#pragma once

#include <opencv2/core.hpp>

namespace AR
{
// TODO: rework this so it doesn't use a lot of gross global variables and doesn't expose the
// arrays

/**
  Camera parameters are obtained from camera calibration and are unique to and constant for
  every camera.

  Each set of CameraParams contains a camera matrix which defines how points in 3D space are
  projected to the 2D image plane of the camera, and a set of distortion coefficients which
  can be used to correct for radial distortion in the image.
*/
class CameraParams
{
private:
	cv::Mat _camera_params;
	cv::Mat _dist_coeff;
public:
	CameraParams(cv::Mat camera_params, cv::Mat dist_coeff);
	cv::Mat getCameraParams() const;
	cv::Mat getDistCoeff() const;
};

// clang-format off

/*
 * Below are all the parameters for various cameras that we have calibrated. Please do not
 * change any of these numbers, as they are automatically generated by the calibration program
 * and the program may not work as intended if they are changed.
 */
enum Params {

	WINSTON_WEBCAM_480,
	WEBCAM_1080,
	WEBCAM_720,
	LAPTOP,
	WEBCAM,
	EVAN_NEW_WEBCAM_480,
	ROBOT_TOP_WEBCAM_480

};
CameraParams getCameraParams (Params params);
// clang-format on

}
