var searchData=
[
  ['narymatiterator_0',['NAryMatIterator',['https://docs.opencv.org/4.2.0/d5/dd2/classcv_1_1NAryMatIterator.html',1,'cv']]],
  ['naturalordering_1',['NaturalOrdering',['https://eigen.tuxfamily.org/dox/classEigen_1_1NaturalOrdering.html',1,'Eigen']]],
  ['ncvbroxopticalflowdescriptor_2',['NCVBroxOpticalFlowDescriptor',['https://docs.opencv.org/4.2.0/db/d7a/structNCVBroxOpticalFlowDescriptor.html',1,'']]],
  ['ncvmatrix_3',['NCVMatrix',['https://docs.opencv.org/4.2.0/de/d26/classNCVMatrix.html',1,'']]],
  ['ncvmatrixalloc_4',['NCVMatrixAlloc',['https://docs.opencv.org/4.2.0/d7/d3a/classNCVMatrixAlloc.html',1,'']]],
  ['ncvmatrixreuse_5',['NCVMatrixReuse',['https://docs.opencv.org/4.2.0/df/d82/classNCVMatrixReuse.html',1,'']]],
  ['ncvmemnativeallocator_6',['NCVMemNativeAllocator',['https://docs.opencv.org/4.2.0/dc/d18/classNCVMemNativeAllocator.html',1,'']]],
  ['ncvmemptr_7',['NCVMemPtr',['https://docs.opencv.org/4.2.0/d6/d86/structNCVMemPtr.html',1,'']]],
  ['ncvmemsegment_8',['NCVMemSegment',['https://docs.opencv.org/4.2.0/d2/d12/structNCVMemSegment.html',1,'']]],
  ['ncvmemstackallocator_9',['NCVMemStackAllocator',['https://docs.opencv.org/4.2.0/db/d74/classNCVMemStackAllocator.html',1,'']]],
  ['ncvpoint2d32s_10',['NcvPoint2D32s',['https://docs.opencv.org/4.2.0/d5/d93/structNcvPoint2D32s.html',1,'']]],
  ['ncvpoint2d32u_11',['NcvPoint2D32u',['https://docs.opencv.org/4.2.0/dc/d16/structNcvPoint2D32u.html',1,'']]],
  ['ncvrect32s_12',['NcvRect32s',['https://docs.opencv.org/4.2.0/d3/dfe/structNcvRect32s.html',1,'']]],
  ['ncvrect32u_13',['NcvRect32u',['https://docs.opencv.org/4.2.0/d0/d62/structNcvRect32u.html',1,'']]],
  ['ncvrect8u_14',['NcvRect8u',['https://docs.opencv.org/4.2.0/da/d3f/structNcvRect8u.html',1,'']]],
  ['ncvsize32s_15',['NcvSize32s',['https://docs.opencv.org/4.2.0/d7/dda/structNcvSize32s.html',1,'']]],
  ['ncvsize32u_16',['NcvSize32u',['https://docs.opencv.org/4.2.0/d8/dde/structNcvSize32u.html',1,'']]],
  ['ncvvector_17',['NCVVector',['https://docs.opencv.org/4.2.0/dc/d73/classNCVVector.html',1,'']]],
  ['ncvvectoralloc_18',['NCVVectorAlloc',['https://docs.opencv.org/4.2.0/d8/da0/classNCVVectorAlloc.html',1,'']]],
  ['ncvvectorreuse_19',['NCVVectorReuse',['https://docs.opencv.org/4.2.0/da/d61/classNCVVectorReuse.html',1,'']]],
  ['nearestinterptr_20',['NearestInterPtr',['https://docs.opencv.org/4.2.0/d0/df5/structcv_1_1cudev_1_1NearestInterPtr.html',1,'cv::cudev']]],
  ['nearestinterptrsz_21',['NearestInterPtrSz',['https://docs.opencv.org/4.2.0/df/dd0/structcv_1_1cudev_1_1NearestInterPtrSz.html',1,'cv::cudev']]],
  ['negate_22',['negate',['https://docs.opencv.org/4.2.0/d9/d77/structcv_1_1cudev_1_1negate.html',1,'cv::cudev::negate&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07375.html',1,'std::negate&lt; class &gt;']]],
  ['negate_3c_20void_20_3e_23',['negate&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07399.html',1,'std']]],
  ['negative_5fbinomial_5fdistribution_24',['negative_binomial_distribution',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06451.html',1,'std']]],
  ['nestbyvalue_25',['NestByValue',['https://eigen.tuxfamily.org/dox/classEigen_1_1NestByValue.html',1,'Eigen']]],
  ['nested_5fexception_26',['nested_exception',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06055.html',1,'std']]],
  ['net_27',['Net',['https://docs.opencv.org/4.2.0/db/d30/classcv_1_1dnn_1_1Net.html',1,'cv::dnn']]],
  ['never_5fadjustor_28',['never_adjustor',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10695.html',1,'__gnu_cxx::limit_condition::never_adjustor'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10719.html',1,'__gnu_cxx::random_condition::never_adjustor']]],
  ['new_5fallocator_29',['new_allocator',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10511.html',1,'__gnu_cxx']]],
  ['no_30',['no',['https://docs.opencv.org/4.2.0/dc/d5a/structcv_1_1cudev_1_1IsUnaryFunction_1_1No.html',1,'cv::cudev::IsUnaryFunction&lt; class &gt;::No'],['https://docs.opencv.org/4.2.0/db/d13/structcv_1_1cudev_1_1IsBinaryFunction_1_1No.html',1,'cv::cudev::IsBinaryFunction&lt; class &gt;::No']]],
  ['no_5fthrow_5fcopies_31',['no_throw_copies',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11515.html',1,'__gnu_pbds::detail']]],
  ['no_5fthrow_5fcopies_3c_20key_2c_20null_5ftype_20_3e_32',['no_throw_copies&lt; Key, null_type &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11519.html',1,'__gnu_pbds::detail']]],
  ['noalias_33',['NoAlias',['https://eigen.tuxfamily.org/dox/classEigen_1_1NoAlias.html',1,'Eigen']]],
  ['nobundleadjuster_34',['NoBundleAdjuster',['https://docs.opencv.org/4.2.0/db/dd4/classcv_1_1detail_1_1NoBundleAdjuster.html',1,'cv::detail']]],
  ['node_35',['node',['https://docs.opencv.org/4.2.0/d4/d7d/classcv_1_1ml_1_1DTrees_1_1Node.html',1,'cv::ml::DTrees::Node'],['https://docs.opencv.org/4.2.0/d3/de3/classcv_1_1Node.html',1,'cv::Node&lt; OBJECT &gt;'],['https://docs.opencv.org/4.2.0/d2/d7d/structcv_1_1optflow_1_1GPCTree_1_1Node.html',1,'cv::optflow::GPCTree::Node'],['https://docs.opencv.org/4.2.0/d9/de0/structcv_1_1SparseMat_1_1Node.html',1,'cv::SparseMat::Node'],['../structNode.html',1,'Node']]],
  ['nodecompare_36',['NodeCompare',['../classNodeCompare.html',1,'']]],
  ['nodedata_37',['NodeData',['https://docs.opencv.org/4.2.0/d7/dc2/classcv_1_1instr_1_1NodeData.html',1,'cv::instr']]],
  ['nodedatatls_38',['NodeDataTls',['https://docs.opencv.org/4.2.0/da/df1/structcv_1_1instr_1_1NodeDataTls.html',1,'cv::instr']]],
  ['nodeequalitycompare_39',['NodeEqualityCompare',['../classNodeEqualityCompare.html',1,'']]],
  ['noexposurecompensator_40',['NoExposureCompensator',['https://docs.opencv.org/4.2.0/d2/dc1/classcv_1_1detail_1_1NoExposureCompensator.html',1,'cv::detail']]],
  ['noisecovmat_41',['NoiseCovMat',['../classfilters_1_1statespace_1_1NoiseCovMat.html',1,'filters::statespace']]],
  ['noisecovmat_3c_20statedim_2c_20outputnoisedim_2c_20outputdim_20_3e_42',['NoiseCovMat&lt; stateDim, outputNoiseDim, outputDim &gt;',['../classfilters_1_1statespace_1_1NoiseCovMat.html',1,'filters::statespace']]],
  ['noisecovmat_3c_20statedim_2c_20processnoisedim_2c_20inputdim_20_3e_43',['NoiseCovMat&lt; stateDim, processNoiseDim, inputDim &gt;',['../classfilters_1_1statespace_1_1NoiseCovMat.html',1,'filters::statespace']]],
  ['noisecovmat_3c_2d1_2c_20_2d1_2c_20_2d1_20_3e_44',['NoiseCovMat&lt;-1, -1, -1 &gt;',['../classfilters_1_1statespace_1_1NoiseCovMat_3-1_00_01-1_00_01-1_01_4.html',1,'filters::statespace']]],
  ['normal_5fdistribution_45',['normal_distribution',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06371.html',1,'std']]],
  ['normal_5fdistribution_3c_20double_20_3e_46',['normal_distribution&lt; double &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06371.html',1,'']]],
  ['normal_5fdistribution_3c_20result_5ftype_20_3e_47',['normal_distribution&lt; result_type &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06371.html',1,'']]],
  ['normalbayesclassifier_48',['NormalBayesClassifier',['https://docs.opencv.org/4.2.0/d4/d8e/classcv_1_1ml_1_1NormalBayesClassifier.html',1,'cv::ml']]],
  ['normalizebboxlayer_49',['NormalizeBBoxLayer',['https://docs.opencv.org/4.2.0/dc/df8/classcv_1_1dnn_1_1NormalizeBBoxLayer.html',1,'cv::dnn']]],
  ['normhamming_50',['NormHamming',['https://docs.opencv.org/4.2.0/d5/d7b/structcv_1_1cudev_1_1NormHamming.html',1,'cv::cudev']]],
  ['normhistogramcostextractor_51',['NormHistogramCostExtractor',['https://docs.opencv.org/4.2.0/df/d65/classcv_1_1NormHistogramCostExtractor.html',1,'cv']]],
  ['norml1_52',['NormL1',['https://docs.opencv.org/4.2.0/d7/df8/structcv_1_1cudev_1_1NormL1.html',1,'cv::cudev']]],
  ['norml1_3c_20float_20_3e_53',['NormL1&lt; float &gt;',['https://docs.opencv.org/4.2.0/d5/d1e/structcv_1_1cudev_1_1NormL1_3_01float_01_4.html',1,'cv::cudev']]],
  ['norml2_54',['NormL2',['https://docs.opencv.org/4.2.0/dc/da6/structcv_1_1cudev_1_1NormL2.html',1,'cv::cudev']]],
  ['noseamfinder_55',['NoSeamFinder',['https://docs.opencv.org/4.2.0/d3/da9/classcv_1_1detail_1_1NoSeamFinder.html',1,'cv::detail']]],
  ['not_5fequal_5fto_56',['not_equal_to',['https://docs.opencv.org/4.2.0/df/d9f/structcv_1_1cudev_1_1not__equal__to.html',1,'cv::cudev::not_equal_to&lt; T &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07407.html',1,'std::not_equal_to&lt; class &gt;']]],
  ['not_5fequal_5fto_3c_20void_20_3e_57',['not_equal_to&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07447.html',1,'std']]],
  ['notag_58',['NoTag',['https://docs.opencv.org/4.2.0/db/d4e/structcv_1_1detail_1_1NoTag.html',1,'cv::detail']]],
  ['notifiable_59',['Notifiable',['../classutil_1_1impl_1_1Notifiable.html',1,'util::impl']]],
  ['nppstinterpolationstate_60',['NppStInterpolationState',['https://docs.opencv.org/4.2.0/da/da9/structNppStInterpolationState.html',1,'']]],
  ['nsobject_61',['NSObject',['https://docs.opencv.org/4.2.0/d4/d19/classNSObject.html',1,'']]],
  ['nsobject_2dp_2dp_62',['NSObject-p-p',['https://docs.opencv.org/4.2.0/d9/d15/classNSObject-p.html',1,'']]],
  ['nsobjectnsobject_2dp_2dp_63',['NSObjectNSObject-p-p',['https://docs.opencv.org/4.2.0/d5/d25/classNSObjectNSObject-p.html',1,'']]],
  ['null_5fnode_5fupdate_64',['null_node_update',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11295.html',1,'__gnu_pbds']]],
  ['null_5ftype_65',['null_type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11291.html',1,'__gnu_pbds']]],
  ['nulldeblurer_66',['NullDeblurer',['https://docs.opencv.org/4.2.0/dc/d86/classcv_1_1videostab_1_1NullDeblurer.html',1,'cv::videostab']]],
  ['nullframesource_67',['NullFrameSource',['https://docs.opencv.org/4.2.0/dd/d5b/classcv_1_1videostab_1_1NullFrameSource.html',1,'cv::videostab']]],
  ['nullinpainter_68',['NullInpainter',['https://docs.opencv.org/4.2.0/d4/d1d/classcv_1_1videostab_1_1NullInpainter.html',1,'cv::videostab']]],
  ['nulllog_69',['NullLog',['https://docs.opencv.org/4.2.0/d6/d78/classcv_1_1videostab_1_1NullLog.html',1,'cv::videostab']]],
  ['nullopt_5ft_70',['nullopt_t',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10079.html',1,'std::experimental::fundamentals_v1']]],
  ['nulloutlierrejector_71',['NullOutlierRejector',['https://docs.opencv.org/4.2.0/d3/de9/classcv_1_1videostab_1_1NullOutlierRejector.html',1,'cv::videostab']]],
  ['nulltype_72',['NullType',['https://docs.opencv.org/4.2.0/d5/d71/structcv_1_1cudev_1_1NullType.html',1,'cv::cudev']]],
  ['nullwobblesuppressor_73',['NullWobbleSuppressor',['https://docs.opencv.org/4.2.0/d0/da4/classcv_1_1videostab_1_1NullWobbleSuppressor.html',1,'cv::videostab']]],
  ['num_5fget_74',['num_get',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a05959.html',1,'std']]],
  ['num_5fput_75',['num_put',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a05963.html',1,'std']]],
  ['numeric_5flimits_76',['numeric_limits',['https://docs.opencv.org/4.2.0/db/dc8/structcv_1_1cudev_1_1numeric__limits.html',1,'cv::cudev::numeric_limits&lt; class &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02519.html',1,'std::numeric_limits&lt; class &gt;']]],
  ['numeric_5flimits_3c_20bool_20_3e_77',['numeric_limits&lt; bool &gt;',['https://docs.opencv.org/4.2.0/da/d81/structcv_1_1cudev_1_1numeric__limits_3_01bool_01_4.html',1,'cv::cudev::numeric_limits&lt; bool &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02535.html',1,'std::numeric_limits&lt; bool &gt;']]],
  ['numeric_5flimits_3c_20char_20_3e_78',['numeric_limits&lt; char &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02539.html',1,'std']]],
  ['numeric_5flimits_3c_20char16_5ft_20_3e_79',['numeric_limits&lt; char16_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02555.html',1,'std']]],
  ['numeric_5flimits_3c_20char32_5ft_20_3e_80',['numeric_limits&lt; char32_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02559.html',1,'std']]],
  ['numeric_5flimits_3c_20double_20_3e_81',['numeric_limits&lt; double &gt;',['https://docs.opencv.org/4.2.0/d2/d80/structcv_1_1cudev_1_1numeric__limits_3_01double_01_4.html',1,'cv::cudev::numeric_limits&lt; double &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02599.html',1,'std::numeric_limits&lt; double &gt;']]],
  ['numeric_5flimits_3c_20float_20_3e_82',['numeric_limits&lt; float &gt;',['https://docs.opencv.org/4.2.0/db/d88/structcv_1_1cudev_1_1numeric__limits_3_01float_01_4.html',1,'cv::cudev::numeric_limits&lt; float &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02595.html',1,'std::numeric_limits&lt; float &gt;']]],
  ['numeric_5flimits_3c_20int_20_3e_83',['numeric_limits&lt; int &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02571.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20_3e_84',['numeric_limits&lt; long &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02579.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20double_20_3e_85',['numeric_limits&lt; long double &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02603.html',1,'std']]],
  ['numeric_5flimits_3c_20long_20long_20_3e_86',['numeric_limits&lt; long long &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02587.html',1,'std']]],
  ['numeric_5flimits_3c_20schar_20_3e_87',['numeric_limits&lt; schar &gt;',['https://docs.opencv.org/4.2.0/da/d4e/structcv_1_1cudev_1_1numeric__limits_3_01schar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20short_20_3e_88',['numeric_limits&lt; short &gt;',['https://docs.opencv.org/4.2.0/d1/d8b/structcv_1_1cudev_1_1numeric__limits_3_01short_01_4.html',1,'cv::cudev::numeric_limits&lt; short &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02563.html',1,'std::numeric_limits&lt; short &gt;']]],
  ['numeric_5flimits_3c_20signed_20char_20_3e_89',['numeric_limits&lt; signed char &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02543.html',1,'std']]],
  ['numeric_5flimits_3c_20uchar_20_3e_90',['numeric_limits&lt; uchar &gt;',['https://docs.opencv.org/4.2.0/d3/dc7/structcv_1_1cudev_1_1numeric__limits_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20uint_20_3e_91',['numeric_limits&lt; uint &gt;',['https://docs.opencv.org/4.2.0/dd/d89/structcv_1_1cudev_1_1numeric__limits_3_01uint_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20unsigned_20char_20_3e_92',['numeric_limits&lt; unsigned char &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02547.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20int_20_3e_93',['numeric_limits&lt; unsigned int &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02575.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20long_20_3e_94',['numeric_limits&lt; unsigned long &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02583.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20long_20long_20_3e_95',['numeric_limits&lt; unsigned long long &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02591.html',1,'std']]],
  ['numeric_5flimits_3c_20unsigned_20short_20_3e_96',['numeric_limits&lt; unsigned short &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02567.html',1,'std']]],
  ['numeric_5flimits_3c_20ushort_20_3e_97',['numeric_limits&lt; ushort &gt;',['https://docs.opencv.org/4.2.0/df/d47/structcv_1_1cudev_1_1numeric__limits_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['numeric_5flimits_3c_20wchar_5ft_20_3e_98',['numeric_limits&lt; wchar_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02551.html',1,'std']]],
  ['numpunct_99',['numpunct',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a05951.html',1,'std']]],
  ['numpunct_5fbyname_100',['numpunct_byname',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a05955.html',1,'std']]],
  ['numtraits_101',['NumTraits',['https://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html',1,'Eigen']]],
  ['numtraits_3c_20scalar_20_3e_102',['NumTraits&lt; Scalar &gt;',['https://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html',1,'']]],
  ['numtraits_3c_20typename_20matrixtype_3a_3ascalar_20_3e_103',['NumTraits&lt; typename MatrixType::Scalar &gt;',['https://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html',1,'']]],
  ['nvidiahwopticalflow_104',['NvidiaHWOpticalFlow',['https://docs.opencv.org/4.2.0/d5/d26/classcv_1_1cuda_1_1NvidiaHWOpticalFlow.html',1,'cv::cuda']]],
  ['nvidiaopticalflow_5f1_5f0_105',['NvidiaOpticalFlow_1_0',['https://docs.opencv.org/4.2.0/dc/d9d/classcv_1_1cuda_1_1NvidiaOpticalFlow__1__0.html',1,'cv::cuda']]]
];
