var searchData=
[
  ['qrcodedetector_0',['QRCodeDetector',['https://docs.opencv.org/4.2.0/de/dc3/classcv_1_1QRCodeDetector.html',1,'cv']]],
  ['qtfont_1',['QtFont',['https://docs.opencv.org/4.2.0/d2/dbf/structcv_1_1QtFont.html',1,'cv']]],
  ['quadedge_2',['QuadEdge',['https://docs.opencv.org/4.2.0/d4/dbc/structcv_1_1Subdiv2D_1_1QuadEdge.html',1,'cv::Subdiv2D']]],
  ['quadratic_5fprobe_5ffn_3',['quadratic_probe_fn',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11147.html',1,'__gnu_pbds']]],
  ['qualitybase_4',['QualityBase',['https://docs.opencv.org/4.2.0/da/d83/classcv_1_1quality_1_1QualityBase.html',1,'cv::quality']]],
  ['qualitybrisque_5',['QualityBRISQUE',['https://docs.opencv.org/4.2.0/d8/d99/classcv_1_1quality_1_1QualityBRISQUE.html',1,'cv::quality']]],
  ['qualitygmsd_6',['QualityGMSD',['https://docs.opencv.org/4.2.0/d8/d81/classcv_1_1quality_1_1QualityGMSD.html',1,'cv::quality']]],
  ['qualitymse_7',['QualityMSE',['https://docs.opencv.org/4.2.0/d7/d80/classcv_1_1quality_1_1QualityMSE.html',1,'cv::quality']]],
  ['qualitypsnr_8',['QualityPSNR',['https://docs.opencv.org/4.2.0/d8/d0c/classcv_1_1quality_1_1QualityPSNR.html',1,'cv::quality']]],
  ['qualityssim_9',['QualitySSIM',['https://docs.opencv.org/4.2.0/d9/db5/classcv_1_1quality_1_1QualitySSIM.html',1,'cv::quality']]],
  ['quantizedpyramid_10',['QuantizedPyramid',['https://docs.opencv.org/4.2.0/d7/d6f/classcv_1_1linemod_1_1QuantizedPyramid.html',1,'cv::linemod']]],
  ['quasidensestereo_11',['QuasiDenseStereo',['https://docs.opencv.org/4.2.0/dc/df4/classcv_1_1stereo_1_1QuasiDenseStereo.html',1,'cv::stereo']]],
  ['quaternion_12',['Quaternion',['https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html',1,'Eigen']]],
  ['quaternion_3c_20double_20_3e_13',['Quaternion&lt; double &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html',1,'Eigen']]],
  ['quaternion_3c_20float_20_3e_14',['Quaternion&lt; float &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html',1,'Eigen']]],
  ['quaternionbase_15',['QuaternionBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html',1,'Eigen']]],
  ['quaternionbase_3c_20map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_20_3e_16',['QuaternionBase&lt; Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html',1,'']]],
  ['quaternionbase_3c_20map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_20_3e_17',['QuaternionBase&lt; Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html',1,'']]],
  ['quaternionbase_3c_20quaternion_3c_20_5fscalar_2c_20_5foptions_20_3e_20_3e_18',['QuaternionBase&lt; Quaternion&lt; _Scalar, _Options &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html',1,'']]],
  ['queue_19',['Queue',['https://docs.opencv.org/4.2.0/dd/dc0/classcv_1_1ocl_1_1Queue.html',1,'cv::ocl']]],
  ['queue_20',['queue',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07807.html',1,'std']]],
  ['quicksort_5ftag_21',['quicksort_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09755.html',1,'__gnu_parallel']]]
];
