var searchData=
[
  ['saliency_0',['Saliency',['https://docs.opencv.org/4.2.0/d9/dcd/classcv_1_1saliency_1_1Saliency.html',1,'cv::saliency']]],
  ['same_5farguments_1',['same_arguments',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1function__traits_1_1same__arguments.html',1,'rclcpp::function_traits']]],
  ['sample_5fprobe_5ffn_2',['sample_probe_fn',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11783.html',1,'__gnu_pbds']]],
  ['sample_5frange_5fhashing_3',['sample_range_hashing',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11787.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fhash_5ffn_4',['sample_ranged_hash_fn',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11791.html',1,'__gnu_pbds']]],
  ['sample_5franged_5fprobe_5ffn_5',['sample_ranged_probe_fn',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11795.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5fpolicy_6',['sample_resize_policy',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12007.html',1,'__gnu_pbds']]],
  ['sample_5fresize_5ftrigger_7',['sample_resize_trigger',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12011.html',1,'__gnu_pbds']]],
  ['sample_5fsize_5fpolicy_8',['sample_size_policy',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12015.html',1,'__gnu_pbds']]],
  ['sample_5ftree_5fnode_5fupdate_9',['sample_tree_node_update',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12059.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5faccess_5ftraits_10',['sample_trie_access_traits',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12079.html',1,'__gnu_pbds']]],
  ['sample_5ftrie_5fnode_5fupdate_11',['sample_trie_node_update',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12083.html',1,'__gnu_pbds']]],
  ['sample_5fupdate_5fpolicy_12',['sample_update_policy',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11859.html',1,'__gnu_pbds']]],
  ['sampling_5ftag_13',['sampling_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09739.html',1,'__gnu_parallel']]],
  ['satcasthelper_14',['SatCastHelper',['https://docs.opencv.org/4.2.0/dc/db0/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_201_2c_20vecd_20_3e_15',['SatCastHelper&lt; 1, VecD &gt;',['https://docs.opencv.org/4.2.0/d2/d31/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_011_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_202_2c_20vecd_20_3e_16',['SatCastHelper&lt; 2, VecD &gt;',['https://docs.opencv.org/4.2.0/dc/dbc/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_012_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_203_2c_20vecd_20_3e_17',['SatCastHelper&lt; 3, VecD &gt;',['https://docs.opencv.org/4.2.0/d8/dbe/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_013_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['satcasthelper_3c_204_2c_20vecd_20_3e_18',['SatCastHelper&lt; 4, VecD &gt;',['https://docs.opencv.org/4.2.0/df/d18/structcv_1_1cudev_1_1vec__math__detail_1_1SatCastHelper_3_014_00_01VecD_01_4.html',1,'cv::cudev::vec_math_detail']]],
  ['saturate_5fcast_5ffp16_5ffunc_19',['saturate_cast_fp16_func',['https://docs.opencv.org/4.2.0/de/d9b/structcv_1_1cudev_1_1saturate__cast__fp16__func.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20float_2c_20short_20_3e_20',['saturate_cast_fp16_func&lt; float, short &gt;',['https://docs.opencv.org/4.2.0/d3/d11/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01float_00_01short_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffp16_5ffunc_3c_20short_2c_20float_20_3e_21',['saturate_cast_fp16_func&lt; short, float &gt;',['https://docs.opencv.org/4.2.0/dc/dc5/structcv_1_1cudev_1_1saturate__cast__fp16__func_3_01short_00_01float_01_4.html',1,'cv::cudev']]],
  ['saturate_5fcast_5ffunc_22',['saturate_cast_func',['https://docs.opencv.org/4.2.0/dc/d99/structcv_1_1cudev_1_1saturate__cast__func.html',1,'cv::cudev']]],
  ['scalar_23',['Scalar',['https://docs.opencv.org/4.2.0/d8/d72/classcv_1_1gapi_1_1own_1_1Scalar.html',1,'cv::gapi::own']]],
  ['scalar_5f_24',['Scalar_',['https://docs.opencv.org/4.2.0/d1/da0/classcv_1_1Scalar__.html',1,'cv']]],
  ['scalar_5f_3c_20double_20_3e_25',['Scalar_&lt; double &gt;',['https://docs.opencv.org/4.2.0/d1/da0/classcv_1_1Scalar__.html',1,'']]],
  ['scalar_5fwrapper_26',['scalar_wrapper',['https://docs.opencv.org/4.2.0/d2/d64/structcv_1_1detail_1_1scalar__wrapper.html',1,'cv::detail']]],
  ['scalar_5fwrapper_5focl_27',['scalar_wrapper_ocl',['https://docs.opencv.org/4.2.0/d2/d3a/structcv_1_1detail_1_1scalar__wrapper__ocl.html',1,'cv::detail']]],
  ['scalarbinaryoptraits_28',['ScalarBinaryOpTraits',['https://eigen.tuxfamily.org/dox/structEigen_1_1ScalarBinaryOpTraits.html',1,'Eigen']]],
  ['scalelayer_29',['ScaleLayer',['https://docs.opencv.org/4.2.0/dd/dde/classcv_1_1dnn_1_1ScaleLayer.html',1,'cv::dnn']]],
  ['scharrxptr_30',['ScharrXPtr',['https://docs.opencv.org/4.2.0/d7/d71/structcv_1_1cudev_1_1ScharrXPtr.html',1,'cv::cudev']]],
  ['scharrxptrsz_31',['ScharrXPtrSz',['https://docs.opencv.org/4.2.0/d2/d88/structcv_1_1cudev_1_1ScharrXPtrSz.html',1,'cv::cudev']]],
  ['scharryptr_32',['ScharrYPtr',['https://docs.opencv.org/4.2.0/d0/d70/structcv_1_1cudev_1_1ScharrYPtr.html',1,'cv::cudev']]],
  ['scharryptrsz_33',['ScharrYPtrSz',['https://docs.opencv.org/4.2.0/dd/def/structcv_1_1cudev_1_1ScharrYPtrSz.html',1,'cv::cudev']]],
  ['scoped_5fallocator_5fadaptor_34',['scoped_allocator_adaptor',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02747.html',1,'std']]],
  ['scoped_5fallocator_5fadaptor_3c_20_5finnerhead_2c_20_5finnertail_2e_2e_2e_20_3e_35',['scoped_allocator_adaptor&lt; _InnerHead, _InnerTail... &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02747.html',1,'']]],
  ['scopedtimer_36',['ScopedTimer',['../classutil_1_1ScopedTimer.html',1,'util']]],
  ['scopeexit_37',['ScopeExit',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1ScopeExit.html',1,'rclcpp']]],
  ['scratch_5fhelper_38',['scratch_helper',['https://docs.opencv.org/4.2.0/db/df4/structcv_1_1detail_1_1scratch__helper.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20false_2c_20impl_2c_20ins_2e_2e_2e_20_3e_39',['scratch_helper&lt; false, Impl, Ins... &gt;',['https://docs.opencv.org/4.2.0/d0/d94/structcv_1_1detail_1_1scratch__helper_3_01false_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['scratch_5fhelper_3c_20true_2c_20impl_2c_20ins_2e_2e_2e_20_3e_40',['scratch_helper&lt; true, Impl, Ins... &gt;',['https://docs.opencv.org/4.2.0/dd/d8e/structcv_1_1detail_1_1scratch__helper_3_01true_00_01Impl_00_01Ins_8_8_8_01_4.html',1,'cv::detail']]],
  ['seamfinder_41',['SeamFinder',['https://docs.opencv.org/4.2.0/d7/d09/classcv_1_1detail_1_1SeamFinder.html',1,'cv::detail']]],
  ['seed_5fseq_42',['seed_seq',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06515.html',1,'std']]],
  ['segmentationmodel_43',['SegmentationModel',['https://docs.opencv.org/4.2.0/da/dce/classcv_1_1dnn_1_1SegmentationModel.html',1,'cv::dnn']]],
  ['segmentationparameters_44',['SegmentationParameters',['https://docs.opencv.org/4.2.0/d9/dbf/structcv_1_1bioinspired_1_1SegmentationParameters.html',1,'cv::bioinspired']]],
  ['select_45',['Select',['https://eigen.tuxfamily.org/dox/classEigen_1_1Select.html',1,'Eigen']]],
  ['select1st_46',['select1st',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09171.html',1,'__gnu_cxx']]],
  ['select2nd_47',['select2nd',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09175.html',1,'__gnu_cxx']]],
  ['selectif_48',['SelectIf',['https://docs.opencv.org/4.2.0/d8/d1b/structcv_1_1cudev_1_1SelectIf.html',1,'cv::cudev']]],
  ['selectif_3c_20false_2c_20thentype_2c_20elsetype_20_3e_49',['SelectIf&lt; false, ThenType, ElseType &gt;',['https://docs.opencv.org/4.2.0/dd/da7/structcv_1_1cudev_1_1SelectIf_3_01false_00_01ThenType_00_01ElseType_01_4.html',1,'cv::cudev']]],
  ['selectivesearchsegmentation_50',['SelectiveSearchSegmentation',['https://docs.opencv.org/4.2.0/d6/d6d/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentation.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategy_51',['SelectiveSearchSegmentationStrategy',['https://docs.opencv.org/4.2.0/dc/d7a/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategy.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategycolor_52',['SelectiveSearchSegmentationStrategyColor',['https://docs.opencv.org/4.2.0/de/dab/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyColor.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategyfill_53',['SelectiveSearchSegmentationStrategyFill',['https://docs.opencv.org/4.2.0/d9/db3/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyFill.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategymultiple_54',['SelectiveSearchSegmentationStrategyMultiple',['https://docs.opencv.org/4.2.0/d8/d8e/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyMultiple.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategysize_55',['SelectiveSearchSegmentationStrategySize',['https://docs.opencv.org/4.2.0/d0/d10/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategySize.html',1,'cv::ximgproc::segmentation']]],
  ['selectivesearchsegmentationstrategytexture_56',['SelectiveSearchSegmentationStrategyTexture',['https://docs.opencv.org/4.2.0/d6/d17/classcv_1_1ximgproc_1_1segmentation_1_1SelectiveSearchSegmentationStrategyTexture.html',1,'cv::ximgproc::segmentation']]],
  ['selfadjointeigensolver_57',['SelfAdjointEigenSolver',['https://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointview_58',['SelfAdjointView',['https://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointView.html',1,'Eigen']]],
  ['selfadjointview_3c_20const_20derived_2c_20uplo_20_3e_59',['SelfAdjointView&lt; const Derived, UpLo &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointView.html',1,'']]],
  ['sensordataqos_60',['SensorDataQoS',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SensorDataQoS.html',1,'rclcpp']]],
  ['sentry_61',['sentry',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02491.html',1,'std::basic_istream&lt; _CharT, _Traits &gt;::sentry'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02639.html',1,'std::basic_ostream&lt; _CharT, _Traits &gt;::sentry']]],
  ['sequence_5ftag_62',['sequence_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11211.html',1,'__gnu_pbds']]],
  ['sequential_5ftag_63',['sequential_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09703.html',1,'__gnu_parallel']]],
  ['sequentialsynchronization_64',['SequentialSynchronization',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1SequentialSynchronization.html',1,'rclcpp::wait_set_policies']]],
  ['serialization_65',['Serialization',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Serialization.html',1,'rclcpp']]],
  ['serializationbase_66',['SerializationBase',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SerializationBase.html',1,'rclcpp']]],
  ['serializedmessage_67',['SerializedMessage',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SerializedMessage.html',1,'rclcpp']]],
  ['service_68',['Service',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'rclcpp']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3adescribeparameters_20_3e_69',['Service&lt; rcl_interfaces::srv::DescribeParameters &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3agetparameters_20_3e_70',['Service&lt; rcl_interfaces::srv::GetParameters &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3agetparametertypes_20_3e_71',['Service&lt; rcl_interfaces::srv::GetParameterTypes &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3alistparameters_20_3e_72',['Service&lt; rcl_interfaces::srv::ListParameters &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3asetparameters_20_3e_73',['Service&lt; rcl_interfaces::srv::SetParameters &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['service_3c_20rcl_5finterfaces_3a_3asrv_3a_3asetparametersatomically_20_3e_74',['Service&lt; rcl_interfaces::srv::SetParametersAtomically &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Service.html',1,'']]],
  ['servicebase_75',['ServiceBase',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1ServiceBase.html',1,'rclcpp']]],
  ['servicesqos_76',['ServicesQoS',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1ServicesQoS.html',1,'rclcpp']]],
  ['set_77',['set',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a08803.html',1,'std::__debug::set&lt; _Key, _Compare, _Allocator &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a08939.html',1,'std::__profile::set&lt; _Key, _Compare, _Allocator &gt;'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07775.html',1,'std::set&lt; _Key, _Compare, _Alloc &gt;']]],
  ['set_3c_20ws_3a_3aconnection_5fhdl_2c_20std_3a_3aowner_5fless_3c_20ws_3a_3aconnection_5fhdl_20_3e_20_3e_78',['set&lt; ws::connection_hdl, std::owner_less&lt; ws::connection_hdl &gt; &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07775.html',1,'std']]],
  ['sfmlibmveuclideanreconstruction_79',['SFMLibmvEuclideanReconstruction',['https://docs.opencv.org/4.2.0/de/d42/classcv_1_1sfm_1_1SFMLibmvEuclideanReconstruction.html',1,'cv::sfm']]],
  ['shapecontextdistanceextractor_80',['ShapeContextDistanceExtractor',['https://docs.opencv.org/4.2.0/d8/de3/classcv_1_1ShapeContextDistanceExtractor.html',1,'cv']]],
  ['shapedistanceextractor_81',['ShapeDistanceExtractor',['https://docs.opencv.org/4.2.0/dc/dbf/classcv_1_1ShapeDistanceExtractor.html',1,'cv']]],
  ['shapetransformer_82',['ShapeTransformer',['https://docs.opencv.org/4.2.0/df/dfe/classcv_1_1ShapeTransformer.html',1,'cv']]],
  ['shared_5ffuture_83',['shared_future',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02243.html',1,'std']]],
  ['shared_5ffuture_3c_20_5fres_20_26_20_3e_84',['shared_future&lt; _Res &amp; &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02359.html',1,'std']]],
  ['shared_5ffuture_3c_20void_20_3e_85',['shared_future&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02363.html',1,'std']]],
  ['shared_5flock_86',['shared_lock',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02783.html',1,'std']]],
  ['shared_5flock_5fguard_87',['shared_lock_guard',['https://docs.opencv.org/4.2.0/d9/d7f/classcv_1_1utils_1_1shared__lock__guard.html',1,'cv::utils']]],
  ['shared_5fptr_88',['shared_ptr',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20_5fdir_20_3e_89',['shared_ptr&lt; _Dir &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20_5fdir_5fstack_20_3e_90',['shared_ptr&lt; _Dir_stack &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20_5fregext_20_3e_91',['shared_ptr&lt; _RegexT &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_20_3e_92',['shared_ptr&lt; _State &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5fbase_20_3e_93',['shared_ptr&lt; _State_base &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20_5fstate_5ftype_20_3e_94',['shared_ptr&lt; _State_type &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20allocator_20_3e_95',['shared_ptr&lt; Allocator &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20ar_3a_3amarkerset_20_3e_96',['shared_ptr&lt; AR::MarkerSet &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20bool_20_3e_97',['shared_ptr&lt; bool &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20bufferalloc_20_3e_98',['shared_ptr&lt; BufferAlloc &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20const_20_5f_5fdetail_3a_3a_5fnfa_3c_20_5frx_5ftraits_20_3e_20_3e_99',['shared_ptr&lt; const __detail::_NFA&lt; _Rx_traits &gt; &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20const_20cv_3a_3aoptflow_3a_3apcaprior_20_3e_100',['shared_ptr&lt; const cv::optflow::PCAPrior &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3aaruco_3a_3adetectorparameters_20_3e_101',['shared_ptr&lt; cv::aruco::DetectorParameters &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3aaruco_3a_3adictionary_20_3e_102',['shared_ptr&lt; cv::aruco::Dictionary &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3abasecascadeclassifier_20_3e_103',['shared_ptr&lt; cv::BaseCascadeClassifier &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3adescriptormatcher_20_3e_104',['shared_ptr&lt; cv::DescriptorMatcher &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3adetail_3a_3afeaturesmatcher_20_3e_105',['shared_ptr&lt; cv::detail::FeaturesMatcher &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3adetail_3a_3atypehintbase_20_3e_106',['shared_ptr&lt; cv::detail::TypeHintBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3adetectionbasedtracker_3a_3aidetector_20_3e_107',['shared_ptr&lt; cv::DetectionBasedTracker::IDetector &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3afeature2d_20_3e_108',['shared_ptr&lt; cv::Feature2D &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3amat_20_3e_109',['shared_ptr&lt; cv::Mat &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3aml_3a_3asvm_20_3e_110',['shared_ptr&lt; cv::ml::SVM &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3aquality_3a_3aqualitymse_20_3e_111',['shared_ptr&lt; cv::quality::QualityMSE &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3argbd_3a_3argbdnormals_20_3e_112',['shared_ptr&lt; cv::rgbd::RgbdNormals &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3astrongclassifierdirectselection_20_3e_113',['shared_ptr&lt; cv::StrongClassifierDirectSelection &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atext_3a_3aocrbeamsearchdecoder_3a_3aclassifiercallback_20_3e_114',['shared_ptr&lt; cv::text::OCRBeamSearchDecoder::ClassifierCallback &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atext_3a_3aocrhmmdecoder_3a_3aclassifiercallback_20_3e_115',['shared_ptr&lt; cv::text::OCRHMMDecoder::ClassifierCallback &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atrackerfeatureset_20_3e_116',['shared_ptr&lt; cv::TrackerFeatureSet &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atrackermodel_20_3e_117',['shared_ptr&lt; cv::TrackerModel &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atrackersampler_20_3e_118',['shared_ptr&lt; cv::TrackerSampler &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atrackerstateestimator_20_3e_119',['shared_ptr&lt; cv::TrackerStateEstimator &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3atracking_3a_3aukfsystemmodel_20_3e_120',['shared_ptr&lt; cv::tracking::UkfSystemModel &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideocapture_20_3e_121',['shared_ptr&lt; cv::VideoCapture &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3adeblurerbase_20_3e_122',['shared_ptr&lt; cv::videostab::DeblurerBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3aiframesource_20_3e_123',['shared_ptr&lt; cv::videostab::IFrameSource &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3ailog_20_3e_124',['shared_ptr&lt; cv::videostab::ILog &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3aimagemotionestimatorbase_20_3e_125',['shared_ptr&lt; cv::videostab::ImageMotionEstimatorBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3aimotionstabilizer_20_3e_126',['shared_ptr&lt; cv::videostab::IMotionStabilizer &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3ainpainterbase_20_3e_127',['shared_ptr&lt; cv::videostab::InpainterBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3amotionfilterbase_20_3e_128',['shared_ptr&lt; cv::videostab::MotionFilterBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cv_3a_3avideostab_3a_3awobblesuppressorbase_20_3e_129',['shared_ptr&lt; cv::videostab::WobbleSuppressorBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cvcapture_20_3e_130',['shared_ptr&lt; CvCapture &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20cvvideowriter_20_3e_131',['shared_ptr&lt; CvVideoWriter &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20flann_3a_3aindex_20_3e_132',['shared_ptr&lt; flann::Index &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20flann_3a_3aindexparams_20_3e_133',['shared_ptr&lt; flann::IndexParams &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20flann_3a_3asearchparams_20_3e_134',['shared_ptr&lt; flann::SearchParams &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20gorigin_20_3e_135',['shared_ptr&lt; GOrigin &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20imghashimpl_20_3e_136',['shared_ptr&lt; ImgHashImpl &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20impl_20_3e_137',['shared_ptr&lt; Impl &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20ivideocapture_20_3e_138',['shared_ptr&lt; IVideoCapture &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20ivideowriter_20_3e_139',['shared_ptr&lt; IVideoWriter &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20messagealloc_20_3e_140',['shared_ptr&lt; MessageAlloc &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20messageallocator_20_3e_141',['shared_ptr&lt; MessageAllocator &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20messaget_20_3e_142',['shared_ptr&lt; MessageT &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20priv_20_3e_143',['shared_ptr&lt; Priv &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20quadtree_20_3e_144',['shared_ptr&lt; QuadTree &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5fclient_5ft_20_3e_145',['shared_ptr&lt; rcl_client_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5fnode_5ft_20_3e_146',['shared_ptr&lt; rcl_node_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5fpublisher_5ft_20_3e_147',['shared_ptr&lt; rcl_publisher_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5fservice_5ft_20_3e_148',['shared_ptr&lt; rcl_service_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5fsubscription_5ft_20_3e_149',['shared_ptr&lt; rcl_subscription_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rcl_5ftimer_5ft_20_3e_150',['shared_ptr&lt; rcl_timer_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3acallbackgroup_20_3e_151',['shared_ptr&lt; rclcpp::CallbackGroup &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3acontext_20_3e_152',['shared_ptr&lt; rclcpp::Context &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3adetail_3a_3armwimplementationspecificpublisherpayload_20_3e_153',['shared_ptr&lt; rclcpp::detail::RMWImplementationSpecificPublisherPayload &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3adetail_3a_3armwimplementationspecificsubscriptionpayload_20_3e_154',['shared_ptr&lt; rclcpp::detail::RMWImplementationSpecificSubscriptionPayload &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3asubscriptionbase_20_3e_155',['shared_ptr&lt; rclcpp::SubscriptionBase &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20rclcpp_3a_3awaitable_20_3e_156',['shared_ptr&lt; rclcpp::Waitable &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20separatedetectionwork_20_3e_157',['shared_ptr&lt; SeparateDetectionWork &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20serializedmessagealloc_20_3e_158',['shared_ptr&lt; SerializedMessageAlloc &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20std_3a_3aallocator_3c_20void_20_3e_20_3e_159',['shared_ptr&lt; std::allocator&lt; void &gt; &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20std_3a_3achrono_3a_3atime_5fpoint_20_3e_160',['shared_ptr&lt; std::chrono::time_point &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20std_3a_3adeque_3c_20int_20_3e_20_3e_161',['shared_ptr&lt; std::deque&lt; int &gt; &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20std_3a_3amutex_20_3e_162',['shared_ptr&lt; std::mutex &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'']]],
  ['shared_5fptr_3c_20std_3a_3athread_20_3e_163',['shared_ptr&lt; std::thread &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20uint32_5ft_20_3e_164',['shared_ptr&lt; uint32_t &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20videoinputstream_20_3e_165',['shared_ptr&lt; VideoInputStream &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5fptr_3c_20void_20_3e_166',['shared_ptr&lt; void &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06899.html',1,'std']]],
  ['shared_5ftimed_5fmutex_167',['shared_timed_mutex',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02779.html',1,'std']]],
  ['shiftlayer_168',['ShiftLayer',['https://docs.opencv.org/4.2.0/d3/dd8/classcv_1_1dnn_1_1ShiftLayer.html',1,'cv::dnn']]],
  ['shuffle_5forder_5fengine_169',['shuffle_order_engine',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06351.html',1,'std']]],
  ['shufflechannellayer_170',['ShuffleChannelLayer',['https://docs.opencv.org/4.2.0/de/d24/classcv_1_1dnn_1_1ShuffleChannelLayer.html',1,'cv::dnn']]],
  ['sift_171',['SIFT',['https://docs.opencv.org/4.2.0/d5/d3c/classcv_1_1xfeatures2d_1_1SIFT.html',1,'cv::xfeatures2d']]],
  ['sigmoidlayer_172',['SigmoidLayer',['https://docs.opencv.org/4.2.0/dc/d09/classcv_1_1dnn_1_1SigmoidLayer.html',1,'cv::dnn']]],
  ['similarrects_173',['SimilarRects',['https://docs.opencv.org/4.2.0/d1/d65/classcv_1_1SimilarRects.html',1,'cv']]],
  ['simpleblobdetector_174',['SimpleBlobDetector',['https://docs.opencv.org/4.2.0/d0/d7a/classcv_1_1SimpleBlobDetector.html',1,'cv']]],
  ['simplewb_175',['SimpleWB',['https://docs.opencv.org/4.2.0/d1/d8b/classcv_1_1xphoto_1_1SimpleWB.html',1,'cv::xphoto']]],
  ['simplicialcholesky_176',['SimplicialCholesky',['https://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase_177',['SimplicialCholeskyBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialldlt_178',['SimplicialLDLT',['https://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialLDLT.html',1,'Eigen']]],
  ['simplicialllt_179',['SimplicialLLT',['https://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialLLT.html',1,'Eigen']]],
  ['simulatedannealingsolversystem_180',['SimulatedAnnealingSolverSystem',['https://docs.opencv.org/4.2.0/dc/db4/structcv_1_1ml_1_1SimulatedAnnealingSolverSystem.html',1,'cv::ml']]],
  ['sin_5ffunc_181',['sin_func',['https://docs.opencv.org/4.2.0/d1/d05/structcv_1_1cudev_1_1sin__func.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20double_20_3e_182',['sin_func&lt; double &gt;',['https://docs.opencv.org/4.2.0/d8/d1c/structcv_1_1cudev_1_1sin__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20float_20_3e_183',['sin_func&lt; float &gt;',['https://docs.opencv.org/4.2.0/d6/d2b/structcv_1_1cudev_1_1sin__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20schar_20_3e_184',['sin_func&lt; schar &gt;',['https://docs.opencv.org/4.2.0/d8/d1b/structcv_1_1cudev_1_1sin__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20short_20_3e_185',['sin_func&lt; short &gt;',['https://docs.opencv.org/4.2.0/dd/d6f/structcv_1_1cudev_1_1sin__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uchar_20_3e_186',['sin_func&lt; uchar &gt;',['https://docs.opencv.org/4.2.0/d2/dfd/structcv_1_1cudev_1_1sin__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20uint_20_3e_187',['sin_func&lt; uint &gt;',['https://docs.opencv.org/4.2.0/d5/dbd/structcv_1_1cudev_1_1sin__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sin_5ffunc_3c_20ushort_20_3e_188',['sin_func&lt; ushort &gt;',['https://docs.opencv.org/4.2.0/d8/d22/structcv_1_1cudev_1_1sin__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['singleclientwsserver_189',['SingleClientWSServer',['../classwebsocket_1_1SingleClientWSServer.html',1,'websocket']]],
  ['singlemaskchannels_190',['SingleMaskChannels',['https://docs.opencv.org/4.2.0/db/dce/structcv_1_1cudev_1_1SingleMaskChannels.html',1,'cv::cudev']]],
  ['singlemaskchannelssz_191',['SingleMaskChannelsSz',['https://docs.opencv.org/4.2.0/d0/d19/structcv_1_1cudev_1_1SingleMaskChannelsSz.html',1,'cv::cudev']]],
  ['singlethreadedexecutor_192',['SingleThreadedExecutor',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1executors_1_1SingleThreadedExecutor.html',1,'rclcpp::executors']]],
  ['sinh_5ffunc_193',['sinh_func',['https://docs.opencv.org/4.2.0/d8/da0/structcv_1_1cudev_1_1sinh__func.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20double_20_3e_194',['sinh_func&lt; double &gt;',['https://docs.opencv.org/4.2.0/db/dde/structcv_1_1cudev_1_1sinh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20float_20_3e_195',['sinh_func&lt; float &gt;',['https://docs.opencv.org/4.2.0/d3/df1/structcv_1_1cudev_1_1sinh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20schar_20_3e_196',['sinh_func&lt; schar &gt;',['https://docs.opencv.org/4.2.0/de/df6/structcv_1_1cudev_1_1sinh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20short_20_3e_197',['sinh_func&lt; short &gt;',['https://docs.opencv.org/4.2.0/da/d3e/structcv_1_1cudev_1_1sinh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uchar_20_3e_198',['sinh_func&lt; uchar &gt;',['https://docs.opencv.org/4.2.0/d4/dd2/structcv_1_1cudev_1_1sinh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20uint_20_3e_199',['sinh_func&lt; uint &gt;',['https://docs.opencv.org/4.2.0/de/d13/structcv_1_1cudev_1_1sinh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sinh_5ffunc_3c_20ushort_20_3e_200',['sinh_func&lt; ushort &gt;',['https://docs.opencv.org/4.2.0/d9/d38/structcv_1_1cudev_1_1sinh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['sinusoidalpattern_201',['SinusoidalPattern',['https://docs.opencv.org/4.2.0/d6/d96/classcv_1_1structured__light_1_1SinusoidalPattern.html',1,'cv::structured_light']]],
  ['size_202',['Size',['https://docs.opencv.org/4.2.0/d7/d3e/classcv_1_1gapi_1_1own_1_1Size.html',1,'cv::gapi::own']]],
  ['size_5f_203',['Size_',['https://docs.opencv.org/4.2.0/d6/d50/classcv_1_1Size__.html',1,'cv']]],
  ['size_5f_3c_20float_20_3e_204',['Size_&lt; float &gt;',['https://docs.opencv.org/4.2.0/d6/d50/classcv_1_1Size__.html',1,'']]],
  ['skeleton_205',['skeleton',['https://docs.opencv.org/4.2.0/d4/d66/structcv_1_1datasets_1_1skeleton.html',1,'cv::datasets']]],
  ['sl2_206',['SL2',['https://docs.opencv.org/4.2.0/d5/d46/structcv_1_1SL2.html',1,'cv']]],
  ['slam_5fkitti_207',['SLAM_kitti',['https://docs.opencv.org/4.2.0/d6/d92/classcv_1_1datasets_1_1SLAM__kitti.html',1,'cv::datasets']]],
  ['slam_5fkittiobj_208',['SLAM_kittiObj',['https://docs.opencv.org/4.2.0/da/df4/structcv_1_1datasets_1_1SLAM__kittiObj.html',1,'cv::datasets']]],
  ['slam_5ftumindoor_209',['SLAM_tumindoor',['https://docs.opencv.org/4.2.0/da/d91/classcv_1_1datasets_1_1SLAM__tumindoor.html',1,'cv::datasets']]],
  ['slam_5ftumindoorobj_210',['SLAM_tumindoorObj',['https://docs.opencv.org/4.2.0/d7/d56/structcv_1_1datasets_1_1SLAM__tumindoorObj.html',1,'cv::datasets']]],
  ['slice_211',['slice',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07115.html',1,'std']]],
  ['slice_5farray_212',['slice_array',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a04651.html',1,'std']]],
  ['slicelayer_213',['SliceLayer',['https://docs.opencv.org/4.2.0/de/d61/classcv_1_1dnn_1_1SliceLayer.html',1,'cv::dnn']]],
  ['slist_214',['slist',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09335.html',1,'__gnu_cxx']]],
  ['sobelxptr_215',['SobelXPtr',['https://docs.opencv.org/4.2.0/de/dc8/structcv_1_1cudev_1_1SobelXPtr.html',1,'cv::cudev']]],
  ['sobelxptrsz_216',['SobelXPtrSz',['https://docs.opencv.org/4.2.0/d7/d84/structcv_1_1cudev_1_1SobelXPtrSz.html',1,'cv::cudev']]],
  ['sobelyptr_217',['SobelYPtr',['https://docs.opencv.org/4.2.0/d0/da6/structcv_1_1cudev_1_1SobelYPtr.html',1,'cv::cudev']]],
  ['sobelyptrsz_218',['SobelYPtrSz',['https://docs.opencv.org/4.2.0/dd/dc6/structcv_1_1cudev_1_1SobelYPtrSz.html',1,'cv::cudev']]],
  ['softdouble_219',['softdouble',['https://docs.opencv.org/4.2.0/de/df1/structcv_1_1softdouble.html',1,'cv']]],
  ['softfloat_220',['softfloat',['https://docs.opencv.org/4.2.0/d7/d2f/structcv_1_1softfloat.html',1,'cv']]],
  ['softmaxlayer_221',['SoftmaxLayer',['https://docs.opencv.org/4.2.0/d8/d18/classcv_1_1dnn_1_1SoftmaxLayer.html',1,'cv::dnn']]],
  ['solve_222',['Solve',['https://eigen.tuxfamily.org/dox/classEigen_1_1Solve.html',1,'Eigen']]],
  ['solverbase_223',['SolverBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'Eigen']]],
  ['solverbase_3c_20colpivhouseholderqr_3c_20_5fmatrixtype_20_3e_20_3e_224',['SolverBase&lt; ColPivHouseholderQR&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20colpivhouseholderqr_3c_20matrixtype_20_3e_20_3e_225',['SolverBase&lt; ColPivHouseholderQR&lt; MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20completeorthogonaldecomposition_3c_20_5fmatrixtype_20_3e_20_3e_226',['SolverBase&lt; CompleteOrthogonalDecomposition&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20fullpivhouseholderqr_3c_20_5fmatrixtype_20_3e_20_3e_227',['SolverBase&lt; FullPivHouseholderQR&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20fullpivlu_3c_20_5fmatrixtype_20_3e_20_3e_228',['SolverBase&lt; FullPivLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20householderqr_3c_20_5fmatrixtype_20_3e_20_3e_229',['SolverBase&lt; HouseholderQR&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20ldlt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e_230',['SolverBase&lt; LDLT&lt; _MatrixType, _UpLo &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20llt_3c_20_5fmatrixtype_2c_20_5fuplo_20_3e_20_3e_231',['SolverBase&lt; LLT&lt; _MatrixType, _UpLo &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20partialpivlu_3c_20_5fmatrixtype_20_3e_20_3e_232',['SolverBase&lt; PartialPivLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20svdbase_3c_20derived_20_3e_20_3e_233',['SolverBase&lt; SVDBase&lt; Derived &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverbase_3c_20svdbase_3c_20jacobisvd_3c_20_5fmatrixtype_2c_20qrpreconditioner_20_3e_20_3e_20_3e_234',['SolverBase&lt; SVDBase&lt; JacobiSVD&lt; _MatrixType, QRPreconditioner &gt; &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolverBase.html',1,'']]],
  ['solverstorage_235',['SolverStorage',['https://eigen.tuxfamily.org/dox/structEigen_1_1SolverStorage.html',1,'Eigen']]],
  ['solvewithguess_236',['SolveWithGuess',['https://eigen.tuxfamily.org/dox/classEigen_1_1SolveWithGuess.html',1,'Eigen']]],
  ['sparse_237',['Sparse',['https://eigen.tuxfamily.org/dox/structEigen_1_1Sparse.html',1,'Eigen']]],
  ['sparsecompressedbase_238',['SparseCompressedBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'Eigen']]],
  ['sparsecompressedbase_3c_20block_3c_20const_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e_239',['SparseCompressedBase&lt; Block&lt; const SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e_240',['SparseCompressedBase&lt; Block&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt;, BlockRows, BlockCols, true &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20block_3c_20sparsematrixtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e_241',['SparseCompressedBase&lt; Block&lt; SparseMatrixType, BlockRows, BlockCols, true &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20derived_20_3e_242',['SparseCompressedBase&lt; Derived &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e_243',['SparseCompressedBase&lt; SparseMatrix&lt; _Scalar, _Options, _StorageIndex &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20scalar_2c_20_5foptions_2c_20_5fstorageindex_20_3e_20_3e_244',['SparseCompressedBase&lt; SparseMatrix&lt; Scalar, _Options, _StorageIndex &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20scalar_2c_20_5foptions_2c_20int_20_3e_20_3e_245',['SparseCompressedBase&lt; SparseMatrix&lt; Scalar, _Options, int &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20sparsematrix_3c_20scalar_2c_20_5foptions_2c_20storageindex_20_3e_20_3e_246',['SparseCompressedBase&lt; SparseMatrix&lt; Scalar, _Options, StorageIndex &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparsecompressedbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e_247',['SparseCompressedBase&lt; Transpose&lt; MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseCompressedBase.html',1,'']]],
  ['sparselu_248',['SparseLU',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseLU.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20readonlyaccessors_20_3e_249',['SparseMapBase&lt; Derived, ReadOnlyAccessors &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMapBase_3_01Derived_00_01ReadOnlyAccessors_01_4.html',1,'Eigen']]],
  ['sparsemapbase_3c_20derived_2c_20writeaccessors_20_3e_250',['SparseMapBase&lt; Derived, WriteAccessors &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMapBase_3_01Derived_00_01WriteAccessors_01_4.html',1,'Eigen']]],
  ['sparsemat_251',['SparseMat',['https://docs.opencv.org/4.2.0/dd/da9/classcv_1_1SparseMat.html',1,'cv']]],
  ['sparsemat_5f_252',['SparseMat_',['https://docs.opencv.org/4.2.0/d7/d8a/classcv_1_1SparseMat__.html',1,'cv']]],
  ['sparsematchinterpolator_253',['SparseMatchInterpolator',['https://docs.opencv.org/4.2.0/d4/da8/classcv_1_1ximgproc_1_1SparseMatchInterpolator.html',1,'cv::ximgproc']]],
  ['sparsematconstiterator_254',['SparseMatConstIterator',['https://docs.opencv.org/4.2.0/df/dec/classcv_1_1SparseMatConstIterator.html',1,'cv']]],
  ['sparsematconstiterator_5f_255',['SparseMatConstIterator_',['https://docs.opencv.org/4.2.0/d9/d29/classcv_1_1SparseMatConstIterator__.html',1,'cv']]],
  ['sparsematiterator_256',['SparseMatIterator',['https://docs.opencv.org/4.2.0/d5/d9b/classcv_1_1SparseMatIterator.html',1,'cv']]],
  ['sparsematiterator_5f_257',['SparseMatIterator_',['https://docs.opencv.org/4.2.0/d3/d24/classcv_1_1SparseMatIterator__.html',1,'cv']]],
  ['sparsematrix_258',['SparseMatrix',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrix_3c_20scalar_20_3e_259',['SparseMatrix&lt; Scalar &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20int_20_3e_260',['SparseMatrix&lt; Scalar, ColMajor, int &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'']]],
  ['sparsematrix_3c_20scalar_2c_20colmajor_2c_20storageindex_20_3e_261',['SparseMatrix&lt; Scalar, ColMajor, StorageIndex &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'']]],
  ['sparsematrix_3c_20scalar_2c_20rowmajor_2c_20storageindex_20_3e_262',['SparseMatrix&lt; Scalar, RowMajor, StorageIndex &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'']]],
  ['sparsematrixbase_263',['SparseMatrixBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e_264',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20true_20_3e_20_3e_265',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, true &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'']]],
  ['sparsematrixbase_3c_20cwisebinaryop_3c_20binaryop_2c_20lhs_2c_20rhs_20_3e_20_3e_266',['SparseMatrixBase&lt; CwiseBinaryOp&lt; BinaryOp, Lhs, Rhs &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'']]],
  ['sparsematrixbase_3c_20transpose_3c_20matrixtype_20_3e_20_3e_267',['SparseMatrixBase&lt; Transpose&lt; MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'']]],
  ['sparsematrixbase_3c_20triangularview_3c_20matrixtype_2c_20mode_20_3e_20_3e_268',['SparseMatrixBase&lt; TriangularView&lt; MatrixType, Mode &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'']]],
  ['sparseopticalflow_269',['SparseOpticalFlow',['https://docs.opencv.org/4.2.0/d5/dcf/classcv_1_1cuda_1_1SparseOpticalFlow.html',1,'cv::cuda::SparseOpticalFlow'],['https://docs.opencv.org/4.2.0/de/d14/classcv_1_1SparseOpticalFlow.html',1,'cv::SparseOpticalFlow']]],
  ['sparsepyrlkoptflowestimator_270',['SparsePyrLkOptFlowEstimator',['https://docs.opencv.org/4.2.0/d1/d4b/classcv_1_1videostab_1_1SparsePyrLkOptFlowEstimator.html',1,'cv::videostab']]],
  ['sparsepyrlkopticalflow_271',['SparsePyrLKOpticalFlow',['https://docs.opencv.org/4.2.0/d7/d05/classcv_1_1cuda_1_1SparsePyrLKOpticalFlow.html',1,'cv::cuda::SparsePyrLKOpticalFlow'],['https://docs.opencv.org/4.2.0/d7/d08/classcv_1_1SparsePyrLKOpticalFlow.html',1,'cv::SparsePyrLKOpticalFlow']]],
  ['sparseqr_272',['SparseQR',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseQR.html',1,'Eigen']]],
  ['sparserlofopticalflow_273',['SparseRLOFOpticalFlow',['https://docs.opencv.org/4.2.0/df/dc4/classcv_1_1optflow_1_1SparseRLOFOpticalFlow.html',1,'cv::optflow']]],
  ['sparseselfadjointview_274',['SparseSelfAdjointView',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSelfAdjointView.html',1,'Eigen']]],
  ['sparseselfadjointview_3c_20const_20derived_2c_20uplo_20_3e_275',['SparseSelfAdjointView&lt; const Derived, UpLo &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSelfAdjointView.html',1,'']]],
  ['sparsesolverbase_276',['SparseSolverBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'Eigen']]],
  ['sparsesolverbase_3c_20cholmoddecomposition_3c_20_5fmatrixtype_2c_20lower_20_3e_20_3e_277',['SparseSolverBase&lt; CholmodDecomposition&lt; _MatrixType, Lower &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20cholmodsimplicialldlt_3c_20_5fmatrixtype_2c_20lower_20_3e_20_3e_278',['SparseSolverBase&lt; CholmodSimplicialLDLT&lt; _MatrixType, Lower &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20cholmodsimplicialllt_3c_20_5fmatrixtype_2c_20lower_20_3e_20_3e_279',['SparseSolverBase&lt; CholmodSimplicialLLT&lt; _MatrixType, Lower &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20cholmodsupernodalllt_3c_20_5fmatrixtype_2c_20lower_20_3e_20_3e_280',['SparseSolverBase&lt; CholmodSupernodalLLT&lt; _MatrixType, Lower &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20incompletecholesky_3c_20scalar_2c_20lower_2c_20amdordering_3c_20int_20_3e_20_3e_20_3e_281',['SparseSolverBase&lt; IncompleteCholesky&lt; Scalar, Lower, AMDOrdering&lt; int &gt; &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20incompletelut_3c_20_5fscalar_2c_20int_20_3e_20_3e_282',['SparseSolverBase&lt; IncompleteLUT&lt; _Scalar, int &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20klu_3c_20_5fmatrixtype_20_3e_20_3e_283',['SparseSolverBase&lt; KLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20sparselutransposeview_3c_20conjugate_2c_20sparselutype_20_3e_20_3e_284',['SparseSolverBase&lt; SparseLUTransposeView&lt; Conjugate, SparseLUType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20superilu_3c_20_5fmatrixtype_20_3e_20_3e_285',['SparseSolverBase&lt; SuperILU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e_286',['SparseSolverBase&lt; SuperLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsesolverbase_3c_20umfpacklu_3c_20_5fmatrixtype_20_3e_20_3e_287',['SparseSolverBase&lt; UmfPackLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseSolverBase.html',1,'']]],
  ['sparsevector_288',['SparseVector',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseVector.html',1,'Eigen']]],
  ['sparseview_289',['SparseView',['https://eigen.tuxfamily.org/dox/classEigen_1_1SparseView.html',1,'Eigen']]],
  ['sphericalportraitprojector_290',['SphericalPortraitProjector',['https://docs.opencv.org/4.2.0/d3/d0d/structcv_1_1detail_1_1SphericalPortraitProjector.html',1,'cv::detail']]],
  ['sphericalportraitwarper_291',['SphericalPortraitWarper',['https://docs.opencv.org/4.2.0/d8/d70/classcv_1_1detail_1_1SphericalPortraitWarper.html',1,'cv::detail']]],
  ['sphericalprojector_292',['SphericalProjector',['https://docs.opencv.org/4.2.0/d0/d88/structcv_1_1detail_1_1SphericalProjector.html',1,'cv::detail']]],
  ['sphericalwarper_293',['SphericalWarper',['https://docs.opencv.org/4.2.0/d6/dd0/classcv_1_1detail_1_1SphericalWarper.html',1,'cv::detail::SphericalWarper'],['https://docs.opencv.org/4.2.0/d3/d3c/classcv_1_1SphericalWarper.html',1,'cv::SphericalWarper']]],
  ['sphericalwarpergpu_294',['SphericalWarperGpu',['https://docs.opencv.org/4.2.0/db/d09/classcv_1_1detail_1_1SphericalWarperGpu.html',1,'cv::detail']]],
  ['splay_5ftree_5fmap_295',['splay_tree_map',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12027.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5fnode_5f_296',['splay_tree_node_',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a12019.html',1,'__gnu_pbds::detail']]],
  ['splay_5ftree_5ftag_297',['splay_tree_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11247.html',1,'__gnu_pbds']]],
  ['split_298',['Split',['https://docs.opencv.org/4.2.0/d9/d37/classcv_1_1ml_1_1DTrees_1_1Split.html',1,'cv::ml::DTrees']]],
  ['splitlayer_299',['SplitLayer',['https://docs.opencv.org/4.2.0/dd/df9/classcv_1_1dnn_1_1SplitLayer.html',1,'cv::dnn']]],
  ['spqr_300',['SPQR',['https://eigen.tuxfamily.org/dox/classEigen_1_1SPQR.html',1,'Eigen']]],
  ['sqr_5ffunc_301',['sqr_func',['https://docs.opencv.org/4.2.0/d9/d1d/structcv_1_1cudev_1_1sqr__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_302',['sqrt_func',['https://docs.opencv.org/4.2.0/d9/d47/structcv_1_1cudev_1_1sqrt__func.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20double_20_3e_303',['sqrt_func&lt; double &gt;',['https://docs.opencv.org/4.2.0/d4/d9d/structcv_1_1cudev_1_1sqrt__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20float_20_3e_304',['sqrt_func&lt; float &gt;',['https://docs.opencv.org/4.2.0/d8/dd2/structcv_1_1cudev_1_1sqrt__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20schar_20_3e_305',['sqrt_func&lt; schar &gt;',['https://docs.opencv.org/4.2.0/da/d64/structcv_1_1cudev_1_1sqrt__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20short_20_3e_306',['sqrt_func&lt; short &gt;',['https://docs.opencv.org/4.2.0/d2/d6a/structcv_1_1cudev_1_1sqrt__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uchar_20_3e_307',['sqrt_func&lt; uchar &gt;',['https://docs.opencv.org/4.2.0/d9/d33/structcv_1_1cudev_1_1sqrt__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20uint_20_3e_308',['sqrt_func&lt; uint &gt;',['https://docs.opencv.org/4.2.0/d0/d7b/structcv_1_1cudev_1_1sqrt__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['sqrt_5ffunc_3c_20ushort_20_3e_309',['sqrt_func&lt; ushort &gt;',['https://docs.opencv.org/4.2.0/df/df4/structcv_1_1cudev_1_1sqrt__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['sr_5fbsds_310',['SR_bsds',['https://docs.opencv.org/4.2.0/d6/d05/classcv_1_1datasets_1_1SR__bsds.html',1,'cv::datasets']]],
  ['sr_5fbsdsobj_311',['SR_bsdsObj',['https://docs.opencv.org/4.2.0/dc/d1e/structcv_1_1datasets_1_1SR__bsdsObj.html',1,'cv::datasets']]],
  ['sr_5fdiv2k_312',['SR_div2k',['https://docs.opencv.org/4.2.0/d2/db5/classcv_1_1datasets_1_1SR__div2k.html',1,'cv::datasets']]],
  ['sr_5fdiv2kobj_313',['SR_div2kObj',['https://docs.opencv.org/4.2.0/d1/db5/structcv_1_1datasets_1_1SR__div2kObj.html',1,'cv::datasets']]],
  ['sr_5fgeneral100_314',['SR_general100',['https://docs.opencv.org/4.2.0/d5/d19/classcv_1_1datasets_1_1SR__general100.html',1,'cv::datasets']]],
  ['sr_5fgeneral100obj_315',['SR_general100Obj',['https://docs.opencv.org/4.2.0/da/dad/structcv_1_1datasets_1_1SR__general100Obj.html',1,'cv::datasets']]],
  ['stabilizerbase_316',['StabilizerBase',['https://docs.opencv.org/4.2.0/d2/d6c/classcv_1_1videostab_1_1StabilizerBase.html',1,'cv::videostab']]],
  ['stack_317',['stack',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07827.html',1,'std']]],
  ['stack_3c_20_5fstateseqt_20_3e_318',['stack&lt; _StateSeqT &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a07827.html',1,'']]],
  ['standardcollector_319',['StandardCollector',['https://docs.opencv.org/4.2.0/d4/d8d/classcv_1_1face_1_1StandardCollector.html',1,'cv::face']]],
  ['stardetector_320',['StarDetector',['https://docs.opencv.org/4.2.0/dd/d39/classcv_1_1xfeatures2d_1_1StarDetector.html',1,'cv::xfeatures2d']]],
  ['starkernelcensus_321',['StarKernelCensus',['https://docs.opencv.org/4.2.0/db/d3b/classcv_1_1stereo_1_1StarKernelCensus.html',1,'cv::stereo']]],
  ['staticexecutorentitiescollector_322',['StaticExecutorEntitiesCollector',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1executors_1_1StaticExecutorEntitiesCollector.html',1,'rclcpp::executors']]],
  ['staticsaliency_323',['StaticSaliency',['https://docs.opencv.org/4.2.0/d5/d87/classcv_1_1saliency_1_1StaticSaliency.html',1,'cv::saliency']]],
  ['staticsaliencyfinegrained_324',['StaticSaliencyFineGrained',['https://docs.opencv.org/4.2.0/da/dd0/classcv_1_1saliency_1_1StaticSaliencyFineGrained.html',1,'cv::saliency']]],
  ['staticsaliencyspectralresidual_325',['StaticSaliencySpectralResidual',['https://docs.opencv.org/4.2.0/df/d37/classcv_1_1saliency_1_1StaticSaliencySpectralResidual.html',1,'cv::saliency']]],
  ['staticsinglethreadedexecutor_326',['StaticSingleThreadedExecutor',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1executors_1_1StaticSingleThreadedExecutor.html',1,'rclcpp::executors']]],
  ['staticstorage_327',['StaticStorage',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1StaticStorage.html',1,'rclcpp::wait_set_policies']]],
  ['statmodel_328',['StatModel',['https://docs.opencv.org/4.2.0/db/d7d/classcv_1_1ml_1_1StatModel.html',1,'cv::ml']]],
  ['stdio_5ffilebuf_329',['stdio_filebuf',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10667.html',1,'__gnu_cxx']]],
  ['stdio_5fsync_5ffilebuf_330',['stdio_sync_filebuf',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a10671.html',1,'__gnu_cxx']]],
  ['steady_5fclock_331',['steady_clock',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01915.html',1,'std::chrono::_V2']]],
  ['stereobeliefpropagation_332',['StereoBeliefPropagation',['https://docs.opencv.org/4.2.0/de/d7a/classcv_1_1cuda_1_1StereoBeliefPropagation.html',1,'cv::cuda']]],
  ['stereobinarybm_333',['StereoBinaryBM',['https://docs.opencv.org/4.2.0/d7/d8e/classcv_1_1stereo_1_1StereoBinaryBM.html',1,'cv::stereo']]],
  ['stereobinarysgbm_334',['StereoBinarySGBM',['https://docs.opencv.org/4.2.0/d1/d9f/classcv_1_1stereo_1_1StereoBinarySGBM.html',1,'cv::stereo']]],
  ['stereobm_335',['StereoBM',['https://docs.opencv.org/4.2.0/db/d8a/classcv_1_1cuda_1_1StereoBM.html',1,'cv::cuda::StereoBM'],['https://docs.opencv.org/4.2.0/d9/dba/classcv_1_1StereoBM.html',1,'cv::StereoBM']]],
  ['stereoconstantspacebp_336',['StereoConstantSpaceBP',['https://docs.opencv.org/4.2.0/d7/d09/classcv_1_1cuda_1_1StereoConstantSpaceBP.html',1,'cv::cuda']]],
  ['stereographicprojector_337',['StereographicProjector',['https://docs.opencv.org/4.2.0/d0/ddf/structcv_1_1detail_1_1StereographicProjector.html',1,'cv::detail']]],
  ['stereographicwarper_338',['StereographicWarper',['https://docs.opencv.org/4.2.0/d1/d3d/classcv_1_1detail_1_1StereographicWarper.html',1,'cv::detail::StereographicWarper'],['https://docs.opencv.org/4.2.0/d2/d5e/classcv_1_1StereographicWarper.html',1,'cv::StereographicWarper']]],
  ['stereomatcher_339',['StereoMatcher',['https://docs.opencv.org/4.2.0/d9/d07/classcv_1_1stereo_1_1StereoMatcher.html',1,'cv::stereo::StereoMatcher'],['https://docs.opencv.org/4.2.0/d2/d6e/classcv_1_1StereoMatcher.html',1,'cv::StereoMatcher']]],
  ['stereosgbm_340',['StereoSGBM',['https://docs.opencv.org/4.2.0/d2/d85/classcv_1_1StereoSGBM.html',1,'cv']]],
  ['stitcher_341',['Stitcher',['https://docs.opencv.org/4.2.0/d2/d8d/classcv_1_1Stitcher.html',1,'cv']]],
  ['storagepolicycommon_342',['StoragePolicyCommon',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1detail_1_1StoragePolicyCommon.html',1,'rclcpp::wait_set_policies::detail']]],
  ['storagepolicycommon_3c_20false_20_3e_343',['StoragePolicyCommon&lt; false &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1detail_1_1StoragePolicyCommon.html',1,'']]],
  ['storagepolicycommon_3c_20true_20_3e_344',['StoragePolicyCommon&lt; true &gt;',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1detail_1_1StoragePolicyCommon.html',1,'']]],
  ['stored_5fdata_345',['stored_data',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11531.html',1,'__gnu_pbds::detail']]],
  ['stored_5fdata_3c_20_5ftv_2c_20null_5ftype_20_3e_346',['stored_data&lt; _Tv, null_type &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11535.html',1,'__gnu_pbds::detail']]],
  ['stored_5fhash_347',['stored_hash',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11527.html',1,'__gnu_pbds::detail']]],
  ['stored_5fvalue_348',['stored_value',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11523.html',1,'__gnu_pbds::detail']]],
  ['stream_349',['Stream',['https://docs.opencv.org/4.2.0/d9/df3/classcv_1_1cuda_1_1Stream.html',1,'cv::cuda']]],
  ['streamaccessor_350',['StreamAccessor',['https://docs.opencv.org/4.2.0/d6/df1/structcv_1_1cuda_1_1StreamAccessor.html',1,'cv::cuda']]],
  ['stride_351',['Stride',['https://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e_352',['Stride&lt; 0, Value &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'']]],
  ['stride_3c_20stridetype_3a_3aouterstrideatcompiletime_2c_20stridetype_3a_3ainnerstrideatcompiletime_20_3e_353',['Stride&lt; StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'']]],
  ['stride_3c_20value_2c_200_20_3e_354',['Stride&lt; Value, 0 &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'']]],
  ['string_5ftag_355',['string_tag',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11215.html',1,'__gnu_pbds']]],
  ['strongclassifierdirectselection_356',['StrongClassifierDirectSelection',['https://docs.opencv.org/4.2.0/d4/d1e/classcv_1_1StrongClassifierDirectSelection.html',1,'cv']]],
  ['structurededgedetection_357',['StructuredEdgeDetection',['https://docs.opencv.org/4.2.0/d8/d54/classcv_1_1ximgproc_1_1StructuredEdgeDetection.html',1,'cv::ximgproc']]],
  ['structuredlightpattern_358',['StructuredLightPattern',['https://docs.opencv.org/4.2.0/d9/dbb/classcv_1_1structured__light_1_1StructuredLightPattern.html',1,'cv::structured_light']]],
  ['student_5ft_5fdistribution_359',['student_t_distribution',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06419.html',1,'std']]],
  ['sub_5fmatch_360',['sub_match',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06767.html',1,'std']]],
  ['sub_5fmatch_3c_20_5fbi_5fiter_20_3e_361',['sub_match&lt; _Bi_iter &gt;',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06767.html',1,'']]],
  ['subdiv2d_362',['Subdiv2D',['https://docs.opencv.org/4.2.0/df/dbf/classcv_1_1Subdiv2D.html',1,'cv']]],
  ['subscription_363',['Subscription',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1Subscription.html',1,'rclcpp']]],
  ['subscriptionbase_364',['SubscriptionBase',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SubscriptionBase.html',1,'rclcpp']]],
  ['subscriptionentry_365',['SubscriptionEntry',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1DynamicStorage_1_1SubscriptionEntry.html',1,'rclcpp::wait_set_policies::DynamicStorage::SubscriptionEntry'],['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1StaticStorage_1_1SubscriptionEntry.html',1,'rclcpp::wait_set_policies::StaticStorage&lt; NumberOfSubscriptions, NumberOfGuardCondtions, NumberOfTimers, NumberOfClients, NumberOfServices, NumberOfWaitables &gt;::SubscriptionEntry']]],
  ['subscriptioneventcallbacks_366',['SubscriptionEventCallbacks',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1SubscriptionEventCallbacks.html',1,'rclcpp']]],
  ['subscriptionfactory_367',['SubscriptionFactory',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1SubscriptionFactory.html',1,'rclcpp']]],
  ['subscriptionintraprocess_368',['SubscriptionIntraProcess',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1experimental_1_1SubscriptionIntraProcess.html',1,'rclcpp::experimental']]],
  ['subscriptionintraprocessbase_369',['SubscriptionIntraProcessBase',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1experimental_1_1SubscriptionIntraProcessBase.html',1,'rclcpp::experimental']]],
  ['subscriptionoptionsbase_370',['SubscriptionOptionsBase',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1SubscriptionOptionsBase.html',1,'rclcpp']]],
  ['subscriptionoptionswithallocator_371',['SubscriptionOptionsWithAllocator',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1SubscriptionOptionsWithAllocator.html',1,'rclcpp']]],
  ['subscriptionoptionswithallocator_3c_20std_3a_3aallocator_3c_20void_20_3e_20_3e_372',['SubscriptionOptionsWithAllocator&lt; std::allocator&lt; void &gt; &gt;',['https://docs.ros2.org/foxy/api/rclcpp/structrclcpp_1_1SubscriptionOptionsWithAllocator.html',1,'']]],
  ['subscriptiontopicstatistics_373',['SubscriptionTopicStatistics',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1topic__statistics_1_1SubscriptionTopicStatistics.html',1,'rclcpp::topic_statistics']]],
  ['subscriptionwaitsetmask_374',['SubscriptionWaitSetMask',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SubscriptionWaitSetMask.html',1,'rclcpp']]],
  ['subtract_5fwith_5fcarry_5fengine_375',['subtract_with_carry_engine',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a06339.html',1,'std']]],
  ['subtractive_5frng_376',['subtractive_rng',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a09219.html',1,'__gnu_cxx']]],
  ['sum_377',['Sum',['https://docs.opencv.org/4.2.0/d8/d60/structcv_1_1cudev_1_1Sum.html',1,'cv::cudev']]],
  ['sumexprbody_378',['SumExprBody',['https://docs.opencv.org/4.2.0/dd/d33/structcv_1_1cudev_1_1SumExprBody.html',1,'cv::cudev']]],
  ['superilu_379',['SuperILU',['https://eigen.tuxfamily.org/dox/classEigen_1_1SuperILU.html',1,'Eigen']]],
  ['superlu_380',['SuperLU',['https://eigen.tuxfamily.org/dox/classEigen_1_1SuperLU.html',1,'Eigen']]],
  ['superlubase_381',['SuperLUBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superilu_3c_20_5fmatrixtype_20_3e_20_3e_382',['SuperLUBase&lt; _MatrixType, SuperILU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e_383',['SuperLUBase&lt; _MatrixType, SuperLU&lt; _MatrixType &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'']]],
  ['superpixellsc_384',['SuperpixelLSC',['https://docs.opencv.org/4.2.0/d5/da0/classcv_1_1ximgproc_1_1SuperpixelLSC.html',1,'cv::ximgproc']]],
  ['superpixelseeds_385',['SuperpixelSEEDS',['https://docs.opencv.org/4.2.0/df/d81/classcv_1_1ximgproc_1_1SuperpixelSEEDS.html',1,'cv::ximgproc']]],
  ['superpixelslic_386',['SuperpixelSLIC',['https://docs.opencv.org/4.2.0/d3/da9/classcv_1_1ximgproc_1_1SuperpixelSLIC.html',1,'cv::ximgproc']]],
  ['superresolution_387',['SuperResolution',['https://docs.opencv.org/4.2.0/d9/dd6/classcv_1_1superres_1_1SuperResolution.html',1,'cv::superres']]],
  ['surf_388',['SURF',['https://docs.opencv.org/4.2.0/d5/df7/classcv_1_1xfeatures2d_1_1SURF.html',1,'cv::xfeatures2d']]],
  ['surf_5fcuda_389',['SURF_CUDA',['https://docs.opencv.org/4.2.0/db/d06/classcv_1_1cuda_1_1SURF__CUDA.html',1,'cv::cuda']]],
  ['svd_390',['SVD',['https://docs.opencv.org/4.2.0/df/df7/classcv_1_1SVD.html',1,'cv']]],
  ['svdbase_391',['SVDBase',['https://eigen.tuxfamily.org/dox/classEigen_1_1SVDBase.html',1,'Eigen']]],
  ['svdbase_3c_20jacobisvd_3c_20_5fmatrixtype_2c_20qrpreconditioner_20_3e_20_3e_392',['SVDBase&lt; JacobiSVD&lt; _MatrixType, QRPreconditioner &gt; &gt;',['https://eigen.tuxfamily.org/dox/classEigen_1_1SVDBase.html',1,'']]],
  ['svm_393',['SVM',['https://docs.opencv.org/4.2.0/d1/d2d/classcv_1_1ml_1_1SVM.html',1,'cv::ml']]],
  ['svmsgd_394',['SVMSGD',['https://docs.opencv.org/4.2.0/de/d54/classcv_1_1ml_1_1SVMSGD.html',1,'cv::ml']]],
  ['swishlayer_395',['SwishLayer',['https://docs.opencv.org/4.2.0/d9/d63/classcv_1_1dnn_1_1SwishLayer.html',1,'cv::dnn']]],
  ['symbolexpr_396',['SymbolExpr',['https://eigen.tuxfamily.org/dox/classEigen_1_1symbolic_1_1SymbolExpr.html',1,'Eigen::symbolic']]],
  ['symbolvalue_397',['SymbolValue',['https://eigen.tuxfamily.org/dox/classEigen_1_1symbolic_1_1SymbolValue.html',1,'Eigen::symbolic']]],
  ['symetriccensus_398',['SymetricCensus',['https://docs.opencv.org/4.2.0/dd/d24/classcv_1_1stereo_1_1SymetricCensus.html',1,'cv::stereo']]],
  ['synchronizationpolicycommon_399',['SynchronizationPolicyCommon',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1wait__set__policies_1_1detail_1_1SynchronizationPolicyCommon.html',1,'rclcpp::wait_set_policies::detail']]],
  ['syncparametersclient_400',['SyncParametersClient',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SyncParametersClient.html',1,'rclcpp']]],
  ['synth_5faccess_5ftraits_401',['synth_access_traits',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a11955.html',1,'__gnu_pbds::detail']]],
  ['syntheticlidar_402',['SyntheticLidar',['../classSyntheticLidar.html',1,'']]],
  ['syntheticsequencegenerator_403',['SyntheticSequenceGenerator',['https://docs.opencv.org/4.2.0/d1/dda/classcv_1_1bgsegm_1_1SyntheticSequenceGenerator.html',1,'cv::bgsegm']]],
  ['system_5fclock_404',['system_clock',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01911.html',1,'std::chrono::_V2']]],
  ['system_5ferror_405',['system_error',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a02855.html',1,'std']]],
  ['systemdefaultsqos_406',['SystemDefaultsQoS',['https://docs.ros2.org/foxy/api/rclcpp/classrclcpp_1_1SystemDefaultsQoS.html',1,'rclcpp']]]
];
