var searchData=
[
  ['va_5fintel_2ehpp_0',['va_intel.hpp',['https://docs.opencv.org/4.2.0/d5/d8c/va__intel_8hpp.html',1,'']]],
  ['valarray_1',['valarray',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00179.html',1,'']]],
  ['valarray_5fafter_2eh_2',['valarray_after.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00638.html',1,'']]],
  ['valarray_5farray_2eh_3',['valarray_array.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00641.html',1,'']]],
  ['valarray_5farray_2etcc_4',['valarray_array.tcc',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00644.html',1,'']]],
  ['valarray_5fbefore_2eh_5',['valarray_before.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00647.html',1,'']]],
  ['variant_2ehpp_6',['variant.hpp',['https://docs.opencv.org/4.2.0/d9/d7a/variant_8hpp.html',1,'']]],
  ['vec_5fdistance_2ehpp_7',['vec_distance.hpp',['https://docs.opencv.org/4.2.0/d7/d23/modules_2core_2include_2opencv2_2core_2cuda_2vec__distance_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d5/dbb/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2vec__distance_8hpp.html',1,'(Global Namespace)']]],
  ['vec_5fmath_2ehpp_8',['vec_math.hpp',['https://docs.opencv.org/4.2.0/d4/da9/modules_2core_2include_2opencv2_2core_2cuda_2vec__math_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/dc/d1b/contrib_2modules_2cudev_2include_2opencv2_2cudev_2util_2vec__math_8hpp.html',1,'(Global Namespace)']]],
  ['vec_5ftraits_2ehpp_9',['vec_traits.hpp',['https://docs.opencv.org/4.2.0/de/d6f/modules_2core_2include_2opencv2_2core_2cuda_2vec__traits_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d1/d0d/contrib_2modules_2cudev_2include_2opencv2_2cudev_2util_2vec__traits_8hpp.html',1,'(Global Namespace)']]],
  ['vector_10',['vector',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00182.html',1,'']]],
  ['vector_2etcc_11',['vector.tcc',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00650.html',1,'']]],
  ['version_2ehpp_12',['version.hpp',['https://docs.opencv.org/4.2.0/da/d1a/dnn_2include_2opencv2_2dnn_2version_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/da/dd7/core_2include_2opencv2_2core_2version_8hpp.html',1,'(Global Namespace)']]],
  ['video_2ehpp_13',['video.hpp',['https://docs.opencv.org/4.2.0/d5/d71/video_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/da/dbe/video_2video_8hpp.html',1,'(Global Namespace)']]],
  ['video_5finput_5fpsnr_5fssim_2emarkdown_14',['video_input_psnr_ssim.markdown',['https://docs.opencv.org/4.2.0/da/dcb/video__input__psnr__ssim_8markdown.html',1,'']]],
  ['video_5fprocessing_2emarkdown_15',['video_processing.markdown',['https://docs.opencv.org/4.2.0/d9/d45/video__processing_8markdown.html',1,'']]],
  ['video_5fwrite_2emarkdown_16',['video_write.markdown',['https://docs.opencv.org/4.2.0/d1/d98/video__write_8markdown.html',1,'']]],
  ['videoio_2ehpp_17',['videoio.hpp',['https://docs.opencv.org/4.2.0/d8/d8e/videoio_2videoio_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/dc/d3d/videoio_8hpp.html',1,'(Global Namespace)']]],
  ['videoio_5foverview_2emarkdown_18',['videoio_overview.markdown',['https://docs.opencv.org/4.2.0/dd/de3/videoio__overview_8markdown.html',1,'']]],
  ['videostab_2ehpp_19',['videostab.hpp',['https://docs.opencv.org/4.2.0/dd/d91/videostab_8hpp.html',1,'']]],
  ['visual_5fdebugging_5fintroduction_2emarkdown_20',['visual_debugging_introduction.markdown',['https://docs.opencv.org/4.2.0/db/de0/visual__debugging__introduction_8markdown.html',1,'']]],
  ['viz_2ehpp_21',['viz.hpp',['https://docs.opencv.org/4.2.0/d0/d7e/viz_8hpp.html',1,'']]],
  ['viz3d_2ehpp_22',['viz3d.hpp',['https://docs.opencv.org/4.2.0/de/d82/viz3d_8hpp.html',1,'']]],
  ['vizcore_2ehpp_23',['vizcore.hpp',['https://docs.opencv.org/4.2.0/d2/d4b/vizcore_8hpp.html',1,'']]],
  ['vstring_2eh_24',['vstring.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01103.html',1,'']]],
  ['vstring_2etcc_25',['vstring.tcc',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01106.html',1,'']]],
  ['vstring_5ffwd_2eh_26',['vstring_fwd.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01109.html',1,'']]],
  ['vstring_5futil_2eh_27',['vstring_util.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01112.html',1,'']]],
  ['vsx_5futils_2ehpp_28',['vsx_utils.hpp',['https://docs.opencv.org/4.2.0/db/d68/vsx__utils_8hpp.html',1,'']]]
];
