var searchData=
[
  ['hal_2ehpp_0',['hal.hpp',['https://docs.opencv.org/4.2.0/d4/d44/imgproc_2include_2opencv2_2imgproc_2hal_2hal_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/de/d0c/core_2include_2opencv2_2core_2hal_2hal_8hpp.html',1,'(Global Namespace)']]],
  ['hal_5freplacement_2ehpp_1',['hal_replacement.hpp',['https://docs.opencv.org/4.2.0/d2/dd9/features2d_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/df/d91/imgproc_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/db/ddd/core_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)']]],
  ['harris_5fdetector_2emarkdown_2',['harris_detector.markdown',['https://docs.opencv.org/4.2.0/db/d48/harris__detector_8markdown.html',1,'']]],
  ['hash_5fbytes_2eh_3',['hash_bytes.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00371.html',1,'']]],
  ['hash_5feq_5ffn_2ehpp_4',['hash_eq_fn.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01298.html',1,'']]],
  ['hash_5fexponential_5fsize_5fpolicy_5fimp_2ehpp_5',['hash_exponential_size_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01403.html',1,'']]],
  ['hash_5ffun_2eh_6',['hash_fun.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00737.html',1,'']]],
  ['hash_5fload_5fcheck_5fresize_5ftrigger_5fimp_2ehpp_7',['hash_load_check_resize_trigger_imp.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01406.html',1,'']]],
  ['hash_5fload_5fcheck_5fresize_5ftrigger_5fsize_5fbase_2ehpp_8',['hash_load_check_resize_trigger_size_base.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01409.html',1,'']]],
  ['hash_5fmap_9',['hash_map',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00740.html',1,'']]],
  ['hash_5fpolicy_2ehpp_10',['hash_policy.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01121.html',1,'']]],
  ['hash_5fprime_5fsize_5fpolicy_5fimp_2ehpp_11',['hash_prime_size_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01412.html',1,'']]],
  ['hash_5fset_12',['hash_set',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00743.html',1,'']]],
  ['hash_5fstandard_5fresize_5fpolicy_5fimp_2ehpp_13',['hash_standard_resize_policy_imp.hpp',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01415.html',1,'']]],
  ['hashtable_5fpolicy_2eh_14',['hashtable_policy.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00377.html',1,'']]],
  ['hdf_2ehpp_15',['hdf.hpp',['https://docs.opencv.org/4.2.0/d7/d55/hdf_8hpp.html',1,'']]],
  ['hdf5_2eh_16',['hdf5.h',['https://docs.opencv.org/4.2.0/db/d87/hdf5_8h.html',1,'']]],
  ['hdf5_2ehpp_17',['hdf5.hpp',['https://docs.opencv.org/4.2.0/de/d24/hdf5_8hpp.html',1,'']]],
  ['hdr_5fimaging_2emarkdown_18',['hdr_imaging.markdown',['https://docs.opencv.org/4.2.0/d9/d87/hdr__imaging_8markdown.html',1,'']]],
  ['heap_2eh_19',['heap.h',['https://docs.opencv.org/4.2.0/da/ddb/heap_8h.html',1,'']]],
  ['hello_2emarkdown_20',['hello.markdown',['https://docs.opencv.org/4.2.0/da/da0/hello_8markdown.html',1,'']]],
  ['helper_5ffunctions_2eh_21',['helper_functions.h',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a00761.html',1,'']]],
  ['hfs_2ehpp_22',['hfs.hpp',['https://docs.opencv.org/4.2.0/de/d29/hfs_8hpp.html',1,'']]],
  ['hierarchical_5fclustering_5findex_2eh_23',['hierarchical_clustering_index.h',['https://docs.opencv.org/4.2.0/de/d1d/hierarchical__clustering__index_8h.html',1,'']]],
  ['highgui_2ehpp_24',['highgui.hpp',['https://docs.opencv.org/4.2.0/d4/dd5/highgui_8hpp.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d0/dce/highgui_2highgui_8hpp.html',1,'(Global Namespace)']]],
  ['highgui_5fwinrt_2ehpp_25',['highgui_winrt.hpp',['https://docs.opencv.org/4.2.0/d9/d22/highgui__winrt_8hpp.html',1,'']]],
  ['hist_5fcost_2ehpp_26',['hist_cost.hpp',['https://docs.opencv.org/4.2.0/df/d08/hist__cost_8hpp.html',1,'']]],
  ['histo3d_2emarkdown_27',['histo3D.markdown',['https://docs.opencv.org/4.2.0/df/dd7/histo3D_8markdown.html',1,'']]],
  ['histogram_2ehpp_28',['histogram.hpp',['https://docs.opencv.org/4.2.0/d5/d6e/histogram_8hpp.html',1,'']]],
  ['histogram_5fcalculation_2emarkdown_29',['histogram_calculation.markdown',['https://docs.opencv.org/4.2.0/d2/d3a/histogram__calculation_8markdown.html',1,'']]],
  ['histogram_5fcomparison_2emarkdown_30',['histogram_comparison.markdown',['https://docs.opencv.org/4.2.0/de/d12/histogram__comparison_8markdown.html',1,'']]],
  ['histogram_5fequalization_2emarkdown_31',['histogram_equalization.markdown',['https://docs.opencv.org/4.2.0/db/de8/histogram__equalization_8markdown.html',1,'']]],
  ['histogramphaseunwrapping_2ehpp_32',['histogramphaseunwrapping.hpp',['https://docs.opencv.org/4.2.0/df/dce/histogramphaseunwrapping_8hpp.html',1,'']]],
  ['hitormiss_2emarkdown_33',['hitOrMiss.markdown',['https://docs.opencv.org/4.2.0/d2/dbf/hitOrMiss_8markdown.html',1,'']]],
  ['homography_2emarkdown_34',['homography.markdown',['https://docs.opencv.org/4.2.0/d2/dc8/homography_8markdown.html',1,'']]],
  ['hough_5fcircle_2emarkdown_35',['hough_circle.markdown',['https://docs.opencv.org/4.2.0/d4/d67/hough__circle_8markdown.html',1,'']]],
  ['hough_5flines_2emarkdown_36',['hough_lines.markdown',['https://docs.opencv.org/4.2.0/da/d5a/hough__lines_8markdown.html',1,'']]],
  ['how_5fto_5fcreate_5fgroups_2emarkdown_37',['how_to_create_groups.markdown',['https://docs.opencv.org/4.2.0/d7/d7b/how__to__create__groups_8markdown.html',1,'']]],
  ['how_5fto_5fscan_5fimages_2emarkdown_38',['how_to_scan_images.markdown',['https://docs.opencv.org/4.2.0/d5/d91/how__to__scan__images_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5f_2emarkdown_39',['how_to_use_OpenCV_parallel_for_.markdown',['https://docs.opencv.org/4.2.0/d5/d45/how__to__use__OpenCV__parallel__for___8markdown.html',1,'']]],
  ['hpe_5fhumaneva_2ehpp_40',['hpe_humaneva.hpp',['https://docs.opencv.org/4.2.0/d8/da7/hpe__humaneva_8hpp.html',1,'']]],
  ['hpe_5fparse_2ehpp_41',['hpe_parse.hpp',['https://docs.opencv.org/4.2.0/da/da9/hpe__parse_8hpp.html',1,'']]],
  ['hull_2emarkdown_42',['hull.markdown',['https://docs.opencv.org/4.2.0/d0/dbd/hull_8markdown.html',1,'']]]
];
