var searchData=
[
  ['backends_0',['backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'Additional flags for video I/O API backends'],['https://docs.opencv.org/4.2.0/dc/d1c/group__gapi__std__backends.html',1,'G-API Standard Backends']]],
  ['backends_20registry_1',['Query I/O API backends registry',['https://docs.opencv.org/4.2.0/de/db1/group__videoio__registry.html',1,'']]],
  ['background_20foreground_20segmentation_20methods_2',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['background_20segmentation_3',['Background Segmentation',['https://docs.opencv.org/4.2.0/d6/d17/group__cudabgsegm.html',1,'']]],
  ['base_20and_20implementation_20classes_4',['base and implementation classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01497.html',1,'Base and Implementation Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01501.html',1,'Base and Implementation Classes']]],
  ['base_20and_20policy_20classes_5',['base and policy classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01529.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01535.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01531.html',1,'Base and Policy Classes']]],
  ['based_6',['based',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01530.html',1,'Branch-Based'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01528.html',1,'Hash-Based'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01534.html',1,'Heap-Based'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01532.html',1,'List-Based']]],
  ['based_20data_20structures_7',['Policy-Based Data Structures',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01536.html',1,'']]],
  ['based_20models_8',['Deformable Part-based Models',['https://docs.opencv.org/4.2.0/d9/d12/group__dpm.html',1,'']]],
  ['based_20on_20fuzzy_20mathematics_9',['Image processing based on fuzzy mathematics',['https://docs.opencv.org/4.2.0/df/d5b/group__fuzzy.html',1,'']]],
  ['basic_20structures_10',['Basic structures',['https://docs.opencv.org/4.2.0/dc/d84/group__core__basic.html',1,'']]],
  ['benchmark_20of_20dense_20decompositions_11',['Benchmark of dense decompositions',['https://eigen.tuxfamily.org/dox/group__DenseDecompositionBenchmark.html',1,'']]],
  ['bernoulli_20distributions_12',['Bernoulli Distributions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01545.html',1,'']]],
  ['binary_20descriptors_20for_20lines_20extracted_20from_20an_20image_13',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['binary_20morphology_20on_20run_20length_20encoded_20image_14',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['binary_20search_15',['Binary Search',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01493.html',1,'']]],
  ['binder_20classes_16',['Binder Classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01517.html',1,'']]],
  ['biologically_20inspired_20vision_20models_20and_20derivated_20tools_17',['Biologically inspired vision models and derivated tools',['https://docs.opencv.org/4.2.0/dd/deb/group__bioinspired.html',1,'']]],
  ['bitset_18',['Dynamic Bitset.',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01519.html',1,'']]],
  ['bitwise_20logical_20operations_19',['Bitwise logical operations',['https://docs.opencv.org/4.2.0/d2/d18/group__core__hal__interface__logical.html',1,'']]],
  ['blenders_20',['Image Blenders',['https://docs.opencv.org/4.2.0/d9/d46/group__stitching__blend.html',1,'']]],
  ['block_20operations_21',['Block operations',['https://eigen.tuxfamily.org/dox/group__TutorialBlockOperations.html',1,'']]],
  ['boolean_20operations_20classes_22',['Boolean Operations Classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01508.html',1,'']]],
  ['box_20typedefs_23',['Global aligned box typedefs',['https://eigen.tuxfamily.org/dox/group__alignedboxtypedefs.html',1,'']]],
  ['branch_20based_24',['Branch-Based',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01530.html',1,'']]],
  ['brings_20implementations_20of_20different_20image_20hashing_20algorithms_25',['The module brings implementations of different image hashing algorithms.',['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'']]],
  ['broadcasting_26',['Reductions, visitors and broadcasting',['https://eigen.tuxfamily.org/dox/group__TutorialReductionsVisitorsBroadcasting.html',1,'']]],
  ['buffers_3a_20the_20map_20class_27',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['by_20value_20to_20functions_28',['Passing Eigen objects by value to functions',['https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html',1,'']]]
];
