var searchData=
[
  ['random_20number_20distributions_0',['Random Number Distributions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01542.html',1,'']]],
  ['random_20number_20generation_1',['Random Number Generation',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01500.html',1,'']]],
  ['random_20number_20generators_2',['Random Number Generators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01541.html',1,'']]],
  ['random_20number_20utilities_3',['Random Number Utilities',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01547.html',1,'']]],
  ['rational_20arithmetic_4',['Rational Arithmetic',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01483.html',1,'']]],
  ['raw_20buffers_3a_20the_20map_20class_5',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['reading_20and_20writing_6',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['reciprocial_7',['Element-wise reciprocial',['https://docs.opencv.org/4.2.0/d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['recognition_8',['recognition',['https://docs.opencv.org/4.2.0/d4/d8b/group__datasets__ar.html',1,'Action Recognition'],['https://docs.opencv.org/4.2.0/de/d93/group__datasets__fr.html',1,'Face Recognition'],['https://docs.opencv.org/4.2.0/d9/db7/group__datasets__gr.html',1,'Gesture Recognition'],['https://docs.opencv.org/4.2.0/dc/d24/group__datasets__or.html',1,'Object Recognition'],['https://docs.opencv.org/4.2.0/d4/d61/group__text.html',1,'Scene Text Detection and Recognition'],['https://docs.opencv.org/4.2.0/d8/df2/group__text__recognize.html',1,'Scene Text Recognition'],['https://docs.opencv.org/4.2.0/db/d7b/group__datasets__tr.html',1,'Text Recognition']]],
  ['recognition_20and_20pose_20estimation_20api_9',['3D object recognition and pose estimation API',['https://docs.opencv.org/4.2.0/d9/d02/group__cnn__3dobj.html',1,'']]],
  ['reconstruction_10',['reconstruction',['https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html',1,'Camera Calibration and 3D Reconstruction'],['https://docs.opencv.org/4.2.0/d3/ddc/group__ccalib.html',1,'Custom Calibration Pattern for 3D reconstruction'],['https://docs.opencv.org/4.2.0/da/db5/group__reconstruction.html',1,'Reconstruction']]],
  ['reductions_11',['Matrix Reductions',['https://docs.opencv.org/4.2.0/d5/de6/group__cudaarithm__reduce.html',1,'']]],
  ['reductions_20visitors_20and_20broadcasting_12',['Reductions, visitors and broadcasting',['https://eigen.tuxfamily.org/dox/group__TutorialReductionsVisitorsBroadcasting.html',1,'']]],
  ['reference_13',['reference',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__Reference.html',1,'Reference'],['https://eigen.tuxfamily.org/dox/group__Geometry__Reference.html',1,'Reference'],['https://eigen.tuxfamily.org/dox/group__Sparse__Reference.html',1,'Reference'],['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__Reference.html',1,'Reference']]],
  ['reference_20guide_14',['Quick reference guide',['https://eigen.tuxfamily.org/dox/group__QuickRefPage.html',1,'']]],
  ['reference_20guide_20for_20sparse_20matrices_15',['Quick reference guide for sparse matrices',['https://eigen.tuxfamily.org/dox/group__SparseQuickRefPage.html',1,'']]],
  ['registration_16',['registration',['https://docs.opencv.org/4.2.0/db/d61/group__reg.html',1,'Image Registration'],['https://docs.opencv.org/4.2.0/dc/def/group__datasets__ir.html',1,'Image Registration'],['https://docs.opencv.org/4.2.0/df/dc1/group__dnnLayerFactory.html',1,'Utilities for New Layers Registration']]],
  ['registry_17',['Query I/O API backends registry',['https://docs.opencv.org/4.2.0/de/db1/group__videoio__registry.html',1,'']]],
  ['regular_20expressions_18',['Regular Expressions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01502.html',1,'']]],
  ['rendering_19',['Non-Photorealistic Rendering',['https://docs.opencv.org/4.2.0/df/dac/group__photo__render.html',1,'']]],
  ['reshape_20',['Reshape',['https://eigen.tuxfamily.org/dox/group__TutorialReshape.html',1,'']]],
  ['resolution_21',['resolution',['https://docs.opencv.org/4.2.0/d9/de0/group__dnn__superres.html',1,'DNN used for super resolution'],['https://docs.opencv.org/4.2.0/d7/d0a/group__superres.html',1,'Super Resolution'],['https://docs.opencv.org/4.2.0/d1/d5b/group__datasets__sr.html',1,'Super Resolution']]],
  ['rgb_20depth_20processing_22',['RGB-Depth Processing',['https://docs.opencv.org/4.2.0/d2/d3a/group__rgbd.html',1,'']]],
  ['robust_20estimation_23',['Robust Estimation',['https://docs.opencv.org/4.2.0/db/d3a/group__robust.html',1,'']]],
  ['root_20calculation_24',['root calculation',['https://docs.opencv.org/4.2.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'Inverse square root calculation'],['https://docs.opencv.org/4.2.0/d5/dc3/group__core__hal__interface__sqrt.html',1,'Square root calculation']]],
  ['rotation_20estimation_25',['Rotation Estimation',['https://docs.opencv.org/4.2.0/d7/d74/group__stitching__rotation.html',1,'']]],
  ['routines_26',['Hierarchical Data Format I/O routines',['https://docs.opencv.org/4.2.0/db/d77/group__hdf.html',1,'']]],
  ['run_20length_20encoded_20image_27',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]]
];
