var searchData=
[
  ['layer_0',['Layer',['https://docs.opencv.org/4.2.0/de/d85/group__core__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/d3/df3/group__imgproc__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/d8/d45/group__feature2d__hal.html',1,'Hardware Acceleration Layer']]],
  ['layer_1',['Device layer',['https://docs.opencv.org/4.2.0/df/dfc/group__cudev.html',1,'']]],
  ['layers_2',['Partial List of Implemented Layers',['https://docs.opencv.org/4.2.0/d6/d87/group__dnnLayerList.html',1,'']]],
  ['layers_20registration_3',['Utilities for New Layers Registration',['https://docs.opencv.org/4.2.0/df/dc1/group__dnnLayerFactory.html',1,'']]],
  ['learning_4',['Machine Learning',['https://docs.opencv.org/4.2.0/dd/ded/group__ml.html',1,'']]],
  ['least_20squares_20systems_5',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['legacy_20support_6',['Legacy support',['https://docs.opencv.org/4.2.0/d5/dc3/group__cudalegacy.html',1,'']]],
  ['length_20encoded_20image_7',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['level_20api_20for_20external_20libraries_20plugins_8',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['level_20gui_9',['High-level GUI',['https://docs.opencv.org/4.2.0/d7/dfc/group__highgui.html',1,'']]],
  ['libraries_20plugins_10',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['light_20api_11',['Structured Light API',['https://docs.opencv.org/4.2.0/d1/d90/group__structured__light.html',1,'']]],
  ['line_20detector_12',['Fast line detector',['https://docs.opencv.org/4.2.0/df/ded/group__ximgproc__fast__line__detector.html',1,'']]],
  ['linear_20algebra_13',['Sparse linear algebra',['https://eigen.tuxfamily.org/dox/group__Sparse__chapter.html',1,'']]],
  ['linear_20algebra_20and_20decompositions_14',['Linear algebra and decompositions',['https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html',1,'']]],
  ['linear_20least_20squares_20systems_15',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['linear_20problems_20and_20decompositions_16',['Dense linear problems and decompositions',['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__chapter.html',1,'']]],
  ['linear_20systems_17',['Solving Sparse Linear Systems',['https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html',1,'']]],
  ['lines_20extracted_20from_20an_20image_18',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['list_20based_19',['List-Based',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01532.html',1,'']]],
  ['list_20of_20implemented_20layers_20',['Partial List of Implemented Layers',['https://docs.opencv.org/4.2.0/d6/d87/group__dnnLayerList.html',1,'']]],
  ['locales_21',['Locales',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01498.html',1,'']]],
  ['logarithm_20calculation_22',['Natural logarithm calculation',['https://docs.opencv.org/4.2.0/d2/de4/group__core__hal__interface__log.html',1,'']]],
  ['logging_20facilities_23',['Logging facilities',['https://docs.opencv.org/4.2.0/d3/dcb/group__core__logging.html',1,'']]],
  ['logical_20operations_24',['Bitwise logical operations',['https://docs.opencv.org/4.2.0/d2/d18/group__core__hal__interface__logical.html',1,'']]],
  ['low_20level_20api_20for_20external_20libraries_20plugins_25',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['lu_20matrix_20decomposition_26',['LU matrix decomposition',['https://docs.opencv.org/4.2.0/d5/d42/group__core__hal__interface__decomp__lu.html',1,'']]],
  ['lu_20module_27',['LU module',['https://eigen.tuxfamily.org/dox/group__LU__Module.html',1,'']]]
];
