var searchData=
[
  ['f0_20transform_20support_0',['Math with F0-transform support',['https://docs.opencv.org/4.2.0/d5/d8e/group__f0__math.html',1,'']]],
  ['f1_20transform_20support_1',['Math with F1-transform support',['https://docs.opencv.org/4.2.0/d6/df0/group__f1__math.html',1,'']]],
  ['face_20analysis_2',['Face Analysis',['https://docs.opencv.org/4.2.0/db/d7c/group__face.html',1,'']]],
  ['face_20recognition_3',['Face Recognition',['https://docs.opencv.org/4.2.0/de/d93/group__datasets__fr.html',1,'']]],
  ['facilities_4',['Logging facilities',['https://docs.opencv.org/4.2.0/d3/dcb/group__core__logging.html',1,'']]],
  ['fast_20edge_20detection_5',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['fast_20line_20detector_6',['Fast line detector',['https://docs.opencv.org/4.2.0/df/ded/group__ximgproc__fast__line__detector.html',1,'']]],
  ['fast_20marching_20method_7',['Fast Marching Method',['https://docs.opencv.org/4.2.0/db/d18/group__videostab__marching.html',1,'']]],
  ['feature_20detection_8',['feature detection',['https://docs.opencv.org/4.2.0/dc/d6d/group__cudaimgproc__feature.html',1,'Feature Detection'],['https://docs.opencv.org/4.2.0/dd/d1a/group__imgproc__feature.html',1,'Feature Detection']]],
  ['feature_20detection_20and_20description_9',['feature detection and description',['https://docs.opencv.org/4.2.0/d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description'],['https://docs.opencv.org/4.2.0/d5/d51/group__features2d__main.html',1,'Feature Detection and Description']]],
  ['feature_20selection_20for_20efficient_20image_20segmentation_10',['Hierarchical Feature Selection for Efficient Image Segmentation',['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'']]],
  ['features_20algorithms_11',['features algorithms',['https://docs.opencv.org/4.2.0/d7/d7a/group__xfeatures2d__experiment.html',1,'Experimental 2D Features Algorithms'],['https://docs.opencv.org/4.2.0/d2/dca/group__xfeatures2d__nonfree.html',1,'Non-free 2D Features Algorithms']]],
  ['features_20finding_20and_20images_20matching_12',['Features Finding and Images Matching',['https://docs.opencv.org/4.2.0/df/d8c/group__stitching__match.html',1,'']]],
  ['features_20framework_13',['features framework',['https://docs.opencv.org/4.2.0/da/d9b/group__features2d.html',1,'2D Features Framework'],['https://docs.opencv.org/4.2.0/d1/db4/group__xfeatures2d.html',1,'Extra 2D Features Framework']]],
  ['features_20matching_20algorithm_14',['Experimental 2D Features Matching Algorithm',['https://docs.opencv.org/4.2.0/db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['file_20reading_20and_20writing_15',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['filesystem_20ts_16',['Filesystem TS',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01521.html',1,'']]],
  ['filtering_17',['filtering',['https://docs.opencv.org/4.2.0/dc/d66/group__cudafilters.html',1,'Image Filtering'],['https://docs.opencv.org/4.2.0/d4/d86/group__imgproc__filter.html',1,'Image Filtering']]],
  ['filters_18',['filters',['https://docs.opencv.org/4.2.0/da/d17/group__ximgproc__filters.html',1,'Filters'],['https://docs.opencv.org/4.2.0/da/dc5/group__gapi__filters.html',1,'Graph API: Image filters']]],
  ['finding_20and_20images_20matching_19',['Features Finding and Images Matching',['https://docs.opencv.org/4.2.0/df/d8c/group__stitching__match.html',1,'']]],
  ['fisheye_20camera_20model_20',['Fisheye camera model',['https://docs.opencv.org/4.2.0/db/d58/group__calib3d__fisheye.html',1,'']]],
  ['fixed_20size_20vectorizable_20eigen_20objects_21',['Fixed-size vectorizable Eigen objects',['https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html',1,'']]],
  ['flags_22',['Flags',['https://eigen.tuxfamily.org/dox/group__flags.html',1,'']]],
  ['flags_20for_20video_20i_20o_23',['Flags for video I/O',['https://docs.opencv.org/4.2.0/d4/d15/group__videoio__flags__base.html',1,'']]],
  ['flags_20for_20video_20i_20o_20api_20backends_24',['Additional flags for video I/O API backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['floating_20point_20arithmetic_25',['Decimal Floating-Point Arithmetic',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01520.html',1,'']]],
  ['flow_26',['Optical Flow',['https://docs.opencv.org/4.2.0/d7/d3f/group__cudaoptflow.html',1,'']]],
  ['flow_20algorithms_27',['Optical Flow Algorithms',['https://docs.opencv.org/4.2.0/d2/d84/group__optflow.html',1,'']]],
  ['for_203d_20reconstruction_28',['Custom Calibration Pattern for 3D reconstruction',['https://docs.opencv.org/4.2.0/d3/ddc/group__ccalib.html',1,'']]],
  ['for_20efficient_20image_20segmentation_29',['Hierarchical Feature Selection for Efficient Image Segmentation',['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'']]],
  ['for_20external_20libraries_20plugins_30',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['for_20fast_20edge_20detection_31',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['for_20interactive_20visual_20debugging_20of_20computer_20vision_20programs_32',['GUI for Interactive Visual Debugging of Computer Vision Programs',['https://docs.opencv.org/4.2.0/df/dff/group__cvv.html',1,'']]],
  ['for_20lines_20extracted_20from_20an_20image_33',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['for_20mat_20data_34',['Plot function for Mat data',['https://docs.opencv.org/4.2.0/db/dfe/group__plot.html',1,'']]],
  ['for_20new_20layers_20registration_35',['Utilities for New Layers Registration',['https://docs.opencv.org/4.2.0/df/dc1/group__dnnLayerFactory.html',1,'']]],
  ['for_20object_20detection_36',['DNN used for object detection',['https://docs.opencv.org/4.2.0/d5/df6/group__dnn__objdetect.html',1,'']]],
  ['for_20opencv_20samples_37',['Utility functions for OpenCV samples',['https://docs.opencv.org/4.2.0/d6/dba/group__core__utils__samples.html',1,'']]],
  ['for_20pointers_20to_20functions_38',['Adaptors for pointers to functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01510.html',1,'']]],
  ['for_20pointers_20to_20members_39',['Adaptors for pointers to members',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01511.html',1,'']]],
  ['for_20sparse_20matrices_40',['Quick reference guide for sparse matrices',['https://eigen.tuxfamily.org/dox/group__SparseQuickRefPage.html',1,'']]],
  ['for_20super_20resolution_41',['DNN used for super resolution',['https://docs.opencv.org/4.2.0/d9/de0/group__dnn__superres.html',1,'']]],
  ['for_20video_20i_20o_42',['for video i o',['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__c.html',1,'C API for video I/O'],['https://docs.opencv.org/4.2.0/d4/d15/group__videoio__flags__base.html',1,'Flags for video I/O'],['https://docs.opencv.org/4.2.0/d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['for_20video_20i_20o_20api_20backends_43',['Additional flags for video I/O API backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['for_20working_20with_20different_20datasets_44',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['foreground_20segmentation_20methods_45',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['forests_20for_20fast_20edge_20detection_46',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['format_20i_20o_20routines_47',['Hierarchical Data Format I/O routines',['https://docs.opencv.org/4.2.0/db/d77/group__hdf.html',1,'']]],
  ['format_20version_205_48',['Hierarchical Data Format version 5',['https://docs.opencv.org/4.2.0/d6/dee/group__hdf5.html',1,'']]],
  ['fourier_20descriptors_49',['Fourier descriptors',['https://docs.opencv.org/4.2.0/dd/ddc/group__ximgproc__fourier.html',1,'']]],
  ['framework_50',['framework',['https://docs.opencv.org/4.2.0/da/d9b/group__features2d.html',1,'2D Features Framework'],['https://docs.opencv.org/4.2.0/d1/db4/group__xfeatures2d.html',1,'Extra 2D Features Framework'],['https://docs.opencv.org/4.2.0/d7/d0d/group__gapi.html',1,'G-API framework']]],
  ['framework_20for_20working_20with_20different_20datasets_51',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['free_202d_20features_20algorithms_52',['Non-free 2D Features Algorithms',['https://docs.opencv.org/4.2.0/d2/dca/group__xfeatures2d__nonfree.html',1,'']]],
  ['free_20solvers_53',['Matrix-free solvers',['https://eigen.tuxfamily.org/dox/group__MatrixfreeSolverExample.html',1,'']]],
  ['freetype_20harfbuzz_54',['Drawing UTF-8 strings with freetype/harfbuzz',['https://docs.opencv.org/4.2.0/d4/dfc/group__freetype.html',1,'']]],
  ['from_20an_20image_55',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['from_20motion_56',['Structure From Motion',['https://docs.opencv.org/4.2.0/d8/d8c/group__sfm.html',1,'']]],
  ['from_20one_20color_20space_20to_20another_57',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['function_20for_20mat_20data_58',['Plot function for Mat data',['https://docs.opencv.org/4.2.0/db/dfe/group__plot.html',1,'']]],
  ['function_20objects_59',['Function Objects',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01505.html',1,'']]],
  ['function_20of_20keypoints_20and_20matches_60',['Drawing Function of Keypoints and Matches',['https://docs.opencv.org/4.2.0/d4/d5d/group__features2d__draw.html',1,'']]],
  ['functionality_61',['functionality',['https://docs.opencv.org/4.2.0/d0/de1/group__core.html',1,'Core functionality'],['https://docs.opencv.org/4.2.0/df/d1f/group__gapi__core.html',1,'G-API Core functionality'],['https://docs.opencv.org/4.2.0/df/de4/group__gapi__draw.html',1,'G-API Drawing and composition functionality'],['https://docs.opencv.org/4.2.0/d2/d00/group__gapi__imgproc.html',1,'G-API Image processing functionality']]],
  ['functions_62',['functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01510.html',1,'Adaptors for pointers to functions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01523.html',1,'Array creation functions'],['https://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html',1,'Catalog of coefficient-wise math functions'],['https://docs.opencv.org/4.2.0/d6/d6e/group__imgproc__draw.html',1,'Drawing Functions'],['https://docs.opencv.org/4.2.0/d0/d43/group__gapi__draw__api.html',1,'Drawing operations and functions'],['https://docs.opencv.org/4.2.0/d5/df1/group__imgproc__hal__functions.html',1,'Functions'],['https://docs.opencv.org/4.2.0/d3/ddd/group__core__hal__functions.html',1,'Functions'],['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'Graph API: Image and channel composition functions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01503.html',1,'Mathematical Special Functions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01518.html',1,'Mathematical Special Functions'],['https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html',1,'Passing Eigen objects by value to functions'],['https://docs.opencv.org/4.2.0/dc/d46/group__highgui__qt.html',1,'Qt New Functions']]],
  ['functions_20and_20macros_63',['Utility and system functions and macros',['https://docs.opencv.org/4.2.0/db/de0/group__core__utils.html',1,'']]],
  ['functions_20for_20opencv_20samples_64',['Utility functions for OpenCV samples',['https://docs.opencv.org/4.2.0/d6/dba/group__core__utils__samples.html',1,'']]],
  ['fundamental_65',['Fundamental',['https://docs.opencv.org/4.2.0/d7/d15/group__fundamental.html',1,'']]],
  ['futures_66',['Futures',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01478.html',1,'']]],
  ['fuzzy_20image_20processing_67',['Fuzzy image processing',['https://docs.opencv.org/4.2.0/d1/dfc/group__f__image.html',1,'']]],
  ['fuzzy_20mathematics_68',['Image processing based on fuzzy mathematics',['https://docs.opencv.org/4.2.0/df/d5b/group__fuzzy.html',1,'']]]
];
