var searchData=
[
  ['c_0',['Connections with C++',['https://docs.opencv.org/4.2.0/d8/dd7/group__core__c__glue.html',1,'']]],
  ['c_20api_1',['c api',['https://docs.opencv.org/4.2.0/d3/d12/group__video__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d3/d40/group__photo__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d0/d28/group__highgui__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d9/d31/group__objdetect__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d5/db8/group__calib3d__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/da/d0a/group__imgcodecs__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/df/d4e/group__imgproc__c.html',1,'C API']]],
  ['c_20api_20for_20video_20i_20o_2',['C API for video I/O',['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__c.html',1,'']]],
  ['c_20c_20converters_3',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['c_20structures_20and_20operations_4',['C structures and operations',['https://docs.opencv.org/4.2.0/d2/df8/group__core__c.html',1,'']]],
  ['calculation_5',['calculation',['https://docs.opencv.org/4.2.0/d5/df4/group__core__hal__interface__fastAtan.html',1,'Atan calculation'],['https://docs.opencv.org/4.2.0/d4/d8a/group__core__hal__interface__exp.html',1,'Exponent calculation'],['https://docs.opencv.org/4.2.0/d8/d0e/group__cudaimgproc__hist.html',1,'Histogram Calculation'],['https://docs.opencv.org/4.2.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'Inverse square root calculation'],['https://docs.opencv.org/4.2.0/d7/d99/group__core__hal__interface__magnitude.html',1,'Magnitude calculation'],['https://docs.opencv.org/4.2.0/d2/de4/group__core__hal__interface__log.html',1,'Natural logarithm calculation'],['https://docs.opencv.org/4.2.0/d5/dc3/group__core__hal__interface__sqrt.html',1,'Square root calculation']]],
  ['calibration_20and_203d_20reconstruction_6',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html',1,'']]],
  ['calibration_20pattern_20for_203d_20reconstruction_7',['Custom Calibration Pattern for 3D reconstruction',['https://docs.opencv.org/4.2.0/d3/ddc/group__ccalib.html',1,'']]],
  ['camera_20access_8',['Camera Access',['../group__camera.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_9',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html',1,'']]],
  ['camera_20model_10',['Fisheye camera model',['https://docs.opencv.org/4.2.0/db/d58/group__calib3d__fisheye.html',1,'']]],
  ['catalog_20of_20coefficient_20wise_20math_20functions_11',['Catalog of coefficient-wise math functions',['https://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html',1,'']]],
  ['catalogue_20of_20dense_20decompositions_12',['Catalogue of dense decompositions',['https://eigen.tuxfamily.org/dox/group__TopicLinearAlgebraDecompositions.html',1,'']]],
  ['categorization_13',['Object Categorization',['https://docs.opencv.org/4.2.0/de/d24/group__features2d__category.html',1,'']]],
  ['channel_20composition_20functions_14',['Graph API: Image and channel composition functions',['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'']]],
  ['channel_20merge_15',['Channel merge',['https://docs.opencv.org/4.2.0/df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['channel_20split_16',['Channel split',['https://docs.opencv.org/4.2.0/df/df2/group__core__hal__interface__split.html',1,'']]],
  ['cholesky_20matrix_20decomposition_17',['Cholesky matrix decomposition',['https://docs.opencv.org/4.2.0/d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'']]],
  ['cholesky_20module_18',['Cholesky module',['https://eigen.tuxfamily.org/dox/group__Cholesky__Module.html',1,'']]],
  ['cholmodsupport_20module_19',['CholmodSupport module',['https://eigen.tuxfamily.org/dox/group__CholmodSupport__Module.html',1,'']]],
  ['cl_20va_20interoperability_20',['Intel VA-API/OpenCL (CL-VA) interoperability',['https://docs.opencv.org/4.2.0/d1/daa/group__core__va__intel.html',1,'']]],
  ['class_21',['class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'Interfacing with raw buffers: the Map class'],['https://eigen.tuxfamily.org/dox/group__TutorialMatrixClass.html',1,'The Matrix class']]],
  ['class_20and_20coefficient_20wise_20operations_22',['The Array class and coefficient-wise operations',['https://eigen.tuxfamily.org/dox/group__TutorialArrayClass.html',1,'']]],
  ['classes_23',['classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01506.html',1,'Arithmetic Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01501.html',1,'Base and Implementation Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01497.html',1,'Base and Implementation Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01531.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01535.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01529.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01517.html',1,'Binder Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01508.html',1,'Boolean Operations Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01507.html',1,'Comparison Classes'],['https://docs.opencv.org/4.2.0/d8/dd0/group__gapi__main__classes.html',1,'G-API Main Classes']]],
  ['cloning_24',['Seamless Cloning',['https://docs.opencv.org/4.2.0/df/da0/group__photo__clone.html',1,'']]],
  ['clustering_25',['Clustering',['https://docs.opencv.org/4.2.0/d5/d38/group__core__cluster.html',1,'']]],
  ['clustering_20and_20search_20in_20multi_20dimensional_20spaces_26',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['coefficient_20wise_20math_20functions_27',['Catalog of coefficient-wise math functions',['https://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html',1,'']]],
  ['coefficient_20wise_20operations_28',['The Array class and coefficient-wise operations',['https://eigen.tuxfamily.org/dox/group__TutorialArrayClass.html',1,'']]],
  ['color_20space_20conversions_29',['Color Space Conversions',['https://docs.opencv.org/4.2.0/d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['color_20space_20processing_30',['Color space processing',['https://docs.opencv.org/4.2.0/db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['color_20space_20to_20another_31',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['colormaps_20in_20opencv_32',['ColorMaps in OpenCV',['https://docs.opencv.org/4.2.0/d3/d50/group__imgproc__colormap.html',1,'']]],
  ['compare_33',['Element-wise compare',['https://docs.opencv.org/4.2.0/d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['comparison_20classes_34',['Comparison Classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01507.html',1,'']]],
  ['compensation_35',['Exposure Compensation',['https://docs.opencv.org/4.2.0/dd/dff/group__stitching__exposure.html',1,'']]],
  ['compilation_20arguments_36',['G-API Graph Compilation Arguments',['https://docs.opencv.org/4.2.0/d9/d29/group__gapi__compile__args.html',1,'']]],
  ['compiler_20making_20a_20wrong_20assumption_20on_20stack_20alignment_37',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['complex_20numbers_38',['Complex Numbers',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01476.html',1,'']]],
  ['composition_20functionality_39',['G-API Drawing and composition functionality',['https://docs.opencv.org/4.2.0/df/de4/group__gapi__draw.html',1,'']]],
  ['composition_20functions_40',['Graph API: Image and channel composition functions',['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'']]],
  ['computational_20photography_41',['Computational Photography',['https://docs.opencv.org/4.2.0/d1/d0d/group__photo.html',1,'']]],
  ['computer_20vision_42',['CUDA-accelerated Computer Vision',['https://docs.opencv.org/4.2.0/d1/d1e/group__cuda.html',1,'']]],
  ['computer_20vision_20programs_43',['GUI for Interactive Visual Debugging of Computer Vision Programs',['https://docs.opencv.org/4.2.0/df/dff/group__cvv.html',1,'']]],
  ['concurrency_44',['Concurrency',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01474.html',1,'']]],
  ['condition_20variables_45',['Condition Variables',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01477.html',1,'']]],
  ['conditioning_46',['Conditioning',['https://docs.opencv.org/4.2.0/da/d8b/group__conditioning.html',1,'']]],
  ['connections_20with_20c_47',['Connections with C++',['https://docs.opencv.org/4.2.0/d8/dd7/group__core__c__glue.html',1,'']]],
  ['const_20propagating_20wrapper_48',['Const-propagating wrapper',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01526.html',1,'']]],
  ['container_20of_20any_20type_49',['Type-safe container of any type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01522.html',1,'']]],
  ['containers_50',['containers',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01469.html',1,'Containers'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01527.html',1,'Containers']]],
  ['containers_20with_20eigen_51',['Using STL Containers with Eigen',['https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html',1,'']]],
  ['contrast_20preserving_20decolorization_52',['Contrast Preserving Decolorization',['https://docs.opencv.org/4.2.0/d4/d32/group__photo__decolor.html',1,'']]],
  ['conversions_53',['Color Space Conversions',['https://docs.opencv.org/4.2.0/d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['converters_54',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['converting_20image_20from_20one_20color_20space_20to_20another_55',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['core_56',['NPPST Core',['https://docs.opencv.org/4.2.0/d5/ddd/group__core__npp.html',1,'']]],
  ['core_20functionality_57',['core functionality',['https://docs.opencv.org/4.2.0/d0/de1/group__core.html',1,'Core functionality'],['https://docs.opencv.org/4.2.0/df/d1f/group__gapi__core.html',1,'G-API Core functionality']]],
  ['core_20module_58',['Core module',['https://eigen.tuxfamily.org/dox/group__Core__Module.html',1,'']]],
  ['core_20operations_20on_20matrices_59',['Core Operations on Matrices',['https://docs.opencv.org/4.2.0/de/d09/group__cudaarithm__core.html',1,'']]],
  ['core_20part_60',['Core part',['https://docs.opencv.org/4.2.0/d7/d05/group__cudacore.html',1,'']]],
  ['correspondance_20algorithms_61',['Stereo Correspondance Algorithms',['https://docs.opencv.org/4.2.0/dd/d86/group__stereo.html',1,'']]],
  ['correspondence_62',['Stereo Correspondence',['https://docs.opencv.org/4.2.0/dd/d47/group__cudastereo.html',1,'']]],
  ['creation_20functions_63',['Array creation functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01523.html',1,'']]],
  ['cuda_20accelerated_20computer_20vision_64',['CUDA-accelerated Computer Vision',['https://docs.opencv.org/4.2.0/d1/d1e/group__cuda.html',1,'']]],
  ['custom_20calibration_20pattern_20for_203d_20reconstruction_65',['Custom Calibration Pattern for 3D reconstruction',['https://docs.opencv.org/4.2.0/d3/ddc/group__ccalib.html',1,'']]]
];
