var searchData=
[
  ['layer_0',['layer',['https://docs.opencv.org/4.2.0/df/dfc/group__cudev.html',1,'Device layer'],['https://docs.opencv.org/4.2.0/de/d85/group__core__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/d3/df3/group__imgproc__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/d8/d45/group__feature2d__hal.html',1,'Hardware Acceleration Layer']]],
  ['layers_1',['Partial List of Implemented Layers',['https://docs.opencv.org/4.2.0/d6/d87/group__dnnLayerList.html',1,'']]],
  ['layers_20registration_2',['Utilities for New Layers Registration',['https://docs.opencv.org/4.2.0/df/dc1/group__dnnLayerFactory.html',1,'']]],
  ['learning_3',['Machine Learning',['https://docs.opencv.org/4.2.0/dd/ded/group__ml.html',1,'']]],
  ['least_20squares_20systems_4',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['legacy_20support_5',['Legacy support',['https://docs.opencv.org/4.2.0/d5/dc3/group__cudalegacy.html',1,'']]],
  ['length_20encoded_20image_6',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['level_20api_20for_20external_20libraries_20plugins_7',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['level_20gui_8',['High-level GUI',['https://docs.opencv.org/4.2.0/d7/dfc/group__highgui.html',1,'']]],
  ['libraries_20plugins_9',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['light_20api_10',['Structured Light API',['https://docs.opencv.org/4.2.0/d1/d90/group__structured__light.html',1,'']]],
  ['line_20detector_11',['Fast line detector',['https://docs.opencv.org/4.2.0/df/ded/group__ximgproc__fast__line__detector.html',1,'']]],
  ['linear_20algebra_12',['Sparse linear algebra',['https://eigen.tuxfamily.org/dox/group__Sparse__chapter.html',1,'']]],
  ['linear_20algebra_20and_20decompositions_13',['Linear algebra and decompositions',['https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html',1,'']]],
  ['linear_20least_20squares_20systems_14',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['linear_20problems_20and_20decompositions_15',['Dense linear problems and decompositions',['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__chapter.html',1,'']]],
  ['linear_20systems_16',['Solving Sparse Linear Systems',['https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html',1,'']]],
  ['lines_20extracted_20from_20an_20image_17',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['list_20based_18',['List-Based',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01532.html',1,'']]],
  ['list_20of_20implemented_20layers_19',['Partial List of Implemented Layers',['https://docs.opencv.org/4.2.0/d6/d87/group__dnnLayerList.html',1,'']]],
  ['locales_20',['Locales',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01498.html',1,'']]],
  ['logarithm_20calculation_21',['Natural logarithm calculation',['https://docs.opencv.org/4.2.0/d2/de4/group__core__hal__interface__log.html',1,'']]],
  ['logging_20facilities_22',['Logging facilities',['https://docs.opencv.org/4.2.0/d3/dcb/group__core__logging.html',1,'']]],
  ['logical_20operations_23',['Bitwise logical operations',['https://docs.opencv.org/4.2.0/d2/d18/group__core__hal__interface__logical.html',1,'']]],
  ['low_20level_20api_20for_20external_20libraries_20plugins_24',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['lu_20matrix_20decomposition_25',['LU matrix decomposition',['https://docs.opencv.org/4.2.0/d5/d42/group__core__hal__interface__decomp__lu.html',1,'']]],
  ['lu_20module_26',['LU module',['https://eigen.tuxfamily.org/dox/group__LU__Module.html',1,'']]]
];
