var searchData=
[
  ['image_20blenders_0',['Image Blenders',['https://docs.opencv.org/4.2.0/d9/d46/group__stitching__blend.html',1,'']]],
  ['image_20file_20reading_20and_20writing_1',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['image_20filtering_2',['Image Filtering',['https://docs.opencv.org/4.2.0/dc/d66/group__cudafilters.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d4/d86/group__imgproc__filter.html',1,'(Global Namespace)']]],
  ['image_20processing_3',['Image Processing',['https://docs.opencv.org/4.2.0/d0/d05/group__cudaimgproc.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d7/dbd/group__imgproc.html',1,'(Global Namespace)']]],
  ['image_20processing_20based_20on_20fuzzy_20mathematics_4',['Image processing based on fuzzy mathematics',['https://docs.opencv.org/4.2.0/df/d5b/group__fuzzy.html',1,'']]],
  ['image_20quality_20analysis_20_28iqa_29_20api_5',['Image Quality Analysis (IQA) API',['https://docs.opencv.org/4.2.0/dc/d20/group__quality.html',1,'']]],
  ['image_20registration_6',['Image Registration',['https://docs.opencv.org/4.2.0/dc/def/group__datasets__ir.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/db/d61/group__reg.html',1,'(Global Namespace)']]],
  ['image_20segmentation_7',['Image Segmentation',['https://docs.opencv.org/4.2.0/d3/d2d/group__datasets__is.html',1,'']]],
  ['image_20segmentation_8',['Image segmentation',['https://docs.opencv.org/4.2.0/d5/df0/group__ximgproc__segmentation.html',1,'']]],
  ['image_20warping_9',['Image Warping',['https://docs.opencv.org/4.2.0/db/d29/group__cudawarping.html',1,'']]],
  ['images_20stitching_10',['Images stitching',['https://docs.opencv.org/4.2.0/d1/d46/group__stitching.html',1,'']]],
  ['images_20warping_11',['Images Warping',['https://docs.opencv.org/4.2.0/d0/dfa/group__stitching__warp.html',1,'']]],
  ['improved_20background_2dforeground_20segmentation_20methods_12',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['initialization_20and_20information_13',['Initialization and Information',['https://docs.opencv.org/4.2.0/d8/d40/group__cudacore__init.html',1,'']]],
  ['inpainting_14',['Inpainting',['https://docs.opencv.org/4.2.0/d7/d8b/group__photo__inpaint.html',1,'']]],
  ['inplace_20matrix_20decompositions_15',['Inplace matrix decompositions',['https://eigen.tuxfamily.org/dox/group__InplaceDecomposition.html',1,'']]],
  ['input_2foutput_16',['Input/Output',['https://docs.opencv.org/4.2.0/d2/da3/group__io.html',1,'']]],
  ['intel_20ipp_20asynchronous_20c_2fc_2b_2b_20converters_17',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['intel_20va_2dapi_2fopencl_20_28cl_2dva_29_20interoperability_18',['Intel VA-API/OpenCL (CL-VA) interoperability',['https://docs.opencv.org/4.2.0/d1/daa/group__core__va__intel.html',1,'']]],
  ['interface_19',['Interface',['https://docs.opencv.org/4.2.0/d1/d1b/group__core__hal__interface.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/db/d47/group__features2d__hal__interface.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/dd/d8b/group__imgproc__hal__interface.html',1,'(Global Namespace)']]],
  ['interfacing_20with_20raw_20buffers_3a_20the_20map_20class_20',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['invalidation_20guarantees_21',['Invalidation Guarantees',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01538.html',1,'']]],
  ['inverse_20square_20root_20calculation_22',['Inverse square root calculation',['https://docs.opencv.org/4.2.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'']]],
  ['ios_20glue_23',['iOS glue',['https://docs.opencv.org/4.2.0/d2/d92/group__imgcodecs__ios.html',1,'']]],
  ['ios_20glue_20for_20video_20i_2fo_24',['iOS glue for video I/O',['https://docs.opencv.org/4.2.0/d5/d26/group__videoio__ios.html',1,'']]],
  ['iterativelinearsolvers_20module_25',['IterativeLinearSolvers module',['https://eigen.tuxfamily.org/dox/group__IterativeLinearSolvers__Module.html',1,'']]],
  ['iterator_20tags_26',['Iterator Tags',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01514.html',1,'']]],
  ['iterators_27',['Iterators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01513.html',1,'']]]
];
