var searchData=
[
  ['i_20o_0',['i o',['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__c.html',1,'C API for video I/O'],['https://docs.opencv.org/4.2.0/d4/d15/group__videoio__flags__base.html',1,'Flags for video I/O'],['https://docs.opencv.org/4.2.0/d5/d26/group__videoio__ios.html',1,'iOS glue for video I/O'],['https://docs.opencv.org/4.2.0/dd/de7/group__videoio.html',1,'Video I/O'],['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__winrt.html',1,'WinRT glue for video I/O']]],
  ['i_20o_20api_20backends_1',['Additional flags for video I/O API backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['i_20o_20api_20backends_20registry_2',['Query I/O API backends registry',['https://docs.opencv.org/4.2.0/de/db1/group__videoio__registry.html',1,'']]],
  ['i_20o_20routines_3',['Hierarchical Data Format I/O routines',['https://docs.opencv.org/4.2.0/db/d77/group__hdf.html',1,'']]],
  ['image_4',['image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'Binary descriptors for lines extracted from an image'],['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'Binary morphology on run-length encoded image']]],
  ['image_20and_20channel_20composition_20functions_5',['Graph API: Image and channel composition functions',['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'']]],
  ['image_20blenders_6',['Image Blenders',['https://docs.opencv.org/4.2.0/d9/d46/group__stitching__blend.html',1,'']]],
  ['image_20file_20reading_20and_20writing_7',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['image_20filtering_8',['image filtering',['https://docs.opencv.org/4.2.0/d4/d86/group__imgproc__filter.html',1,'Image Filtering'],['https://docs.opencv.org/4.2.0/dc/d66/group__cudafilters.html',1,'Image Filtering']]],
  ['image_20filters_9',['Graph API: Image filters',['https://docs.opencv.org/4.2.0/da/dc5/group__gapi__filters.html',1,'']]],
  ['image_20from_20one_20color_20space_20to_20another_10',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['image_20hashing_20algorithms_11',['The module brings implementations of different image hashing algorithms.',['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'']]],
  ['image_20processing_12',['image processing',['https://docs.opencv.org/4.2.0/df/d2d/group__ximgproc.html',1,'Extended Image Processing'],['https://docs.opencv.org/4.2.0/d1/dfc/group__f__image.html',1,'Fuzzy image processing'],['https://docs.opencv.org/4.2.0/d7/dbd/group__imgproc.html',1,'Image Processing'],['https://docs.opencv.org/4.2.0/d0/d05/group__cudaimgproc.html',1,'Image Processing'],['https://docs.opencv.org/4.2.0/d1/d0d/group__nppi.html',1,'NPPST Image Processing']]],
  ['image_20processing_20based_20on_20fuzzy_20mathematics_13',['Image processing based on fuzzy mathematics',['https://docs.opencv.org/4.2.0/df/d5b/group__fuzzy.html',1,'']]],
  ['image_20processing_20functionality_14',['G-API Image processing functionality',['https://docs.opencv.org/4.2.0/d2/d00/group__gapi__imgproc.html',1,'']]],
  ['image_20quality_20analysis_20iqa_20api_15',['Image Quality Analysis (IQA) API',['https://docs.opencv.org/4.2.0/dc/d20/group__quality.html',1,'']]],
  ['image_20registration_16',['image registration',['https://docs.opencv.org/4.2.0/dc/def/group__datasets__ir.html',1,'Image Registration'],['https://docs.opencv.org/4.2.0/db/d61/group__reg.html',1,'Image Registration']]],
  ['image_20segmentation_17',['image segmentation',['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'Hierarchical Feature Selection for Efficient Image Segmentation'],['https://docs.opencv.org/4.2.0/d3/d2d/group__datasets__is.html',1,'Image Segmentation'],['https://docs.opencv.org/4.2.0/d5/df0/group__ximgproc__segmentation.html',1,'Image segmentation']]],
  ['image_20transformations_18',['image transformations',['https://docs.opencv.org/4.2.0/da/d54/group__imgproc__transform.html',1,'Geometric Image Transformations'],['https://docs.opencv.org/4.2.0/d7/d1b/group__imgproc__misc.html',1,'Miscellaneous Image Transformations']]],
  ['image_20warping_19',['Image Warping',['https://docs.opencv.org/4.2.0/db/d29/group__cudawarping.html',1,'']]],
  ['images_20matching_20',['Features Finding and Images Matching',['https://docs.opencv.org/4.2.0/df/d8c/group__stitching__match.html',1,'']]],
  ['images_20stitching_21',['Images stitching',['https://docs.opencv.org/4.2.0/d1/d46/group__stitching.html',1,'']]],
  ['images_20warping_22',['Images Warping',['https://docs.opencv.org/4.2.0/d0/dfa/group__stitching__warp.html',1,'']]],
  ['imaging_23',['HDR imaging',['https://docs.opencv.org/4.2.0/d6/df5/group__photo__hdr.html',1,'']]],
  ['implementation_20classes_24',['implementation classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01497.html',1,'Base and Implementation Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01501.html',1,'Base and Implementation Classes']]],
  ['implementation_20helpers_25',['Private implementation helpers',['https://docs.opencv.org/4.2.0/dd/d96/group__core__hal__intrin__impl.html',1,'']]],
  ['implementations_20of_20different_20image_20hashing_20algorithms_26',['The module brings implementations of different image hashing algorithms.',['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'']]],
  ['implemented_20layers_27',['Partial List of Implemented Layers',['https://docs.opencv.org/4.2.0/d6/d87/group__dnnLayerList.html',1,'']]],
  ['improved_20background_20foreground_20segmentation_20methods_28',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['in_20multi_20dimensional_20spaces_29',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['in_20opencv_30',['ColorMaps in OpenCV',['https://docs.opencv.org/4.2.0/d3/d50/group__imgproc__colormap.html',1,'']]],
  ['indexing_31',['Slicing and Indexing',['https://eigen.tuxfamily.org/dox/group__TutorialSlicingIndexing.html',1,'']]],
  ['information_32',['Initialization and Information',['https://docs.opencv.org/4.2.0/d8/d40/group__cudacore__init.html',1,'']]],
  ['initialization_33',['Advanced initialization',['https://eigen.tuxfamily.org/dox/group__TutorialAdvancedInitialization.html',1,'']]],
  ['initialization_20and_20information_34',['Initialization and Information',['https://docs.opencv.org/4.2.0/d8/d40/group__cudacore__init.html',1,'']]],
  ['inpainting_35',['Inpainting',['https://docs.opencv.org/4.2.0/d7/d8b/group__photo__inpaint.html',1,'']]],
  ['inplace_20matrix_20decompositions_36',['Inplace matrix decompositions',['https://eigen.tuxfamily.org/dox/group__InplaceDecomposition.html',1,'']]],
  ['input_20output_37',['Input/Output',['https://docs.opencv.org/4.2.0/d2/da3/group__io.html',1,'']]],
  ['inspired_20vision_20models_20and_20derivated_20tools_38',['Biologically inspired vision models and derivated tools',['https://docs.opencv.org/4.2.0/dd/deb/group__bioinspired.html',1,'']]],
  ['intel_20ipp_20asynchronous_20c_20c_20converters_39',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['intel_20va_20api_20opencl_20cl_20va_20interoperability_40',['Intel VA-API/OpenCL (CL-VA) interoperability',['https://docs.opencv.org/4.2.0/d1/daa/group__core__va__intel.html',1,'']]],
  ['interactive_20visual_20debugging_20of_20computer_20vision_20programs_41',['GUI for Interactive Visual Debugging of Computer Vision Programs',['https://docs.opencv.org/4.2.0/df/dff/group__cvv.html',1,'']]],
  ['interface_42',['interface',['https://docs.opencv.org/4.2.0/dd/d8b/group__imgproc__hal__interface.html',1,'Interface'],['https://docs.opencv.org/4.2.0/db/d47/group__features2d__hal__interface.html',1,'Interface'],['https://docs.opencv.org/4.2.0/d1/d1b/group__core__hal__interface.html',1,'Interface']]],
  ['interfacing_20with_20raw_20buffers_3a_20the_20map_20class_43',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['interoperability_44',['interoperability',['https://docs.opencv.org/4.2.0/de/dc1/group__core__directx.html',1,'DirectX interoperability'],['https://docs.opencv.org/4.2.0/d1/daa/group__core__va__intel.html',1,'Intel VA-API/OpenCL (CL-VA) interoperability'],['https://docs.opencv.org/4.2.0/d2/d3c/group__core__opengl.html',1,'OpenGL interoperability']]],
  ['intrinsics_45',['Universal intrinsics',['https://docs.opencv.org/4.2.0/df/d91/group__core__hal__intrin.html',1,'']]],
  ['invalidation_20guarantees_46',['Invalidation Guarantees',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01538.html',1,'']]],
  ['inverse_20square_20root_20calculation_47',['Inverse square root calculation',['https://docs.opencv.org/4.2.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'']]],
  ['ios_20glue_48',['iOS glue',['https://docs.opencv.org/4.2.0/d2/d92/group__imgcodecs__ios.html',1,'']]],
  ['ios_20glue_20for_20video_20i_20o_49',['iOS glue for video I/O',['https://docs.opencv.org/4.2.0/d5/d26/group__videoio__ios.html',1,'']]],
  ['ipp_20asynchronous_20c_20c_20converters_50',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['iqa_20api_51',['Image Quality Analysis (IQA) API',['https://docs.opencv.org/4.2.0/dc/d20/group__quality.html',1,'']]],
  ['issues_52',['Alignment issues',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__Alignement.html',1,'']]],
  ['iterativelinearsolvers_20module_53',['IterativeLinearSolvers module',['https://eigen.tuxfamily.org/dox/group__IterativeLinearSolvers__Module.html',1,'']]],
  ['iterator_20tags_54',['Iterator Tags',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01514.html',1,'']]],
  ['iterators_55',['Iterators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01513.html',1,'']]],
  ['iterators_20and_20algorithms_56',['STL iterators and algorithms',['https://eigen.tuxfamily.org/dox/group__TutorialSTL.html',1,'']]]
];
