var searchData=
[
  ['safe_20container_20of_20any_20type_0',['Type-safe container of any type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01522.html',1,'']]],
  ['saliency_20api_1',['Saliency API',['https://docs.opencv.org/4.2.0/d8/d65/group__saliency.html',1,'']]],
  ['samples_2',['Utility functions for OpenCV samples',['https://docs.opencv.org/4.2.0/d6/dba/group__core__utils__samples.html',1,'']]],
  ['scene_20text_20detection_3',['Scene Text Detection',['https://docs.opencv.org/4.2.0/da/d56/group__text__detect.html',1,'']]],
  ['scene_20text_20detection_20and_20recognition_4',['Scene Text Detection and Recognition',['https://docs.opencv.org/4.2.0/d4/d61/group__text.html',1,'']]],
  ['scene_20text_20recognition_5',['Scene Text Recognition',['https://docs.opencv.org/4.2.0/d8/df2/group__text__recognize.html',1,'']]],
  ['seam_20estimation_6',['Seam Estimation',['https://docs.opencv.org/4.2.0/d9/d24/group__stitching__seam.html',1,'']]],
  ['seamless_20cloning_7',['Seamless Cloning',['https://docs.opencv.org/4.2.0/df/da0/group__photo__clone.html',1,'']]],
  ['search_8',['Binary Search',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01493.html',1,'']]],
  ['search_20in_20multi_20dimensional_20spaces_9',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['segmentation_10',['segmentation',['https://docs.opencv.org/4.2.0/d6/d17/group__cudabgsegm.html',1,'Background Segmentation'],['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'Hierarchical Feature Selection for Efficient Image Segmentation'],['https://docs.opencv.org/4.2.0/d3/d2d/group__datasets__is.html',1,'Image Segmentation'],['https://docs.opencv.org/4.2.0/d5/df0/group__ximgproc__segmentation.html',1,'Image segmentation']]],
  ['segmentation_20methods_11',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['selection_20for_20efficient_20image_20segmentation_12',['Hierarchical Feature Selection for Efficient Image Segmentation',['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'']]],
  ['sequences_13',['Sequences',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01470.html',1,'']]],
  ['set_20operations_14',['Set Operations',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01492.html',1,'']]],
  ['sgi_15',['SGI',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01468.html',1,'']]],
  ['shape_20descriptors_16',['Structural Analysis and Shape Descriptors',['https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html',1,'']]],
  ['shape_20distance_20and_20matching_17',['Shape Distance and Matching',['https://docs.opencv.org/4.2.0/d1/d85/group__shape.html',1,'']]],
  ['signal_20processing_18',['NPPST Signal Processing',['https://docs.opencv.org/4.2.0/de/d25/group__npps.html',1,'']]],
  ['simple_20pipeline_19',['Simple Pipeline',['https://docs.opencv.org/4.2.0/d7/de2/group__simple__pipeline.html',1,'']]],
  ['singular_20value_20matrix_20decomposition_20',['Singular value matrix decomposition',['https://docs.opencv.org/4.2.0/dd/d2a/group__core__hal__interface__decomp__svd.html',1,'']]],
  ['size_20vectorizable_20eigen_20objects_21',['Fixed-size vectorizable Eigen objects',['https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html',1,'']]],
  ['slam_22',['SLAM',['https://docs.opencv.org/4.2.0/dc/dfb/group__datasets__slam.html',1,'']]],
  ['slicing_20and_20indexing_23',['Slicing and Indexing',['https://eigen.tuxfamily.org/dox/group__TutorialSlicingIndexing.html',1,'']]],
  ['softfloat_20support_24',['Softfloat support',['https://docs.opencv.org/4.2.0/d7/dcc/group__core__utils__softfloat.html',1,'']]],
  ['solvers_25',['Matrix-free solvers',['https://eigen.tuxfamily.org/dox/group__MatrixfreeSolverExample.html',1,'']]],
  ['solving_20linear_20least_20squares_20systems_26',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['solving_20sparse_20linear_20systems_27',['Solving Sparse Linear Systems',['https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html',1,'']]],
  ['sorting_28',['Sorting',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01491.html',1,'']]],
  ['space_20conversions_29',['Color Space Conversions',['https://docs.opencv.org/4.2.0/d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['space_20processing_30',['Color space processing',['https://docs.opencv.org/4.2.0/db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['space_20to_20another_31',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['space_20transformations_32',['Space transformations',['https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html',1,'']]],
  ['spaces_33',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['sparse_20linear_20algebra_34',['Sparse linear algebra',['https://eigen.tuxfamily.org/dox/group__Sparse__chapter.html',1,'']]],
  ['sparse_20linear_20systems_35',['Solving Sparse Linear Systems',['https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html',1,'']]],
  ['sparse_20matrices_36',['Quick reference guide for sparse matrices',['https://eigen.tuxfamily.org/dox/group__SparseQuickRefPage.html',1,'']]],
  ['sparse_20matrix_20manipulations_37',['Sparse matrix manipulations',['https://eigen.tuxfamily.org/dox/group__TutorialSparse.html',1,'']]],
  ['sparse_20meta_20module_38',['Sparse meta-module',['https://eigen.tuxfamily.org/dox/group__Sparse__Module.html',1,'']]],
  ['sparsecholesky_20module_39',['SparseCholesky module',['https://eigen.tuxfamily.org/dox/group__SparseCholesky__Module.html',1,'']]],
  ['sparsecore_20module_40',['SparseCore module',['https://eigen.tuxfamily.org/dox/group__SparseCore__Module.html',1,'']]],
  ['sparselu_20module_41',['SparseLU module',['https://eigen.tuxfamily.org/dox/group__SparseLU__Module.html',1,'']]],
  ['sparseqr_20module_42',['SparseQR module',['https://eigen.tuxfamily.org/dox/group__SparseQR__Module.html',1,'']]],
  ['special_20functions_43',['special functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01518.html',1,'Mathematical Special Functions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01503.html',1,'Mathematical Special Functions']]],
  ['splines_5fmodule_44',['Splines_Module',['https://eigen.tuxfamily.org/dox/group__Splines__Module.html',1,'']]],
  ['split_45',['Channel split',['https://docs.opencv.org/4.2.0/df/df2/group__core__hal__interface__split.html',1,'']]],
  ['square_20root_20calculation_46',['square root calculation',['https://docs.opencv.org/4.2.0/d0/d5d/group__core__hal__interface__invSqrt.html',1,'Inverse square root calculation'],['https://docs.opencv.org/4.2.0/d5/dc3/group__core__hal__interface__sqrt.html',1,'Square root calculation']]],
  ['squares_20systems_47',['Solving linear least squares systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'']]],
  ['sse_20utilities_48',['SSE utilities',['https://docs.opencv.org/4.2.0/d6/d06/group__core__utils__sse.html',1,'']]],
  ['stabilization_49',['Video Stabilization',['https://docs.opencv.org/4.2.0/d5/d50/group__videostab.html',1,'']]],
  ['stack_20alignment_50',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['standard_20backends_51',['G-API Standard Backends',['https://docs.opencv.org/4.2.0/dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['stereo_20correspondance_20algorithms_52',['Stereo Correspondance Algorithms',['https://docs.opencv.org/4.2.0/dd/d86/group__stereo.html',1,'']]],
  ['stereo_20correspondence_53',['Stereo Correspondence',['https://docs.opencv.org/4.2.0/dd/d47/group__cudastereo.html',1,'']]],
  ['stereo_20matching_54',['Multiview Stereo Matching',['https://docs.opencv.org/4.2.0/d7/dd5/group__datasets__msm.html',1,'']]],
  ['stitching_55',['Images stitching',['https://docs.opencv.org/4.2.0/d1/d46/group__stitching.html',1,'']]],
  ['stl_20containers_20with_20eigen_56',['Using STL Containers with Eigen',['https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html',1,'']]],
  ['stl_20iterators_20and_20algorithms_57',['STL iterators and algorithms',['https://eigen.tuxfamily.org/dox/group__TutorialSTL.html',1,'']]],
  ['storage_20orders_58',['Storage orders',['https://eigen.tuxfamily.org/dox/group__TopicStorageOrders.html',1,'']]],
  ['strings_59',['Strings',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01516.html',1,'']]],
  ['strings_20with_20freetype_20harfbuzz_60',['Drawing UTF-8 strings with freetype/harfbuzz',['https://docs.opencv.org/4.2.0/d4/dfc/group__freetype.html',1,'']]],
  ['structural_20analysis_20and_20shape_20descriptors_61',['Structural Analysis and Shape Descriptors',['https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html',1,'']]],
  ['structure_20from_20motion_62',['Structure From Motion',['https://docs.opencv.org/4.2.0/d8/d8c/group__sfm.html',1,'']]],
  ['structure_20type_63',['Data Structure Type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01539.html',1,'']]],
  ['structured_20forests_20for_20fast_20edge_20detection_64',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['structured_20light_20api_65',['Structured Light API',['https://docs.opencv.org/4.2.0/d1/d90/group__structured__light.html',1,'']]],
  ['structures_66',['structures',['https://docs.opencv.org/4.2.0/dc/d84/group__core__basic.html',1,'Basic structures'],['https://docs.opencv.org/4.2.0/d9/d41/group__cudacore__struct.html',1,'Data Structures'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01536.html',1,'Policy-Based Data Structures']]],
  ['structures_20and_20operations_67',['C structures and operations',['https://docs.opencv.org/4.2.0/d2/df8/group__core__c.html',1,'']]],
  ['structures_20having_20eigen_20members_68',['Structures Having Eigen Members',['https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html',1,'']]],
  ['subdivision_69',['Planar Subdivision',['https://docs.opencv.org/4.2.0/df/d5b/group__imgproc__subdiv2d.html',1,'']]],
  ['subtract_70',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['suitesparseqr_20module_71',['SuiteSparseQR module',['https://eigen.tuxfamily.org/dox/group__SPQRSupport__Module.html',1,'']]],
  ['sum_72',['Element-wise weighted sum',['https://docs.opencv.org/4.2.0/da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['super_20resolution_73',['super resolution',['https://docs.opencv.org/4.2.0/d9/de0/group__dnn__superres.html',1,'DNN used for super resolution'],['https://docs.opencv.org/4.2.0/d1/d5b/group__datasets__sr.html',1,'Super Resolution'],['https://docs.opencv.org/4.2.0/d7/d0a/group__superres.html',1,'Super Resolution']]],
  ['superlusupport_20module_74',['SuperLUSupport module',['https://eigen.tuxfamily.org/dox/group__SuperLUSupport__Module.html',1,'']]],
  ['superpixels_75',['Superpixels',['https://docs.opencv.org/4.2.0/df/d6c/group__ximgproc__superpixel.html',1,'']]],
  ['support_76',['support',['https://docs.opencv.org/4.2.0/d0/daf/group__core__eigen.html',1,'Eigen support'],['https://docs.opencv.org/4.2.0/d5/dc3/group__cudalegacy.html',1,'Legacy support'],['https://docs.opencv.org/4.2.0/d5/d8e/group__f0__math.html',1,'Math with F0-transform support'],['https://docs.opencv.org/4.2.0/d6/df0/group__f1__math.html',1,'Math with F1-transform support'],['https://docs.opencv.org/4.2.0/dc/d83/group__core__opencl.html',1,'OpenCL support'],['https://docs.opencv.org/4.2.0/df/d24/group__highgui__opengl.html',1,'OpenGL support'],['https://docs.opencv.org/4.2.0/d7/dcc/group__core__utils__softfloat.html',1,'Softfloat support'],['https://docs.opencv.org/4.2.0/d6/d2f/group__highgui__winrt.html',1,'WinRT support']]],
  ['support_20modules_77',['Support modules',['https://eigen.tuxfamily.org/dox/group__Support__modules.html',1,'']]],
  ['surface_20matching_78',['Surface Matching',['https://docs.opencv.org/4.2.0/d9/d25/group__surface__matching.html',1,'']]],
  ['svd_20module_79',['SVD module',['https://eigen.tuxfamily.org/dox/group__SVD__Module.html',1,'']]],
  ['system_20functions_20and_20macros_80',['Utility and system functions and macros',['https://docs.opencv.org/4.2.0/db/de0/group__core__utils.html',1,'']]],
  ['systems_81',['systems',['https://eigen.tuxfamily.org/dox/group__LeastSquares.html',1,'Solving linear least squares systems'],['https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html',1,'Solving Sparse Linear Systems']]]
];
