var searchData=
[
  ['natural_20logarithm_20calculation_0',['Natural logarithm calculation',['https://docs.opencv.org/4.2.0/d2/de4/group__core__hal__interface__log.html',1,'']]],
  ['negators_1',['Negators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01509.html',1,'']]],
  ['neon_20utilities_2',['NEON utilities',['https://docs.opencv.org/4.2.0/d8/d45/group__core__utils__neon.html',1,'']]],
  ['network_20module_3',['Deep Neural Network module',['https://docs.opencv.org/4.2.0/d6/d0f/group__dnn.html',1,'']]],
  ['neural_20network_20module_4',['Deep Neural Network module',['https://docs.opencv.org/4.2.0/d6/d0f/group__dnn.html',1,'']]],
  ['new_20functions_5',['Qt New Functions',['https://docs.opencv.org/4.2.0/dc/d46/group__highgui__qt.html',1,'']]],
  ['new_20layers_20registration_6',['Utilities for New Layers Registration',['https://docs.opencv.org/4.2.0/df/dc1/group__dnnLayerFactory.html',1,'']]],
  ['non_20free_202d_20features_20algorithms_7',['Non-free 2D Features Algorithms',['https://docs.opencv.org/4.2.0/d2/dca/group__xfeatures2d__nonfree.html',1,'']]],
  ['non_20mutating_8',['Non-Mutating',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01490.html',1,'']]],
  ['non_20photorealistic_20rendering_9',['Non-Photorealistic Rendering',['https://docs.opencv.org/4.2.0/df/dac/group__photo__render.html',1,'']]],
  ['normal_20distributions_10',['Normal Distributions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01544.html',1,'']]],
  ['nppst_20core_11',['NPPST Core',['https://docs.opencv.org/4.2.0/d5/ddd/group__core__npp.html',1,'']]],
  ['nppst_20image_20processing_12',['NPPST Image Processing',['https://docs.opencv.org/4.2.0/d1/d0d/group__nppi.html',1,'']]],
  ['nppst_20signal_20processing_13',['NPPST Signal Processing',['https://docs.opencv.org/4.2.0/de/d25/group__npps.html',1,'']]],
  ['number_20distributions_14',['Random Number Distributions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01542.html',1,'']]],
  ['number_20generation_15',['Random Number Generation',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01500.html',1,'']]],
  ['number_20generators_16',['Random Number Generators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01541.html',1,'']]],
  ['number_20utilities_17',['Random Number Utilities',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01547.html',1,'']]],
  ['numbers_18',['Complex Numbers',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01476.html',1,'']]],
  ['numeric_19',['Numeric',['https://docs.opencv.org/4.2.0/d1/d6a/group__numeric.html',1,'']]],
  ['numeric_20arrays_20',['Numeric Arrays',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01487.html',1,'']]],
  ['numeric_20operations_21',['Generalized Numeric operations',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01515.html',1,'']]],
  ['numerics_22',['Numerics',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01482.html',1,'']]]
];
