var searchData=
[
  ['edgeboxes_36618',['EdgeBoxes',['https://docs.opencv.org/4.2.0/d4/d0d/group__ximgproc__edgeboxes.html',1,'']]],
  ['eigen_20support_36619',['Eigen support',['https://docs.opencv.org/4.2.0/d0/daf/group__core__eigen.html',1,'']]],
  ['eigenvalues_20module_36620',['Eigenvalues module',['https://eigen.tuxfamily.org/dox/group__Eigenvalues__Module.html',1,'']]],
  ['element_2dwise_20absolute_20difference_36621',['Element-wise absolute difference',['https://docs.opencv.org/4.2.0/d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['element_2dwise_20add_20and_20subtract_36622',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['element_2dwise_20compare_36623',['Element-wise compare',['https://docs.opencv.org/4.2.0/d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['element_2dwise_20divide_36624',['Element-wise divide',['https://docs.opencv.org/4.2.0/dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['element_2dwise_20minimum_20or_20maximum_36625',['Element-wise minimum or maximum',['https://docs.opencv.org/4.2.0/dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['element_2dwise_20multiply_36626',['Element-wise multiply',['https://docs.opencv.org/4.2.0/de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['element_2dwise_20reciprocial_36627',['Element-wise reciprocial',['https://docs.opencv.org/4.2.0/d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['element_2dwise_20weighted_20sum_36628',['Element-wise weighted sum',['https://docs.opencv.org/4.2.0/da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['enumerations_36629',['Enumerations',['https://eigen.tuxfamily.org/dox/group__enums.html',1,'']]],
  ['exceptions_36630',['Exceptions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01495.html',1,'(Global Namespace)'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01533.html',1,'(Global Namespace)']]],
  ['experimental_36631',['Experimental',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01524.html',1,'']]],
  ['experimental_202d_20features_20algorithms_36632',['Experimental 2D Features Algorithms',['https://docs.opencv.org/4.2.0/d7/d7a/group__xfeatures2d__experiment.html',1,'']]],
  ['experimental_202d_20features_20matching_20algorithm_36633',['Experimental 2D Features Matching Algorithm',['https://docs.opencv.org/4.2.0/db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['explanation_20of_20the_20assertion_20on_20unaligned_20arrays_36634',['Explanation of the assertion on unaligned arrays',['https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html',1,'']]],
  ['exponent_20calculation_36635',['Exponent calculation',['https://docs.opencv.org/4.2.0/d4/d8a/group__core__hal__interface__exp.html',1,'']]],
  ['exposure_20compensation_36636',['Exposure Compensation',['https://docs.opencv.org/4.2.0/dd/dff/group__stitching__exposure.html',1,'']]],
  ['extended_20image_20processing_36637',['Extended Image Processing',['https://docs.opencv.org/4.2.0/df/d2d/group__ximgproc.html',1,'']]],
  ['extended_20object_20detection_36638',['Extended object detection',['https://docs.opencv.org/4.2.0/d4/d54/group__xobjdetect.html',1,'']]],
  ['extensions_36639',['Extensions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01467.html',1,'']]],
  ['extra_202d_20features_20framework_36640',['Extra 2D Features Framework',['https://docs.opencv.org/4.2.0/d1/db4/group__xfeatures2d.html',1,'']]]
];
