var searchData=
[
  ['warping_0',['warping',['https://docs.opencv.org/4.2.0/db/d29/group__cudawarping.html',1,'Image Warping'],['https://docs.opencv.org/4.2.0/d0/dfa/group__stitching__warp.html',1,'Images Warping']]],
  ['weighted_20sum_1',['Element-wise weighted sum',['https://docs.opencv.org/4.2.0/da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['widget_2',['Widget',['https://docs.opencv.org/4.2.0/dc/d5c/group__viz__widget.html',1,'']]],
  ['winrt_20glue_20for_20video_20i_20o_3',['WinRT glue for video I/O',['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__winrt.html',1,'']]],
  ['winrt_20support_4',['WinRT support',['https://docs.opencv.org/4.2.0/d6/d2f/group__highgui__winrt.html',1,'']]],
  ['wise_20absolute_20difference_5',['Element-wise absolute difference',['https://docs.opencv.org/4.2.0/d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['wise_20add_20and_20subtract_6',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['wise_20compare_7',['Element-wise compare',['https://docs.opencv.org/4.2.0/d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['wise_20divide_8',['Element-wise divide',['https://docs.opencv.org/4.2.0/dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['wise_20math_20functions_9',['Catalog of coefficient-wise math functions',['https://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html',1,'']]],
  ['wise_20minimum_20or_20maximum_10',['Element-wise minimum or maximum',['https://docs.opencv.org/4.2.0/dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['wise_20multiply_11',['Element-wise multiply',['https://docs.opencv.org/4.2.0/de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['wise_20operations_12',['The Array class and coefficient-wise operations',['https://eigen.tuxfamily.org/dox/group__TutorialArrayClass.html',1,'']]],
  ['wise_20reciprocial_13',['Element-wise reciprocial',['https://docs.opencv.org/4.2.0/d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['wise_20weighted_20sum_14',['Element-wise weighted sum',['https://docs.opencv.org/4.2.0/da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['with_20c_15',['Connections with C++',['https://docs.opencv.org/4.2.0/d8/dd7/group__core__c__glue.html',1,'']]],
  ['with_20different_20datasets_16',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['with_20eigen_17',['Using STL Containers with Eigen',['https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html',1,'']]],
  ['with_20f0_20transform_20support_18',['Math with F0-transform support',['https://docs.opencv.org/4.2.0/d5/d8e/group__f0__math.html',1,'']]],
  ['with_20f1_20transform_20support_19',['Math with F1-transform support',['https://docs.opencv.org/4.2.0/d6/df0/group__f1__math.html',1,'']]],
  ['with_20freetype_20harfbuzz_20',['Drawing UTF-8 strings with freetype/harfbuzz',['https://docs.opencv.org/4.2.0/d4/dfc/group__freetype.html',1,'']]],
  ['with_20raw_20buffers_3a_20the_20map_20class_21',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['working_20with_20different_20datasets_22',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['wrapper_23',['Const-propagating wrapper',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01526.html',1,'']]],
  ['writing_24',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['wrong_20assumption_20on_20stack_20alignment_25',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]]
];
