var searchData=
[
  ['a_20wrong_20assumption_20on_20stack_20alignment_0',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['absolute_20difference_1',['Element-wise absolute difference',['https://docs.opencv.org/4.2.0/d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['abstractions_2',['Pointer Abstractions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01481.html',1,'']]],
  ['accelerated_20computer_20vision_3',['CUDA-accelerated Computer Vision',['https://docs.opencv.org/4.2.0/d1/d1e/group__cuda.html',1,'']]],
  ['acceleration_20layer_4',['acceleration layer',['https://docs.opencv.org/4.2.0/d8/d45/group__feature2d__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/d3/df3/group__imgproc__hal.html',1,'Hardware Acceleration Layer'],['https://docs.opencv.org/4.2.0/de/d85/group__core__hal.html',1,'Hardware Acceleration Layer']]],
  ['access_5',['Camera Access',['../group__camera.html',1,'']]],
  ['action_20recognition_6',['Action Recognition',['https://docs.opencv.org/4.2.0/d4/d8b/group__datasets__ar.html',1,'']]],
  ['adaptors_20for_20pointers_20to_20functions_7',['Adaptors for pointers to functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01510.html',1,'']]],
  ['adaptors_20for_20pointers_20to_20members_8',['Adaptors for pointers to members',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01511.html',1,'']]],
  ['add_20and_20subtract_9',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['additional_20flags_20for_20video_20i_20o_20api_20backends_10',['Additional flags for video I/O API backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['additional_20photo_20processing_20algorithms_11',['Additional photo processing algorithms',['https://docs.opencv.org/4.2.0/de/daa/group__xphoto.html',1,'']]],
  ['advanced_20initialization_12',['Advanced initialization',['https://eigen.tuxfamily.org/dox/group__TutorialAdvancedInitialization.html',1,'']]],
  ['algebra_13',['Sparse linear algebra',['https://eigen.tuxfamily.org/dox/group__Sparse__chapter.html',1,'']]],
  ['algebra_20and_20decompositions_14',['Linear algebra and decompositions',['https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html',1,'']]],
  ['algorithm_15',['Experimental 2D Features Matching Algorithm',['https://docs.opencv.org/4.2.0/db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['algorithms_16',['algorithms',['https://docs.opencv.org/4.2.0/de/daa/group__xphoto.html',1,'Additional photo processing algorithms'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01488.html',1,'Algorithms'],['https://docs.opencv.org/4.2.0/d7/d7a/group__xfeatures2d__experiment.html',1,'Experimental 2D Features Algorithms'],['https://docs.opencv.org/4.2.0/d2/dca/group__xfeatures2d__nonfree.html',1,'Non-free 2D Features Algorithms'],['https://docs.opencv.org/4.2.0/d2/d84/group__optflow.html',1,'Optical Flow Algorithms'],['https://docs.opencv.org/4.2.0/da/d01/group__core__optim.html',1,'Optimization Algorithms'],['https://docs.opencv.org/4.2.0/dd/d86/group__stereo.html',1,'Stereo Correspondance Algorithms'],['https://eigen.tuxfamily.org/dox/group__TutorialSTL.html',1,'STL iterators and algorithms'],['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'The module brings implementations of different image hashing algorithms.']]],
  ['aliasing_17',['Aliasing',['https://eigen.tuxfamily.org/dox/group__TopicAliasing.html',1,'']]],
  ['aligned_20box_20typedefs_18',['Global aligned box typedefs',['https://eigen.tuxfamily.org/dox/group__alignedboxtypedefs.html',1,'']]],
  ['alignment_19',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['alignment_20issues_20',['Alignment issues',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__Alignement.html',1,'']]],
  ['allocators_21',['Allocators',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01499.html',1,'']]],
  ['an_20image_22',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['analysis_23',['analysis',['https://docs.opencv.org/4.2.0/db/d7c/group__face.html',1,'Face Analysis'],['https://docs.opencv.org/4.2.0/de/de1/group__video__motion.html',1,'Motion Analysis'],['https://docs.opencv.org/4.2.0/d7/de9/group__video.html',1,'Video Analysis']]],
  ['analysis_20and_20object_20tracking_24',['Motion Analysis and Object Tracking',['https://docs.opencv.org/4.2.0/d7/df3/group__imgproc__motion.html',1,'']]],
  ['analysis_20and_20shape_20descriptors_25',['Structural Analysis and Shape Descriptors',['https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html',1,'']]],
  ['analysis_20iqa_20api_26',['Image Quality Analysis (IQA) API',['https://docs.opencv.org/4.2.0/dc/d20/group__quality.html',1,'']]],
  ['and_203d_20reconstruction_27',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/d0c/group__calib3d.html',1,'']]],
  ['and_20algorithms_28',['STL iterators and algorithms',['https://eigen.tuxfamily.org/dox/group__TutorialSTL.html',1,'']]],
  ['and_20array_20manipulation_29',['Dense matrix and array manipulation',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__chapter.html',1,'']]],
  ['and_20broadcasting_30',['Reductions, visitors and broadcasting',['https://eigen.tuxfamily.org/dox/group__TutorialReductionsVisitorsBroadcasting.html',1,'']]],
  ['and_20channel_20composition_20functions_31',['Graph API: Image and channel composition functions',['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'']]],
  ['and_20coefficient_20wise_20operations_32',['The Array class and coefficient-wise operations',['https://eigen.tuxfamily.org/dox/group__TutorialArrayClass.html',1,'']]],
  ['and_20composition_20functionality_33',['G-API Drawing and composition functionality',['https://docs.opencv.org/4.2.0/df/de4/group__gapi__draw.html',1,'']]],
  ['and_20decompositions_34',['and decompositions',['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__chapter.html',1,'Dense linear problems and decompositions'],['https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html',1,'Linear algebra and decompositions']]],
  ['and_20derivated_20tools_35',['Biologically inspired vision models and derivated tools',['https://docs.opencv.org/4.2.0/dd/deb/group__bioinspired.html',1,'']]],
  ['and_20description_36',['and description',['https://docs.opencv.org/4.2.0/d5/d51/group__features2d__main.html',1,'Feature Detection and Description'],['https://docs.opencv.org/4.2.0/d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description']]],
  ['and_20functions_37',['Drawing operations and functions',['https://docs.opencv.org/4.2.0/d0/d43/group__gapi__draw__api.html',1,'']]],
  ['and_20images_20matching_38',['Features Finding and Images Matching',['https://docs.opencv.org/4.2.0/df/d8c/group__stitching__match.html',1,'']]],
  ['and_20implementation_20classes_39',['and implementation classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01497.html',1,'Base and Implementation Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01501.html',1,'Base and Implementation Classes']]],
  ['and_20indexing_40',['Slicing and Indexing',['https://eigen.tuxfamily.org/dox/group__TutorialSlicingIndexing.html',1,'']]],
  ['and_20information_41',['Initialization and Information',['https://docs.opencv.org/4.2.0/d8/d40/group__cudacore__init.html',1,'']]],
  ['and_20matches_42',['Drawing Function of Keypoints and Matches',['https://docs.opencv.org/4.2.0/d4/d5d/group__features2d__draw.html',1,'']]],
  ['and_20matching_43',['Shape Distance and Matching',['https://docs.opencv.org/4.2.0/d1/d85/group__shape.html',1,'']]],
  ['and_20object_20tracking_44',['Motion Analysis and Object Tracking',['https://docs.opencv.org/4.2.0/d7/df3/group__imgproc__motion.html',1,'']]],
  ['and_20operations_45',['C structures and operations',['https://docs.opencv.org/4.2.0/d2/df8/group__core__c.html',1,'']]],
  ['and_20policy_20classes_46',['and policy classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01529.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01535.html',1,'Base and Policy Classes'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01531.html',1,'Base and Policy Classes']]],
  ['and_20pose_20estimation_20api_47',['3D object recognition and pose estimation API',['https://docs.opencv.org/4.2.0/d9/d02/group__cnn__3dobj.html',1,'']]],
  ['and_20recognition_48',['Scene Text Detection and Recognition',['https://docs.opencv.org/4.2.0/d4/d61/group__text.html',1,'']]],
  ['and_20search_20in_20multi_20dimensional_20spaces_49',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['and_20shape_20descriptors_50',['Structural Analysis and Shape Descriptors',['https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html',1,'']]],
  ['and_20subtract_51',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['and_20system_20functions_20and_20macros_52',['Utility and system functions and macros',['https://docs.opencv.org/4.2.0/db/de0/group__core__utils.html',1,'']]],
  ['and_20vector_20arithmetic_53',['Matrix and vector arithmetic',['https://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html',1,'']]],
  ['and_20writing_54',['Image file reading and writing',['https://docs.opencv.org/4.2.0/d4/da8/group__imgcodecs.html',1,'']]],
  ['another_55',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['any_20type_56',['Type-safe container of any type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01522.html',1,'']]],
  ['api_57',['api',['https://docs.opencv.org/4.2.0/d9/d02/group__cnn__3dobj.html',1,'3D object recognition and pose estimation API'],['https://docs.opencv.org/4.2.0/da/d57/group__core__async.html',1,'Asynchronous API'],['https://docs.opencv.org/4.2.0/d3/d40/group__photo__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d9/d31/group__objdetect__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/da/d0a/group__imgcodecs__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d0/d28/group__highgui__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/df/d4e/group__imgproc__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d3/d12/group__video__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/d5/db8/group__calib3d__c.html',1,'C API'],['https://docs.opencv.org/4.2.0/dc/d20/group__quality.html',1,'Image Quality Analysis (IQA) API'],['https://docs.opencv.org/4.2.0/df/d3a/group__phase__unwrapping.html',1,'Phase Unwrapping API'],['https://docs.opencv.org/4.2.0/d8/d65/group__saliency.html',1,'Saliency API'],['https://docs.opencv.org/4.2.0/d1/d90/group__structured__light.html',1,'Structured Light API'],['https://docs.opencv.org/4.2.0/d9/df8/group__tracking.html',1,'Tracking API']]],
  ['api_20backends_58',['Additional flags for video I/O API backends',['https://docs.opencv.org/4.2.0/dc/dfc/group__videoio__flags__others.html',1,'']]],
  ['api_20backends_20registry_59',['Query I/O API backends registry',['https://docs.opencv.org/4.2.0/de/db1/group__videoio__registry.html',1,'']]],
  ['api_20core_20functionality_60',['G-API Core functionality',['https://docs.opencv.org/4.2.0/df/d1f/group__gapi__core.html',1,'']]],
  ['api_20data_20types_61',['G-API Data Types',['https://docs.opencv.org/4.2.0/db/df1/group__gapi__data__objects.html',1,'']]],
  ['api_20drawing_20and_20composition_20functionality_62',['G-API Drawing and composition functionality',['https://docs.opencv.org/4.2.0/df/de4/group__gapi__draw.html',1,'']]],
  ['api_20for_20external_20libraries_20plugins_63',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['api_20for_20video_20i_20o_64',['C API for video I/O',['https://docs.opencv.org/4.2.0/dd/d01/group__videoio__c.html',1,'']]],
  ['api_20framework_65',['G-API framework',['https://docs.opencv.org/4.2.0/d7/d0d/group__gapi.html',1,'']]],
  ['api_20graph_20compilation_20arguments_66',['G-API Graph Compilation Arguments',['https://docs.opencv.org/4.2.0/d9/d29/group__gapi__compile__args.html',1,'']]],
  ['api_20image_20processing_20functionality_67',['G-API Image processing functionality',['https://docs.opencv.org/4.2.0/d2/d00/group__gapi__imgproc.html',1,'']]],
  ['api_20main_20classes_68',['G-API Main Classes',['https://docs.opencv.org/4.2.0/d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['api_20metadata_20descriptors_69',['G-API Metadata Descriptors',['https://docs.opencv.org/4.2.0/d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['api_20opencl_20cl_20va_20interoperability_70',['Intel VA-API/OpenCL (CL-VA) interoperability',['https://docs.opencv.org/4.2.0/d1/daa/group__core__va__intel.html',1,'']]],
  ['api_20standard_20backends_71',['G-API Standard Backends',['https://docs.opencv.org/4.2.0/dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['api_3a_20converting_20image_20from_20one_20color_20space_20to_20another_72',['Graph API: Converting image from one color space to another',['https://docs.opencv.org/4.2.0/dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['api_3a_20image_20and_20channel_20composition_20functions_73',['Graph API: Image and channel composition functions',['https://docs.opencv.org/4.2.0/d6/d91/group__gapi__transform.html',1,'']]],
  ['api_3a_20image_20filters_74',['Graph API: Image filters',['https://docs.opencv.org/4.2.0/da/dc5/group__gapi__filters.html',1,'']]],
  ['api_3a_20math_20operations_75',['Graph API: Math operations',['https://docs.opencv.org/4.2.0/da/dd3/group__gapi__math.html',1,'']]],
  ['api_3a_20operations_20on_20matrices_76',['Graph API: Operations on matrices',['https://docs.opencv.org/4.2.0/d0/d86/group__gapi__matrixop.html',1,'']]],
  ['api_3a_20pixelwise_20operations_77',['Graph API: Pixelwise operations',['https://docs.opencv.org/4.2.0/d1/db2/group__gapi__pixelwise.html',1,'']]],
  ['ar_78',['Ar',['../group__ar.html',1,'']]],
  ['arguments_79',['G-API Graph Compilation Arguments',['https://docs.opencv.org/4.2.0/d9/d29/group__gapi__compile__args.html',1,'']]],
  ['arithm_20operations_20on_20matrices_80',['Arithm Operations on Matrices',['https://docs.opencv.org/4.2.0/d9/d88/group__cudaarithm__arithm.html',1,'']]],
  ['arithmetic_81',['arithmetic',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01520.html',1,'Decimal Floating-Point Arithmetic'],['https://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html',1,'Matrix and vector arithmetic'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01483.html',1,'Rational Arithmetic']]],
  ['arithmetic_20classes_82',['Arithmetic Classes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01506.html',1,'']]],
  ['array_20class_20and_20coefficient_20wise_20operations_83',['The Array class and coefficient-wise operations',['https://eigen.tuxfamily.org/dox/group__TutorialArrayClass.html',1,'']]],
  ['array_20creation_20functions_84',['Array creation functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01523.html',1,'']]],
  ['array_20manipulation_85',['Dense matrix and array manipulation',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__chapter.html',1,'']]],
  ['array_20typedefs_86',['Global array typedefs',['https://eigen.tuxfamily.org/dox/group__arraytypedefs.html',1,'']]],
  ['arrays_87',['arrays',['https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html',1,'Explanation of the assertion on unaligned arrays'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01487.html',1,'Numeric Arrays'],['https://docs.opencv.org/4.2.0/d2/de8/group__core__array.html',1,'Operations on arrays']]],
  ['aruco_20marker_20detection_88',['ArUco Marker Detection',['https://docs.opencv.org/4.2.0/d9/d6a/group__aruco.html',1,'']]],
  ['assertion_20on_20unaligned_20arrays_89',['Explanation of the assertion on unaligned arrays',['https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html',1,'']]],
  ['associative_90',['associative',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01471.html',1,'Associative'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01472.html',1,'Unordered Associative']]],
  ['assumption_20on_20stack_20alignment_91',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['asynchronous_20api_92',['Asynchronous API',['https://docs.opencv.org/4.2.0/da/d57/group__core__async.html',1,'']]],
  ['asynchronous_20c_20c_20converters_93',['Intel IPP Asynchronous C/C++ Converters',['https://docs.opencv.org/4.2.0/d6/dcf/group__core__ipp.html',1,'']]],
  ['atan_20calculation_94',['Atan calculation',['https://docs.opencv.org/4.2.0/d5/df4/group__core__hal__interface__fastAtan.html',1,'']]],
  ['atomics_95',['Atomics',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01494.html',1,'']]],
  ['autocalibration_96',['Autocalibration',['https://docs.opencv.org/4.2.0/d4/dbc/group__stitching__autocalib.html',1,'']]]
];
