var searchData=
[
  ['data_0',['Plot function for Mat data',['https://docs.opencv.org/4.2.0/db/dfe/group__plot.html',1,'']]],
  ['data_20format_20i_20o_20routines_1',['Hierarchical Data Format I/O routines',['https://docs.opencv.org/4.2.0/db/d77/group__hdf.html',1,'']]],
  ['data_20format_20version_205_2',['Hierarchical Data Format version 5',['https://docs.opencv.org/4.2.0/d6/dee/group__hdf5.html',1,'']]],
  ['data_20structure_20type_3',['Data Structure Type',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01539.html',1,'']]],
  ['data_20structures_4',['data structures',['https://docs.opencv.org/4.2.0/d9/d41/group__cudacore__struct.html',1,'Data Structures'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01536.html',1,'Policy-Based Data Structures']]],
  ['data_20types_5',['G-API Data Types',['https://docs.opencv.org/4.2.0/db/df1/group__gapi__data__objects.html',1,'']]],
  ['datasets_6',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['debugging_20of_20computer_20vision_20programs_7',['GUI for Interactive Visual Debugging of Computer Vision Programs',['https://docs.opencv.org/4.2.0/df/dff/group__cvv.html',1,'']]],
  ['decimal_20floating_20point_20arithmetic_8',['Decimal Floating-Point Arithmetic',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01520.html',1,'']]],
  ['decoding_9',['Video Encoding/Decoding',['https://docs.opencv.org/4.2.0/d0/d61/group__cudacodec.html',1,'']]],
  ['decolorization_10',['Contrast Preserving Decolorization',['https://docs.opencv.org/4.2.0/d4/d32/group__photo__decolor.html',1,'']]],
  ['decomposition_11',['decomposition',['https://docs.opencv.org/4.2.0/d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'Cholesky matrix decomposition'],['https://docs.opencv.org/4.2.0/d5/d42/group__core__hal__interface__decomp__lu.html',1,'LU matrix decomposition'],['https://docs.opencv.org/4.2.0/db/d36/group__core__hal__interface__decomp__qr.html',1,'QR matrix decomposition'],['https://docs.opencv.org/4.2.0/dd/d2a/group__core__hal__interface__decomp__svd.html',1,'Singular value matrix decomposition']]],
  ['decompositions_12',['decompositions',['https://eigen.tuxfamily.org/dox/group__DenseDecompositionBenchmark.html',1,'Benchmark of dense decompositions'],['https://eigen.tuxfamily.org/dox/group__TopicLinearAlgebraDecompositions.html',1,'Catalogue of dense decompositions'],['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__chapter.html',1,'Dense linear problems and decompositions'],['https://eigen.tuxfamily.org/dox/group__InplaceDecomposition.html',1,'Inplace matrix decompositions'],['https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html',1,'Linear algebra and decompositions']]],
  ['deep_20neural_20network_20module_13',['Deep Neural Network module',['https://docs.opencv.org/4.2.0/d6/d0f/group__dnn.html',1,'']]],
  ['deformable_20part_20based_20models_14',['Deformable Part-based Models',['https://docs.opencv.org/4.2.0/d9/d12/group__dpm.html',1,'']]],
  ['denoising_15',['Denoising',['https://docs.opencv.org/4.2.0/d1/d79/group__photo__denoise.html',1,'']]],
  ['dense_20decompositions_16',['dense decompositions',['https://eigen.tuxfamily.org/dox/group__DenseDecompositionBenchmark.html',1,'Benchmark of dense decompositions'],['https://eigen.tuxfamily.org/dox/group__TopicLinearAlgebraDecompositions.html',1,'Catalogue of dense decompositions']]],
  ['dense_20linear_20problems_20and_20decompositions_17',['Dense linear problems and decompositions',['https://eigen.tuxfamily.org/dox/group__DenseLinearSolvers__chapter.html',1,'']]],
  ['dense_20matrix_20and_20array_20manipulation_18',['Dense matrix and array manipulation',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__chapter.html',1,'']]],
  ['depth_20processing_19',['RGB-Depth Processing',['https://docs.opencv.org/4.2.0/d2/d3a/group__rgbd.html',1,'']]],
  ['derivated_20tools_20',['Biologically inspired vision models and derivated tools',['https://docs.opencv.org/4.2.0/dd/deb/group__bioinspired.html',1,'']]],
  ['description_21',['description',['https://docs.opencv.org/4.2.0/d5/d51/group__features2d__main.html',1,'Feature Detection and Description'],['https://docs.opencv.org/4.2.0/d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description']]],
  ['descriptor_20matchers_22',['Descriptor Matchers',['https://docs.opencv.org/4.2.0/d8/d9b/group__features2d__match.html',1,'']]],
  ['descriptors_23',['descriptors',['https://docs.opencv.org/4.2.0/dd/ddc/group__ximgproc__fourier.html',1,'Fourier descriptors'],['https://docs.opencv.org/4.2.0/d3/d0c/group__gapi__meta__args.html',1,'G-API Metadata Descriptors'],['https://docs.opencv.org/4.2.0/d3/dc0/group__imgproc__shape.html',1,'Structural Analysis and Shape Descriptors']]],
  ['descriptors_20for_20lines_20extracted_20from_20an_20image_24',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]],
  ['detection_25',['detection',['https://docs.opencv.org/4.2.0/d9/d6a/group__aruco.html',1,'ArUco Marker Detection'],['https://docs.opencv.org/4.2.0/d5/df6/group__dnn__objdetect.html',1,'DNN used for object detection'],['https://docs.opencv.org/4.2.0/d4/d54/group__xobjdetect.html',1,'Extended object detection'],['https://docs.opencv.org/4.2.0/dc/d6d/group__cudaimgproc__feature.html',1,'Feature Detection'],['https://docs.opencv.org/4.2.0/dd/d1a/group__imgproc__feature.html',1,'Feature Detection'],['https://docs.opencv.org/4.2.0/d9/d3f/group__cudaobjdetect.html',1,'Object Detection'],['https://docs.opencv.org/4.2.0/d5/d54/group__objdetect.html',1,'Object Detection'],['https://docs.opencv.org/4.2.0/df/dfb/group__imgproc__object.html',1,'Object Detection'],['https://docs.opencv.org/4.2.0/d8/db1/group__datasets__pd.html',1,'Pedestrian Detection'],['https://docs.opencv.org/4.2.0/da/d56/group__text__detect.html',1,'Scene Text Detection'],['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'Structured forests for fast edge detection']]],
  ['detection_20and_20description_26',['detection and description',['https://docs.opencv.org/4.2.0/d6/d1d/group__cudafeatures2d.html',1,'Feature Detection and Description'],['https://docs.opencv.org/4.2.0/d5/d51/group__features2d__main.html',1,'Feature Detection and Description']]],
  ['detection_20and_20recognition_27',['Scene Text Detection and Recognition',['https://docs.opencv.org/4.2.0/d4/d61/group__text.html',1,'']]],
  ['detector_28',['Fast line detector',['https://docs.opencv.org/4.2.0/df/ded/group__ximgproc__fast__line__detector.html',1,'']]],
  ['device_20layer_29',['Device layer',['https://docs.opencv.org/4.2.0/df/dfc/group__cudev.html',1,'']]],
  ['diagnostics_30',['Diagnostics',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01473.html',1,'']]],
  ['difference_31',['Element-wise absolute difference',['https://docs.opencv.org/4.2.0/d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['different_20datasets_32',['Framework for working with different datasets',['https://docs.opencv.org/4.2.0/d8/d00/group__datasets.html',1,'']]],
  ['different_20image_20hashing_20algorithms_33',['The module brings implementations of different image hashing algorithms.',['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'']]],
  ['dimensional_20spaces_34',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['directx_20interoperability_35',['DirectX interoperability',['https://docs.opencv.org/4.2.0/de/dc1/group__core__directx.html',1,'']]],
  ['distance_20and_20matching_36',['Shape Distance and Matching',['https://docs.opencv.org/4.2.0/d1/d85/group__shape.html',1,'']]],
  ['distributions_37',['distributions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01545.html',1,'Bernoulli Distributions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01544.html',1,'Normal Distributions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01546.html',1,'Poisson Distributions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01542.html',1,'Random Number Distributions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01543.html',1,'Uniform Distributions']]],
  ['divide_38',['Element-wise divide',['https://docs.opencv.org/4.2.0/dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['dnn_20used_20for_20object_20detection_39',['DNN used for object detection',['https://docs.opencv.org/4.2.0/d5/df6/group__dnn__objdetect.html',1,'']]],
  ['dnn_20used_20for_20super_20resolution_40',['DNN used for super resolution',['https://docs.opencv.org/4.2.0/d9/de0/group__dnn__superres.html',1,'']]],
  ['drawing_20and_20composition_20functionality_41',['G-API Drawing and composition functionality',['https://docs.opencv.org/4.2.0/df/de4/group__gapi__draw.html',1,'']]],
  ['drawing_20function_20of_20keypoints_20and_20matches_42',['Drawing Function of Keypoints and Matches',['https://docs.opencv.org/4.2.0/d4/d5d/group__features2d__draw.html',1,'']]],
  ['drawing_20functions_43',['Drawing Functions',['https://docs.opencv.org/4.2.0/d6/d6e/group__imgproc__draw.html',1,'']]],
  ['drawing_20operations_20and_20functions_44',['Drawing operations and functions',['https://docs.opencv.org/4.2.0/d0/d43/group__gapi__draw__api.html',1,'']]],
  ['drawing_20primitives_45',['Drawing primitives',['https://docs.opencv.org/4.2.0/de/db8/group__gapi__draw__prims.html',1,'']]],
  ['drawing_20utf_208_20strings_20with_20freetype_20harfbuzz_46',['Drawing UTF-8 strings with freetype/harfbuzz',['https://docs.opencv.org/4.2.0/d4/dfc/group__freetype.html',1,'']]],
  ['dynamic_20bitset_47',['Dynamic Bitset.',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01519.html',1,'']]]
];
