var searchData=
[
  ['edge_20detection_0',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/de/d51/group__ximgproc__edge.html',1,'']]],
  ['edgeboxes_1',['EdgeBoxes',['https://docs.opencv.org/4.2.0/d4/d0d/group__ximgproc__edgeboxes.html',1,'']]],
  ['efficient_20image_20segmentation_2',['Hierarchical Feature Selection for Efficient Image Segmentation',['https://docs.opencv.org/4.2.0/dc/d29/group__hfs.html',1,'']]],
  ['eigen_3',['Using STL Containers with Eigen',['https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html',1,'']]],
  ['eigen_20members_4',['Structures Having Eigen Members',['https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html',1,'']]],
  ['eigen_20objects_5',['Fixed-size vectorizable Eigen objects',['https://eigen.tuxfamily.org/dox/group__TopicFixedSizeVectorizable.html',1,'']]],
  ['eigen_20objects_20by_20value_20to_20functions_6',['Passing Eigen objects by value to functions',['https://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html',1,'']]],
  ['eigen_20support_7',['Eigen support',['https://docs.opencv.org/4.2.0/d0/daf/group__core__eigen.html',1,'']]],
  ['eigenvalues_20module_8',['Eigenvalues module',['https://eigen.tuxfamily.org/dox/group__Eigenvalues__Module.html',1,'']]],
  ['element_20operations_9',['Per-element Operations',['https://docs.opencv.org/4.2.0/d8/d34/group__cudaarithm__elem.html',1,'']]],
  ['element_20wise_20absolute_20difference_10',['Element-wise absolute difference',['https://docs.opencv.org/4.2.0/d5/dec/group__core__hal__interface__absdiff.html',1,'']]],
  ['element_20wise_20add_20and_20subtract_11',['Element-wise add and subtract',['https://docs.opencv.org/4.2.0/d8/d6f/group__core__hal__interface__addsub.html',1,'']]],
  ['element_20wise_20compare_12',['Element-wise compare',['https://docs.opencv.org/4.2.0/d6/dab/group__core__hal__interface__compare.html',1,'']]],
  ['element_20wise_20divide_13',['Element-wise divide',['https://docs.opencv.org/4.2.0/dd/d2c/group__core__hal__interface__divide.html',1,'']]],
  ['element_20wise_20minimum_20or_20maximum_14',['Element-wise minimum or maximum',['https://docs.opencv.org/4.2.0/dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['element_20wise_20multiply_15',['Element-wise multiply',['https://docs.opencv.org/4.2.0/de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['element_20wise_20reciprocial_16',['Element-wise reciprocial',['https://docs.opencv.org/4.2.0/d4/de4/group__core__hal__interface__reciprocial.html',1,'']]],
  ['element_20wise_20weighted_20sum_17',['Element-wise weighted sum',['https://docs.opencv.org/4.2.0/da/d9b/group__core__hal__interface__addWeighted.html',1,'']]],
  ['encoded_20image_18',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['encoding_20decoding_19',['Video Encoding/Decoding',['https://docs.opencv.org/4.2.0/d0/d61/group__cudacodec.html',1,'']]],
  ['enumerations_20',['Enumerations',['https://eigen.tuxfamily.org/dox/group__enums.html',1,'']]],
  ['estimation_21',['estimation',['https://docs.opencv.org/4.2.0/d4/d2c/group__videostab__motion.html',1,'Global Motion Estimation'],['https://docs.opencv.org/4.2.0/d9/de0/group__datasets__hpe.html',1,'Human Pose Estimation'],['https://docs.opencv.org/4.2.0/db/d3a/group__robust.html',1,'Robust Estimation'],['https://docs.opencv.org/4.2.0/d7/d74/group__stitching__rotation.html',1,'Rotation Estimation'],['https://docs.opencv.org/4.2.0/d9/d24/group__stitching__seam.html',1,'Seam Estimation']]],
  ['estimation_20api_22',['3D object recognition and pose estimation API',['https://docs.opencv.org/4.2.0/d9/d02/group__cnn__3dobj.html',1,'']]],
  ['exceptions_23',['exceptions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01533.html',1,'Exceptions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01495.html',1,'Exceptions']]],
  ['experimental_24',['Experimental',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01524.html',1,'']]],
  ['experimental_202d_20features_20algorithms_25',['Experimental 2D Features Algorithms',['https://docs.opencv.org/4.2.0/d7/d7a/group__xfeatures2d__experiment.html',1,'']]],
  ['experimental_202d_20features_20matching_20algorithm_26',['Experimental 2D Features Matching Algorithm',['https://docs.opencv.org/4.2.0/db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['explanation_20of_20the_20assertion_20on_20unaligned_20arrays_27',['Explanation of the assertion on unaligned arrays',['https://eigen.tuxfamily.org/dox/group__TopicUnalignedArrayAssert.html',1,'']]],
  ['exponent_20calculation_28',['Exponent calculation',['https://docs.opencv.org/4.2.0/d4/d8a/group__core__hal__interface__exp.html',1,'']]],
  ['exposure_20compensation_29',['Exposure Compensation',['https://docs.opencv.org/4.2.0/dd/dff/group__stitching__exposure.html',1,'']]],
  ['expressions_30',['Regular Expressions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01502.html',1,'']]],
  ['extended_20image_20processing_31',['Extended Image Processing',['https://docs.opencv.org/4.2.0/df/d2d/group__ximgproc.html',1,'']]],
  ['extended_20object_20detection_32',['Extended object detection',['https://docs.opencv.org/4.2.0/d4/d54/group__xobjdetect.html',1,'']]],
  ['extensions_33',['Extensions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01467.html',1,'']]],
  ['external_20libraries_20plugins_34',['Low-level API for external libraries / plugins',['https://docs.opencv.org/4.2.0/da/dd2/group__core__lowlevel__api.html',1,'']]],
  ['extra_202d_20features_20framework_35',['Extra 2D Features Framework',['https://docs.opencv.org/4.2.0/d1/db4/group__xfeatures2d.html',1,'']]],
  ['extracted_20from_20an_20image_36',['Binary descriptors for lines extracted from an image',['https://docs.opencv.org/4.2.0/dc/ddd/group__line__descriptor.html',1,'']]]
];
