var searchData=
[
  ['machine_20learning_0',['Machine Learning',['https://docs.opencv.org/4.2.0/dd/ded/group__ml.html',1,'']]],
  ['macros_1',['Utility and system functions and macros',['https://docs.opencv.org/4.2.0/db/de0/group__core__utils.html',1,'']]],
  ['magnitude_20calculation_2',['Magnitude calculation',['https://docs.opencv.org/4.2.0/d7/d99/group__core__hal__interface__magnitude.html',1,'']]],
  ['main_20classes_3',['G-API Main Classes',['https://docs.opencv.org/4.2.0/d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['making_20a_20wrong_20assumption_20on_20stack_20alignment_4',['Compiler making a wrong assumption on stack alignment',['https://eigen.tuxfamily.org/dox/group__TopicWrongStackAlignment.html',1,'']]],
  ['manipulation_5',['Dense matrix and array manipulation',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__chapter.html',1,'']]],
  ['manipulations_6',['Sparse matrix manipulations',['https://eigen.tuxfamily.org/dox/group__TutorialSparse.html',1,'']]],
  ['map_20class_7',['Interfacing with raw buffers: the Map class',['https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html',1,'']]],
  ['marching_20method_8',['Fast Marching Method',['https://docs.opencv.org/4.2.0/db/d18/group__videostab__marching.html',1,'']]],
  ['marker_20detection_9',['ArUco Marker Detection',['https://docs.opencv.org/4.2.0/d9/d6a/group__aruco.html',1,'']]],
  ['mat_20data_10',['Plot function for Mat data',['https://docs.opencv.org/4.2.0/db/dfe/group__plot.html',1,'']]],
  ['matchers_11',['Descriptor Matchers',['https://docs.opencv.org/4.2.0/d8/d9b/group__features2d__match.html',1,'']]],
  ['matches_12',['Drawing Function of Keypoints and Matches',['https://docs.opencv.org/4.2.0/d4/d5d/group__features2d__draw.html',1,'']]],
  ['matching_13',['matching',['https://docs.opencv.org/4.2.0/df/d8c/group__stitching__match.html',1,'Features Finding and Images Matching'],['https://docs.opencv.org/4.2.0/d7/dd5/group__datasets__msm.html',1,'Multiview Stereo Matching'],['https://docs.opencv.org/4.2.0/d1/d85/group__shape.html',1,'Shape Distance and Matching'],['https://docs.opencv.org/4.2.0/d9/d25/group__surface__matching.html',1,'Surface Matching']]],
  ['matching_20algorithm_14',['Experimental 2D Features Matching Algorithm',['https://docs.opencv.org/4.2.0/db/dd9/group__xfeatures2d__match.html',1,'']]],
  ['math_20functions_15',['Catalog of coefficient-wise math functions',['https://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html',1,'']]],
  ['math_20operations_16',['Graph API: Math operations',['https://docs.opencv.org/4.2.0/da/dd3/group__gapi__math.html',1,'']]],
  ['math_20with_20f0_20transform_20support_17',['Math with F0-transform support',['https://docs.opencv.org/4.2.0/d5/d8e/group__f0__math.html',1,'']]],
  ['math_20with_20f1_20transform_20support_18',['Math with F1-transform support',['https://docs.opencv.org/4.2.0/d6/df0/group__f1__math.html',1,'']]],
  ['mathematical_20special_20functions_19',['mathematical special functions',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01503.html',1,'Mathematical Special Functions'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01518.html',1,'Mathematical Special Functions']]],
  ['mathematics_20',['Image processing based on fuzzy mathematics',['https://docs.opencv.org/4.2.0/df/d5b/group__fuzzy.html',1,'']]],
  ['matrices_21',['matrices',['https://docs.opencv.org/4.2.0/d9/d88/group__cudaarithm__arithm.html',1,'Arithm Operations on Matrices'],['https://docs.opencv.org/4.2.0/de/d09/group__cudaarithm__core.html',1,'Core Operations on Matrices'],['https://docs.opencv.org/4.2.0/d0/d86/group__gapi__matrixop.html',1,'Graph API: Operations on matrices'],['https://docs.opencv.org/4.2.0/d5/d8e/group__cudaarithm.html',1,'Operations on Matrices'],['https://eigen.tuxfamily.org/dox/group__SparseQuickRefPage.html',1,'Quick reference guide for sparse matrices']]],
  ['matrix_20and_20array_20manipulation_22',['Dense matrix and array manipulation',['https://eigen.tuxfamily.org/dox/group__DenseMatrixManipulation__chapter.html',1,'']]],
  ['matrix_20and_20vector_20arithmetic_23',['Matrix and vector arithmetic',['https://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html',1,'']]],
  ['matrix_20class_24',['The Matrix class',['https://eigen.tuxfamily.org/dox/group__TutorialMatrixClass.html',1,'']]],
  ['matrix_20decomposition_25',['matrix decomposition',['https://docs.opencv.org/4.2.0/d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'Cholesky matrix decomposition'],['https://docs.opencv.org/4.2.0/d5/d42/group__core__hal__interface__decomp__lu.html',1,'LU matrix decomposition'],['https://docs.opencv.org/4.2.0/db/d36/group__core__hal__interface__decomp__qr.html',1,'QR matrix decomposition'],['https://docs.opencv.org/4.2.0/dd/d2a/group__core__hal__interface__decomp__svd.html',1,'Singular value matrix decomposition']]],
  ['matrix_20decompositions_26',['Inplace matrix decompositions',['https://eigen.tuxfamily.org/dox/group__InplaceDecomposition.html',1,'']]],
  ['matrix_20free_20solvers_27',['Matrix-free solvers',['https://eigen.tuxfamily.org/dox/group__MatrixfreeSolverExample.html',1,'']]],
  ['matrix_20manipulations_28',['Sparse matrix manipulations',['https://eigen.tuxfamily.org/dox/group__TutorialSparse.html',1,'']]],
  ['matrix_20multiplication_29',['Matrix multiplication',['https://docs.opencv.org/4.2.0/d2/dab/group__core__hal__interface__matrix__multiplication.html',1,'']]],
  ['matrix_20reductions_30',['Matrix Reductions',['https://docs.opencv.org/4.2.0/d5/de6/group__cudaarithm__reduce.html',1,'']]],
  ['matrix_20typedefs_31',['Global matrix typedefs',['https://eigen.tuxfamily.org/dox/group__matrixtypedefs.html',1,'']]],
  ['maximum_32',['Element-wise minimum or maximum',['https://docs.opencv.org/4.2.0/dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['members_33',['members',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01511.html',1,'Adaptors for pointers to members'],['https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html',1,'Structures Having Eigen Members']]],
  ['memory_34',['Memory',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01480.html',1,'']]],
  ['merge_35',['Channel merge',['https://docs.opencv.org/4.2.0/df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['meta_20module_36',['Sparse meta-module',['https://eigen.tuxfamily.org/dox/group__Sparse__Module.html',1,'']]],
  ['metadata_20descriptors_37',['G-API Metadata Descriptors',['https://docs.opencv.org/4.2.0/d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['metaprogramming_38',['Metaprogramming',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01485.html',1,'']]],
  ['method_39',['Fast Marching Method',['https://docs.opencv.org/4.2.0/db/d18/group__videostab__marching.html',1,'']]],
  ['methods_40',['Improved Background-Foreground Segmentation Methods',['https://docs.opencv.org/4.2.0/d2/d55/group__bgsegm.html',1,'']]],
  ['metissupport_20module_41',['MetisSupport module',['https://eigen.tuxfamily.org/dox/group__MetisSupport__Module.html',1,'']]],
  ['minimum_20or_20maximum_42',['Element-wise minimum or maximum',['https://docs.opencv.org/4.2.0/dc/d19/group__core__hal__interface__minmax.html',1,'']]],
  ['miscellaneous_20image_20transformations_43',['Miscellaneous Image Transformations',['https://docs.opencv.org/4.2.0/d7/d1b/group__imgproc__misc.html',1,'']]],
  ['model_44',['Fisheye camera model',['https://docs.opencv.org/4.2.0/db/d58/group__calib3d__fisheye.html',1,'']]],
  ['models_45',['Deformable Part-based Models',['https://docs.opencv.org/4.2.0/d9/d12/group__dpm.html',1,'']]],
  ['models_20and_20derivated_20tools_46',['Biologically inspired vision models and derivated tools',['https://docs.opencv.org/4.2.0/dd/deb/group__bioinspired.html',1,'']]],
  ['module_47',['module',['https://eigen.tuxfamily.org/dox/group__Cholesky__Module.html',1,'Cholesky module'],['https://eigen.tuxfamily.org/dox/group__CholmodSupport__Module.html',1,'CholmodSupport module'],['https://eigen.tuxfamily.org/dox/group__Core__Module.html',1,'Core module'],['https://docs.opencv.org/4.2.0/d6/d0f/group__dnn.html',1,'Deep Neural Network module'],['https://eigen.tuxfamily.org/dox/group__Eigenvalues__Module.html',1,'Eigenvalues module'],['https://eigen.tuxfamily.org/dox/group__Geometry__Module.html',1,'Geometry module'],['https://eigen.tuxfamily.org/dox/group__Householder__Module.html',1,'Householder module'],['https://eigen.tuxfamily.org/dox/group__IterativeLinearSolvers__Module.html',1,'IterativeLinearSolvers module'],['https://eigen.tuxfamily.org/dox/group__Jacobi__Module.html',1,'Jacobi module'],['https://eigen.tuxfamily.org/dox/group__KLUSupport__Module.html',1,'KLUSupport module'],['https://eigen.tuxfamily.org/dox/group__LU__Module.html',1,'LU module'],['https://eigen.tuxfamily.org/dox/group__MetisSupport__Module.html',1,'MetisSupport module'],['https://eigen.tuxfamily.org/dox/group__OrderingMethods__Module.html',1,'OrderingMethods module'],['https://eigen.tuxfamily.org/dox/group__PardisoSupport__Module.html',1,'PardisoSupport module'],['https://eigen.tuxfamily.org/dox/group__PaStiXSupport__Module.html',1,'PaStiXSupport module'],['https://eigen.tuxfamily.org/dox/group__QR__Module.html',1,'QR module'],['https://eigen.tuxfamily.org/dox/group__Sparse__Module.html',1,'Sparse meta-module'],['https://eigen.tuxfamily.org/dox/group__SparseCholesky__Module.html',1,'SparseCholesky module'],['https://eigen.tuxfamily.org/dox/group__SparseCore__Module.html',1,'SparseCore module'],['https://eigen.tuxfamily.org/dox/group__SparseLU__Module.html',1,'SparseLU module'],['https://eigen.tuxfamily.org/dox/group__SparseQR__Module.html',1,'SparseQR module'],['https://eigen.tuxfamily.org/dox/group__SPQRSupport__Module.html',1,'SuiteSparseQR module'],['https://eigen.tuxfamily.org/dox/group__SuperLUSupport__Module.html',1,'SuperLUSupport module'],['https://eigen.tuxfamily.org/dox/group__SVD__Module.html',1,'SVD module'],['https://eigen.tuxfamily.org/dox/group__UmfPackSupport__Module.html',1,'UmfPackSupport module']]],
  ['module_20brings_20implementations_20of_20different_20image_20hashing_20algorithms_48',['The module brings implementations of different image hashing algorithms.',['https://docs.opencv.org/4.2.0/d4/d93/group__img__hash.html',1,'']]],
  ['modules_49',['Support modules',['https://eigen.tuxfamily.org/dox/group__Support__modules.html',1,'']]],
  ['morphology_20on_20run_20length_20encoded_20image_50',['Binary morphology on run-length encoded image',['https://docs.opencv.org/4.2.0/df/def/group__ximgproc__run__length__morphology.html',1,'']]],
  ['motion_51',['Structure From Motion',['https://docs.opencv.org/4.2.0/d8/d8c/group__sfm.html',1,'']]],
  ['motion_20analysis_52',['Motion Analysis',['https://docs.opencv.org/4.2.0/de/de1/group__video__motion.html',1,'']]],
  ['motion_20analysis_20and_20object_20tracking_53',['Motion Analysis and Object Tracking',['https://docs.opencv.org/4.2.0/d7/df3/group__imgproc__motion.html',1,'']]],
  ['motion_20estimation_54',['Global Motion Estimation',['https://docs.opencv.org/4.2.0/d4/d2c/group__videostab__motion.html',1,'']]],
  ['multi_20dimensional_20spaces_55',['Clustering and Search in Multi-Dimensional Spaces',['https://docs.opencv.org/4.2.0/dc/de5/group__flann.html',1,'']]],
  ['multiplication_56',['Matrix multiplication',['https://docs.opencv.org/4.2.0/d2/dab/group__core__hal__interface__matrix__multiplication.html',1,'']]],
  ['multiply_57',['Element-wise multiply',['https://docs.opencv.org/4.2.0/de/db7/group__core__hal__interface__multiply.html',1,'']]],
  ['multiview_20stereo_20matching_58',['Multiview Stereo Matching',['https://docs.opencv.org/4.2.0/d7/dd5/group__datasets__msm.html',1,'']]],
  ['mutating_59',['mutating',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01489.html',1,'Mutating'],['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01490.html',1,'Non-Mutating']]],
  ['mutexes_60',['Mutexes',['https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libstdc++/api/a01504.html',1,'']]]
];
