var searchData=
[
  ['haar_20cascades_0',['haar cascades',['https://docs.opencv.org/4.2.0/d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades'],['https://docs.opencv.org/4.2.0/d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['halide_20backend_1',['How to schedule your network for Halide backend',['https://docs.opencv.org/4.2.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['halide_20backend_20for_20improve_20efficiency_2',['How to enable Halide backend for improve efficiency',['https://docs.opencv.org/4.2.0/de/d37/tutorial_dnn_halide.html',1,'']]],
  ['hand_20written_20data_20using_20knn_3',['OCR of Hand-written Data using kNN',['https://docs.opencv.org/4.2.0/d8/d4b/tutorial_py_knn_opencv.html',1,'']]],
  ['hand_20written_20data_20using_20svm_4',['OCR of Hand-written Data using SVM',['https://docs.opencv.org/4.2.0/dd/d3b/tutorial_py_svm_opencv.html',1,'']]],
  ['happens_20inside_20eigen_20on_20a_20simple_20example_5',['What happens inside Eigen, on a simple example',['https://eigen.tuxfamily.org/dox/TopicInsideEigenExample.html',1,'']]],
  ['harris_20corner_20detection_6',['Harris Corner Detection',['https://docs.opencv.org/4.2.0/dc/d0d/tutorial_py_features_harris.html',1,'']]],
  ['harris_20corner_20detector_7',['Harris corner detector',['https://docs.opencv.org/4.2.0/d4/d7d/tutorial_harris_detector.html',1,'']]],
  ['hdf_20i_20o_8',['The Hierarchical Data Format (hdf) I/O',['https://docs.opencv.org/4.2.0/d3/d00/tutorial_table_of_content_hdf.html',1,'']]],
  ['hdr_9',['High Dynamic Range (HDR)',['https://docs.opencv.org/4.2.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['hello_10',['OpenCV iOS Hello',['https://docs.opencv.org/4.2.0/d7/d88/tutorial_hello.html',1,'']]],
  ['hierarchical_20data_20format_20hdf_20i_20o_11',['The Hierarchical Data Format (hdf) I/O',['https://docs.opencv.org/4.2.0/d3/d00/tutorial_table_of_content_hdf.html',1,'']]],
  ['hierarchy_12',['hierarchy',['https://docs.opencv.org/4.2.0/da/d0a/tutorial_js_contours_hierarchy.html',1,'Contours Hierarchy'],['https://docs.opencv.org/4.2.0/d9/d8b/tutorial_py_contours_hierarchy.html',1,'Contours Hierarchy'],['https://eigen.tuxfamily.org/dox/TopicClassHierarchy.html',1,'The class hierarchy']]],
  ['high_20dynamic_20range_20hdr_13',['High Dynamic Range (HDR)',['https://docs.opencv.org/4.2.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['high_20dynamic_20range_20imaging_14',['High Dynamic Range Imaging',['https://docs.opencv.org/4.2.0/d3/db7/tutorial_hdr_imaging.html',1,'']]],
  ['high_20level_20design_20overview_15',['High-level design overview',['https://docs.opencv.org/4.2.0/de/d4d/gapi_hld.html',1,'']]],
  ['high_20level_20gui_20and_20media_20highgui_20module_16',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['high_20level_20stitching_20api_20stitcher_20class_17',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['highgui_20module_18',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['histogram_19',['Creating a 3D histogram',['https://docs.opencv.org/4.2.0/d1/d1d/tutorial_histo3D.html',1,'']]],
  ['histogram_203_20_3a_20histogram_20backprojection_20',['Histogram - 3 : Histogram Backprojection',['https://docs.opencv.org/4.2.0/dd/d4d/tutorial_js_histogram_backprojection.html',1,'']]],
  ['histogram_204_20_3a_20histogram_20backprojection_21',['Histogram - 4 : Histogram Backprojection',['https://docs.opencv.org/4.2.0/dc/df6/tutorial_py_histogram_backprojection.html',1,'']]],
  ['histogram_20calculation_22',['Histogram Calculation',['https://docs.opencv.org/4.2.0/d8/dbc/tutorial_histogram_calculation.html',1,'']]],
  ['histogram_20comparison_23',['Histogram Comparison',['https://docs.opencv.org/4.2.0/d8/dc8/tutorial_histogram_comparison.html',1,'']]],
  ['histogram_20equalization_24',['histogram equalization',['https://docs.opencv.org/4.2.0/d4/d1b/tutorial_histogram_equalization.html',1,'Histogram Equalization'],['https://docs.opencv.org/4.2.0/d2/d74/tutorial_js_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization'],['https://docs.opencv.org/4.2.0/d5/daf/tutorial_py_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization']]],
  ['histograms_201_20_3a_20find_20plot_20analyze_25',['histograms 1 : find plot analyze',['https://docs.opencv.org/4.2.0/d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['https://docs.opencv.org/4.2.0/d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['histograms_202_3a_20histogram_20equalization_26',['histograms 2: histogram equalization',['https://docs.opencv.org/4.2.0/d2/d74/tutorial_js_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization'],['https://docs.opencv.org/4.2.0/d5/daf/tutorial_py_histogram_equalization.html',1,'Histograms - 2: Histogram Equalization']]],
  ['histograms_203_20_3a_202d_20histograms_27',['Histograms - 3 : 2D Histograms',['https://docs.opencv.org/4.2.0/dd/d0d/tutorial_py_2d_histogram.html',1,'']]],
  ['histograms_20in_20opencv_28',['Histograms in OpenCV',['https://docs.opencv.org/4.2.0/de/db2/tutorial_py_table_of_contents_histograms.html',1,'']]],
  ['histograms_20in_20opencv_20js_29',['Histograms in OpenCV.js',['https://docs.opencv.org/4.2.0/d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'']]],
  ['hit_20or_20miss_30',['Hit-or-Miss',['https://docs.opencv.org/4.2.0/db/d06/tutorial_hitOrMiss.html',1,'']]],
  ['homography_20explained_20with_20code_31',['Basic concepts of the homography explained with code',['https://docs.opencv.org/4.2.0/d9/dab/tutorial_homography.html',1,'']]],
  ['homography_20to_20find_20a_20known_20object_32',['Features2D + Homography to find a known object',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_feature_homography.html',1,'']]],
  ['homography_20to_20find_20objects_33',['Feature Matching + Homography to find Objects',['https://docs.opencv.org/4.2.0/d1/de0/tutorial_py_feature_homography.html',1,'']]],
  ['horizontal_20and_20vertical_20lines_20by_20using_20morphological_20operations_34',['Extract horizontal and vertical lines by using morphological operations',['https://docs.opencv.org/4.2.0/dd/dd7/tutorial_morph_lines_detection.html',1,'']]],
  ['hough_20circle_20transform_35',['hough circle transform',['https://docs.opencv.org/4.2.0/da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform']]],
  ['hough_20line_20transform_36',['hough line transform',['https://docs.opencv.org/4.2.0/d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform']]],
  ['how_20opencv_20python_20bindings_20works_37',['How OpenCV-Python Bindings Works?',['https://docs.opencv.org/4.2.0/da/d49/tutorial_py_bindings_basics.html',1,'']]],
  ['how_20to_20build_20applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_38',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['how_20to_20enable_20halide_20backend_20for_20improve_20efficiency_39',['How to enable Halide backend for improve efficiency',['https://docs.opencv.org/4.2.0/de/d37/tutorial_dnn_halide.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20in_20browser_40',['How to run deep networks in browser',['https://docs.opencv.org/4.2.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20on_20android_20device_41',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['how_20to_20scan_20images_20lookup_20tables_20and_20time_20measurement_20with_20opencv_42',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['how_20to_20schedule_20your_20network_20for_20halide_20backend_43',['How to schedule your network for Halide backend',['https://docs.opencv.org/4.2.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['how_20to_20use_20background_20subtraction_20methods_44',['How to Use Background Subtraction Methods',['https://docs.opencv.org/4.2.0/d1/dc5/tutorial_background_subtraction.html',1,'']]],
  ['how_20to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_45',['How to use the OpenCV parallel_for_ to parallelize your code',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'']]],
  ['hull_46',['Convex Hull',['https://docs.opencv.org/4.2.0/d7/d1d/tutorial_hull.html',1,'']]],
  ['human_20retina_20and_20its_20use_20for_20image_20processing_47',['Discovering the human retina and its use for image processing',['https://docs.opencv.org/4.2.0/df/dee/tutorial_table_of_content_retina.html',1,'']]]
];
