var searchData=
[
  ['tables_20and_20time_20measurement_20with_20opencv_0',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['taking_20eigen_20types_20as_20parameters_1',['Writing Functions Taking Eigen Types as Parameters',['https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html',1,'']]],
  ['techniques_2',['Performance Measurement and Improvement Techniques',['https://docs.opencv.org/4.2.0/dc/d71/tutorial_py_optimization.html',1,'']]],
  ['tegra_20with_20cuda_3',['Building OpenCV for Tegra with CUDA',['https://docs.opencv.org/4.2.0/d6/d15/tutorial_building_tegra_cuda.html',1,'']]],
  ['template_20and_20typename_20keywords_20in_20c_4',['The template and typename keywords in C++',['https://eigen.tuxfamily.org/dox/TopicTemplateKeyword.html',1,'']]],
  ['template_20matching_5',['template matching',['https://docs.opencv.org/4.2.0/d8/dd1/tutorial_js_template_matching.html',1,'Template Matching'],['https://docs.opencv.org/4.2.0/d4/dc6/tutorial_py_template_matching.html',1,'Template Matching'],['https://docs.opencv.org/4.2.0/de/da9/tutorial_template_matching.html',1,'Template Matching']]],
  ['template_20parameter_20file_6',['Exporting a template parameter file',['https://docs.opencv.org/4.2.0/df/dc0/tutorial_qds_export_parameters.html',1,'']]],
  ['templates_20in_20eigen_7',['Expression templates in Eigen',['https://eigen.tuxfamily.org/dox/TopicEigenExpressionTemplates.html',1,'']]],
  ['tensor_8',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['tesseract_20master_20installation_20by_20using_20git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_9',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['https://docs.opencv.org/4.2.0/db/d4c/tutorial_install_tesseract.html',1,'']]],
  ['test_10',['Point Polygon Test',['https://docs.opencv.org/4.2.0/dc/d48/tutorial_point_polygon_test.html',1,'']]],
  ['text_20module_11',['Text module',['https://docs.opencv.org/4.2.0/d0/dda/tutorial_table_of_content_text.html',1,'']]],
  ['text_20with_20opencv_12',['Random generator and text with OpenCV',['https://docs.opencv.org/4.2.0/df/d61/tutorial_random_generator_and_text.html',1,'']]],
  ['textured_20object_13',['Real Time pose estimation of a textured object',['https://docs.opencv.org/4.2.0/dc/d2c/tutorial_real_time_pose.html',1,'']]],
  ['the_20basic_20image_20container_14',['Mat - The Basic Image Container',['https://docs.opencv.org/4.2.0/d6/d6d/tutorial_mat_the_basic_image_container.html',1,'']]],
  ['the_20class_20hierarchy_15',['The class hierarchy',['https://eigen.tuxfamily.org/dox/TopicClassHierarchy.html',1,'']]],
  ['the_20cn_20tracker_16',['Customizing the CN Tracker',['https://docs.opencv.org/4.2.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'']]],
  ['the_20color_20palette_17',['Trackbar as the Color Palette',['https://docs.opencv.org/4.2.0/d9/dc8/tutorial_py_trackbar.html',1,'']]],
  ['the_20contrast_20and_20brightness_20of_20an_20image_18',['Changing the contrast and brightness of an image!',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['the_20core_20functionality_20core_20module_19',['The Core Functionality (core module)',['https://docs.opencv.org/4.2.0/de/d7a/tutorial_table_of_content_core.html',1,'']]],
  ['the_20facemark_20api_20',['the facemark api',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'Adding a new algorithm to the Facemark API'],['https://docs.opencv.org/4.2.0/d7/dec/tutorial_facemark_usage.html',1,'Using the Facemark API']]],
  ['the_20facemarkaam_21',['Using the FacemarkAAM',['https://docs.opencv.org/4.2.0/d5/dd8/tutorial_facemark_aam.html',1,'']]],
  ['the_20gpu_22',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['the_20hierarchical_20data_20format_20hdf_20i_20o_23',['The Hierarchical Data Format (hdf) I/O',['https://docs.opencv.org/4.2.0/d3/d00/tutorial_table_of_content_hdf.html',1,'']]],
  ['the_20homography_20explained_20with_20code_24',['Basic concepts of the homography explained with code',['https://docs.opencv.org/4.2.0/d9/dab/tutorial_homography.html',1,'']]],
  ['the_20human_20retina_20and_20its_20use_20for_20image_20processing_25',['Discovering the human retina and its use for image processing',['https://docs.opencv.org/4.2.0/df/dee/tutorial_table_of_content_retina.html',1,'']]],
  ['the_20learning_20based_20white_20balance_20algorithm_26',['Training the learning-based white balance algorithm',['https://docs.opencv.org/4.2.0/dc/dcb/tutorial_xphoto_training_white_balance.html',1,'']]],
  ['the_20microsoft_20visual_20studio_27',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_28',['How to use the OpenCV parallel_for_ to parallelize your code',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'']]],
  ['the_20template_20and_20typename_20keywords_20in_20c_29',['The template and typename keywords in C++',['https://eigen.tuxfamily.org/dox/TopicTemplateKeyword.html',1,'']]],
  ['the_20visual_20studio_20debugger_30',['Image Watch: viewing in-memory images in the Visual Studio debugger',['https://docs.opencv.org/4.2.0/d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'']]],
  ['theory_31',['F-transform theory',['https://docs.opencv.org/4.2.0/db/daf/tutorial_fuzzy_theory.html',1,'']]],
  ['threading_32',['Eigen and multi-threading',['https://eigen.tuxfamily.org/dox/TopicMultiThreading.html',1,'']]],
  ['thresholding_33',['thresholding',['https://docs.opencv.org/4.2.0/d7/d4d/tutorial_py_thresholding.html',1,'Image Thresholding'],['https://docs.opencv.org/4.2.0/d7/dd0/tutorial_js_thresholding.html',1,'Image Thresholding']]],
  ['thresholding_20operations_34',['Basic Thresholding Operations',['https://docs.opencv.org/4.2.0/db/d8e/tutorial_threshold.html',1,'']]],
  ['thresholding_20operations_20using_20inrange_35',['Thresholding Operations using inRange',['https://docs.opencv.org/4.2.0/da/d97/tutorial_threshold_inRange.html',1,'']]],
  ['thrust_36',['Using a cv::cuda::GpuMat with thrust',['https://docs.opencv.org/4.2.0/d8/db9/tutorial_gpu_thrust_interop.html',1,'']]],
  ['time_20measurement_20with_20opencv_37',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['time_20pose_20estimation_20of_20a_20textured_20object_38',['Real Time pose estimation of a textured object',['https://docs.opencv.org/4.2.0/dc/d2c/tutorial_real_time_pose.html',1,'']]],
  ['to_20build_20applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_39',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['to_20enable_20halide_20backend_20for_20improve_20efficiency_40',['How to enable Halide backend for improve efficiency',['https://docs.opencv.org/4.2.0/de/d37/tutorial_dnn_halide.html',1,'']]],
  ['to_20find_20a_20known_20object_41',['Features2D + Homography to find a known object',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_feature_homography.html',1,'']]],
  ['to_20find_20objects_42',['Feature Matching + Homography to find Objects',['https://docs.opencv.org/4.2.0/d1/de0/tutorial_py_feature_homography.html',1,'']]],
  ['to_20java_20development_43',['Introduction to Java Development',['https://docs.opencv.org/4.2.0/d9/d52/tutorial_java_dev_intro.html',1,'']]],
  ['to_20opencv_44',['to opencv',['https://docs.opencv.org/4.2.0/df/d65/tutorial_table_of_content_introduction.html',1,'Introduction to OpenCV'],['https://docs.opencv.org/4.2.0/da/df6/tutorial_py_table_of_contents_setup.html',1,'Introduction to OpenCV']]],
  ['to_20opencv_20development_20with_20clojure_45',['Introduction to OpenCV Development with Clojure',['https://docs.opencv.org/4.2.0/d7/d1e/tutorial_clojure_dev_intro.html',1,'']]],
  ['to_20opencv_20js_46',['Introduction to OpenCV.js',['https://docs.opencv.org/4.2.0/df/df7/tutorial_js_table_of_contents_setup.html',1,'']]],
  ['to_20opencv_20js_20and_20tutorials_47',['Introduction to OpenCV.js and Tutorials',['https://docs.opencv.org/4.2.0/df/d0a/tutorial_js_intro.html',1,'']]],
  ['to_20opencv_20python_20tutorials_48',['Introduction to OpenCV-Python Tutorials',['https://docs.opencv.org/4.2.0/d0/de3/tutorial_py_intro.html',1,'']]],
  ['to_20opencv_20tracker_49',['Introduction to OpenCV Tracker',['https://docs.opencv.org/4.2.0/d2/d0a/tutorial_introduction_to_tracker.html',1,'']]],
  ['to_20our_20applications_50',['Adding a Trackbar to our applications!',['https://docs.opencv.org/4.2.0/da/d6a/tutorial_trackbar.html',1,'']]],
  ['to_20principal_20component_20analysis_20pca_51',['Introduction to Principal Component Analysis (PCA)',['https://docs.opencv.org/4.2.0/d1/dee/tutorial_introduction_to_pca.html',1,'']]],
  ['to_20run_20deep_20networks_20in_20browser_52',['How to run deep networks in browser',['https://docs.opencv.org/4.2.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['to_20run_20deep_20networks_20on_20android_20device_53',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['to_20scan_20images_20lookup_20tables_20and_20time_20measurement_20with_20opencv_54',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['to_20schedule_20your_20network_20for_20halide_20backend_55',['How to schedule your network for Halide backend',['https://docs.opencv.org/4.2.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['to_20sift_20scale_20invariant_20feature_20transform_56',['Introduction to SIFT (Scale-Invariant Feature Transform)',['https://docs.opencv.org/4.2.0/da/df5/tutorial_py_sift_intro.html',1,'']]],
  ['to_20support_20vector_20machines_57',['Introduction to Support Vector Machines',['https://docs.opencv.org/4.2.0/d1/d73/tutorial_introduction_to_svm.html',1,'']]],
  ['to_20surf_20speeded_20up_20robust_20features_58',['Introduction to SURF (Speeded-Up Robust Features)',['https://docs.opencv.org/4.2.0/df/dd2/tutorial_py_surf_intro.html',1,'']]],
  ['to_20the_20facemark_20api_59',['Adding a new algorithm to the Facemark API',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'']]],
  ['to_20track_60',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['to_20use_20background_20subtraction_20methods_61',['How to Use Background Subtraction Methods',['https://docs.opencv.org/4.2.0/d1/dc5/tutorial_background_subtraction.html',1,'']]],
  ['to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_62',['How to use the OpenCV parallel_for_ to parallelize your code',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'']]],
  ['to_20your_20application_63',['Add a Trackbar to Your Application',['https://docs.opencv.org/4.2.0/d5/df3/tutorial_js_trackbar.html',1,'']]],
  ['to_20your_20images_64',['Adding borders to your images',['https://docs.opencv.org/4.2.0/dc/da3/tutorial_copyMakeBorder.html',1,'']]],
  ['tomasi_20corner_20detector_65',['Shi-Tomasi corner detector',['https://docs.opencv.org/4.2.0/d8/dd8/tutorial_good_features_to_track.html',1,'']]],
  ['tomasi_20corner_20detector_20good_20features_20to_20track_66',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['topics_67',['General topics',['https://eigen.tuxfamily.org/dox/UserManual_Generalities.html',1,'']]],
  ['track_68',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['trackbar_20as_20the_20color_20palette_69',['Trackbar as the Color Palette',['https://docs.opencv.org/4.2.0/d9/dc8/tutorial_py_trackbar.html',1,'']]],
  ['trackbar_20to_20our_20applications_70',['Adding a Trackbar to our applications!',['https://docs.opencv.org/4.2.0/da/d6a/tutorial_trackbar.html',1,'']]],
  ['trackbar_20to_20your_20application_71',['Add a Trackbar to Your Application',['https://docs.opencv.org/4.2.0/d5/df3/tutorial_js_trackbar.html',1,'']]],
  ['tracker_72',['tracker',['https://docs.opencv.org/4.2.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'Customizing the CN Tracker'],['https://docs.opencv.org/4.2.0/d2/d0a/tutorial_introduction_to_tracker.html',1,'Introduction to OpenCV Tracker']]],
  ['tracking_73',['AKAZE and ORB planar tracking',['https://docs.opencv.org/4.2.0/dc/d16/tutorial_akaze_tracking.html',1,'']]],
  ['training_74',['training',['https://docs.opencv.org/4.2.0/dc/d88/tutorial_traincascade.html',1,'Cascade Classifier Training'],['https://docs.opencv.org/4.2.0/d2/d59/tutorial_ximgproc_training.html',1,'Structured forest training']]],
  ['training_20data_20generation_20using_20icosphere_75',['Training data generation using Icosphere',['https://docs.opencv.org/4.2.0/d6/df4/tutorial_data_generation.html',1,'']]],
  ['training_20model_20analysis_76',['Training Model Analysis',['https://docs.opencv.org/4.2.0/d8/d09/tutorial_model_analysis.html',1,'']]],
  ['training_20the_20learning_20based_20white_20balance_20algorithm_77',['Training the learning-based white balance algorithm',['https://docs.opencv.org/4.2.0/dc/dcb/tutorial_xphoto_training_white_balance.html',1,'']]],
  ['transform_78',['transform',['https://docs.opencv.org/4.2.0/d8/d01/tutorial_discrete_fourier_transform.html',1,'Discrete Fourier Transform'],['https://docs.opencv.org/4.2.0/d3/d1d/tutorial_fuzzy_filtering.html',1,'Filtering using F-transform'],['https://docs.opencv.org/4.2.0/dd/d02/tutorial_js_fourier_transform.html',1,'Fourier Transform'],['https://docs.opencv.org/4.2.0/de/dbc/tutorial_py_fourier_transform.html',1,'Fourier Transform'],['https://docs.opencv.org/4.2.0/da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d3/db8/tutorial_fuzzy_inpainting.html',1,'Inpainting using F-transform'],['https://docs.opencv.org/4.2.0/da/df5/tutorial_py_sift_intro.html',1,'Introduction to SIFT (Scale-Invariant Feature Transform)']]],
  ['transform_20and_20watershed_20algorithm_79',['Image Segmentation with Distance Transform and Watershed Algorithm',['https://docs.opencv.org/4.2.0/d2/dbd/tutorial_distance_transform.html',1,'']]],
  ['transform_20theory_80',['F-transform theory',['https://docs.opencv.org/4.2.0/db/daf/tutorial_fuzzy_theory.html',1,'']]],
  ['transformations_81',['transformations',['https://docs.opencv.org/4.2.0/d4/d61/tutorial_warp_affine.html',1,'Affine Transformations'],['https://docs.opencv.org/4.2.0/d3/dbe/tutorial_opening_closing_hats.html',1,'More Morphology Transformations'],['https://docs.opencv.org/4.2.0/d4/d76/tutorial_js_morphological_ops.html',1,'Morphological Transformations'],['https://docs.opencv.org/4.2.0/d9/d61/tutorial_py_morphological_ops.html',1,'Morphological Transformations'],['https://docs.opencv.org/4.2.0/d7/d72/tutorial_transformations.html',1,'Transformations']]],
  ['transformations_20of_20images_82',['transformations of images',['https://docs.opencv.org/4.2.0/dd/d52/tutorial_js_geometric_transformations.html',1,'Geometric Transformations of Images'],['https://docs.opencv.org/4.2.0/da/d6e/tutorial_py_geometric_transformations.html',1,'Geometric Transformations of Images']]],
  ['transforms_20in_20opencv_83',['Image Transforms in OpenCV',['https://docs.opencv.org/4.2.0/dd/dc4/tutorial_py_table_of_contents_transforms.html',1,'']]],
  ['transforms_20in_20opencv_20js_84',['Image Transforms in OpenCV.js',['https://docs.opencv.org/4.2.0/db/db3/tutorial_js_table_of_contents_transforms.html',1,'']]],
  ['transition_20guide_85',['Transition guide',['https://docs.opencv.org/4.2.0/db/dfa/tutorial_transition_guide.html',1,'']]],
  ['tutorial_86',['tutorial',['https://docs.opencv.org/4.2.0/db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['https://docs.opencv.org/4.2.0/d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'Capture Sinusoidal pattern tutorial'],['https://docs.opencv.org/4.2.0/dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial'],['https://docs.opencv.org/4.2.0/df/dfa/tutorial_line_descriptor_main.html',1,'Line Features Tutorial'],['https://docs.opencv.org/4.2.0/db/d74/tutorial_unwrap_phase_map.html',1,'Phase Unwrapping tutorial']]],
  ['tutorial_20on_20facial_20landmark_20detector_20api_87',['Tutorial on Facial Landmark Detector API',['https://docs.opencv.org/4.2.0/d5/d47/tutorial_table_of_content_facemark.html',1,'']]],
  ['tutorials_88',['tutorials',['https://docs.opencv.org/4.2.0/d7/d36/tutorial_fuzzy.html',1,'Fuzzy image processing tutorials'],['https://docs.opencv.org/4.2.0/d0/de3/tutorial_py_intro.html',1,'Introduction to OpenCV-Python Tutorials'],['https://docs.opencv.org/4.2.0/df/d0a/tutorial_js_intro.html',1,'Introduction to OpenCV.js and Tutorials'],['https://docs.opencv.org/4.2.0/d9/df8/tutorial_root.html',1,'OpenCV Tutorials'],['https://docs.opencv.org/4.2.0/d6/d00/tutorial_py_root.html',1,'OpenCV-Python Tutorials'],['https://docs.opencv.org/4.2.0/d5/d10/tutorial_js_root.html',1,'OpenCV.js Tutorials'],['https://docs.opencv.org/4.2.0/d3/d81/tutorial_structured_light.html',1,'Structured Light tutorials']]],
  ['tutorials_20for_20bgsegm_20module_89',['Tutorials for bgsegm module',['https://docs.opencv.org/4.2.0/d3/d89/tutorial_table_of_content_bgsegm.html',1,'']]],
  ['tutorials_20for_20contrib_20modules_90',['Tutorials for contrib modules',['https://docs.opencv.org/4.2.0/d3/d81/tutorial_contrib_root.html',1,'']]],
  ['tutorials_20for_20face_20module_91',['Tutorials for face module',['https://docs.opencv.org/4.2.0/de/d27/tutorial_table_of_content_face.html',1,'']]],
  ['tutorialsparse_5fexample_5fdetails_92',['TutorialSparse_example_details',['https://eigen.tuxfamily.org/dox/TutorialSparse_example_details.html',1,'']]],
  ['two_20dimensional_20phase_20maps_93',['Unwrap two-dimensional phase maps',['https://docs.opencv.org/4.2.0/d9/dfb/tutorial_unwrap.html',1,'']]],
  ['two_20images_20using_20opencv_94',['Adding (blending) two images using OpenCV',['https://docs.opencv.org/4.2.0/d5/dc4/tutorial_adding_images.html',1,'']]],
  ['type_95',['Adding a new expression type',['https://eigen.tuxfamily.org/dox/TopicNewExpressionType.html',1,'']]],
  ['typename_20keywords_20in_20c_96',['The template and typename keywords in C++',['https://eigen.tuxfamily.org/dox/TopicTemplateKeyword.html',1,'']]],
  ['types_97',['types',['https://eigen.tuxfamily.org/dox/TopicScalarTypes.html',1,'Scalar types'],['https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html',1,'Using custom scalar types']]],
  ['types_20as_20parameters_98',['Writing Functions Taking Eigen Types as Parameters',['https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html',1,'']]]
];
