var searchData=
[
  ['g_20api_0',['g api',['https://docs.opencv.org/4.2.0/d8/d24/tutorial_gapi_interactive_face_detection.html',1,'Face analytics pipeline with G-API'],['https://docs.opencv.org/4.2.0/d4/d48/tutorial_gapi_face_beautification.html',1,'Implementing a face beautification algorithm with G-API'],['https://docs.opencv.org/4.2.0/d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'Porting anisotropic image segmentation on G-API']]],
  ['g_20api_20overview_1',['G-API Overview',['https://docs.opencv.org/4.2.0/db/d87/md_gapi_doc_slides_README.html',1,'']]],
  ['gapi_20module_2',['Graph API (gapi module)',['https://docs.opencv.org/4.2.0/df/d7e/tutorial_table_of_content_gapi.html',1,'']]],
  ['gcc_20and_20cmake_3',['Using OpenCV with gcc and CMake',['https://docs.opencv.org/4.2.0/db/df5/tutorial_linux_gcc_cmake.html',1,'']]],
  ['gdal_4',['Reading Geospatial Raster files with GDAL',['https://docs.opencv.org/4.2.0/d7/d73/tutorial_raster_io_gdal.html',1,'']]],
  ['general_20topics_5',['General topics',['https://eigen.tuxfamily.org/dox/UserManual_Generalities.html',1,'']]],
  ['generation_20using_20icosphere_6',['Training data generation using Icosphere',['https://docs.opencv.org/4.2.0/d6/df4/tutorial_data_generation.html',1,'']]],
  ['generator_20and_20text_20with_20opencv_7',['Random generator and text with OpenCV',['https://docs.opencv.org/4.2.0/df/d61/tutorial_random_generator_and_text.html',1,'']]],
  ['geometric_20transformations_20of_20images_8',['geometric transformations of images',['https://docs.opencv.org/4.2.0/dd/d52/tutorial_js_geometric_transformations.html',1,'Geometric Transformations of Images'],['https://docs.opencv.org/4.2.0/da/d6e/tutorial_py_geometric_transformations.html',1,'Geometric Transformations of Images']]],
  ['geometry_9',['Epipolar Geometry',['https://docs.opencv.org/4.2.0/da/de9/tutorial_py_epipolar_geometry.html',1,'']]],
  ['geospatial_20raster_20files_20with_20gdal_10',['Reading Geospatial Raster files with GDAL',['https://docs.opencv.org/4.2.0/d7/d73/tutorial_raster_io_gdal.html',1,'']]],
  ['getting_20started_11',['getting started',['https://docs.opencv.org/4.2.0/d4/d73/tutorial_py_contours_begin.html',1,'Contours : Getting Started'],['https://docs.opencv.org/4.2.0/d5/daa/tutorial_js_contours_begin.html',1,'Contours : Getting Started'],['https://eigen.tuxfamily.org/dox/GettingStarted.html',1,'Getting started']]],
  ['getting_20started_20with_20images_12',['getting started with images',['https://docs.opencv.org/4.2.0/df/d24/tutorial_js_image_display.html',1,'Getting Started with Images'],['https://docs.opencv.org/4.2.0/dc/d2e/tutorial_py_image_display.html',1,'Getting Started with Images']]],
  ['getting_20started_20with_20videos_13',['getting started with videos',['https://docs.opencv.org/4.2.0/dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos'],['https://docs.opencv.org/4.2.0/dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos']]],
  ['git_20bash_20version_202_2014_201_20and_20cmake_20version_203_209_201_14',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['https://docs.opencv.org/4.2.0/db/d4c/tutorial_install_tesseract.html',1,'']]],
  ['good_20features_20to_20track_15',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['gpu_16',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['gpu_20accelerated_20computer_20vision_20cuda_20module_17',['GPU-Accelerated Computer Vision (cuda module)',['https://docs.opencv.org/4.2.0/da/d2c/tutorial_table_of_content_gpu.html',1,'']]],
  ['grabcut_20algorithm_18',['grabcut algorithm',['https://docs.opencv.org/4.2.0/dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['https://docs.opencv.org/4.2.0/d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm']]],
  ['gradient_20structure_20tensor_19',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['gradients_20',['gradients',['https://docs.opencv.org/4.2.0/d5/d0f/tutorial_py_gradients.html',1,'Image Gradients'],['https://docs.opencv.org/4.2.0/da/d85/tutorial_js_gradients.html',1,'Image Gradients']]],
  ['graph_20api_21',['graph api',['https://docs.opencv.org/4.2.0/d0/d1e/gapi.html',1,'Graph API'],['https://docs.opencv.org/4.2.0/d6/dc9/gapi_purposes.html',1,'Why Graph API?']]],
  ['graph_20api_20gapi_20module_22',['Graph API (gapi module)',['https://docs.opencv.org/4.2.0/df/d7e/tutorial_table_of_content_gapi.html',1,'']]],
  ['gray_20code_20pattern_20tutorial_23',['gray code pattern tutorial',['https://docs.opencv.org/4.2.0/db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['https://docs.opencv.org/4.2.0/dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial']]],
  ['groups_24',['Creating Groups',['https://docs.opencv.org/4.2.0/d1/d8b/tutorial_hdf_create_groups.html',1,'']]],
  ['gui_20and_20media_20highgui_20module_25',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['gui_20features_26',['GUI Features',['https://docs.opencv.org/4.2.0/df/d04/tutorial_js_table_of_contents_gui.html',1,'']]],
  ['gui_20features_20in_20opencv_27',['Gui Features in OpenCV',['https://docs.opencv.org/4.2.0/dc/d4d/tutorial_py_table_of_contents_gui.html',1,'']]],
  ['guide_28',['guide',['../md_StyleGuide.html',1,'Style Guide'],['https://docs.opencv.org/4.2.0/db/dfa/tutorial_transition_guide.html',1,'Transition guide']]]
];
