var searchData=
[
  ['landmark_20detection_0',['Face swapping using face landmark detection',['https://docs.opencv.org/4.2.0/d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'']]],
  ['landmark_20detection_20in_20a_20video_1',['Face landmark detection in a video',['https://docs.opencv.org/4.2.0/d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'']]],
  ['landmark_20detection_20in_20an_20image_2',['Face landmark detection in an image',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'']]],
  ['landmark_20detector_20api_3',['Tutorial on Facial Landmark Detector API',['https://docs.opencv.org/4.2.0/d5/d47/tutorial_table_of_content_facemark.html',1,'']]],
  ['lapack_20from_20eigen_4',['Using BLAS/LAPACK from Eigen',['https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html',1,'']]],
  ['laplace_20operator_5',['Laplace Operator',['https://docs.opencv.org/4.2.0/d5/db5/tutorial_laplace_operator.html',1,'']]],
  ['launching_20viz_6',['Launching Viz',['https://docs.opencv.org/4.2.0/d5/d7d/tutorial_launching_viz.html',1,'']]],
  ['layers_20support_7',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['lazy_20evaluation_20and_20aliasing_8',['Lazy Evaluation and Aliasing',['https://eigen.tuxfamily.org/dox/TopicLazyEvaluation.html',1,'']]],
  ['learning_9',['Machine Learning',['https://docs.opencv.org/4.2.0/d6/de2/tutorial_py_table_of_contents_ml.html',1,'']]],
  ['learning_20based_20white_20balance_20algorithm_10',['Training the learning-based white balance algorithm',['https://docs.opencv.org/4.2.0/dc/dcb/tutorial_xphoto_training_white_balance.html',1,'']]],
  ['learning_20layers_20support_11',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['learning_20ml_20module_12',['Machine Learning (ml module)',['https://docs.opencv.org/4.2.0/d1/d69/tutorial_table_of_content_ml.html',1,'']]],
  ['learning_20overview_13',['Machine Learning Overview',['https://docs.opencv.org/4.2.0/dc/dd6/ml_intro.html',1,'']]],
  ['level_20design_20overview_14',['High-level design overview',['https://docs.opencv.org/4.2.0/de/d4d/gapi_hld.html',1,'']]],
  ['level_20gui_20and_20media_20highgui_20module_15',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['level_20stitching_20api_20stitcher_20class_16',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['light_20tutorials_17',['Structured Light tutorials',['https://docs.opencv.org/4.2.0/d3/d81/tutorial_structured_light.html',1,'']]],
  ['line_20features_20tutorial_18',['Line Features Tutorial',['https://docs.opencv.org/4.2.0/df/dfa/tutorial_line_descriptor_main.html',1,'']]],
  ['line_20transform_19',['line transform',['https://docs.opencv.org/4.2.0/d9/db0/tutorial_hough_lines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d6/d10/tutorial_py_houghlines.html',1,'Hough Line Transform'],['https://docs.opencv.org/4.2.0/d3/de6/tutorial_js_houghlines.html',1,'Hough Line Transform']]],
  ['linear_20filters_20',['Making your own linear filters!',['https://docs.opencv.org/4.2.0/d4/dbd/tutorial_filter_2d.html',1,'']]],
  ['linearly_20separable_20data_21',['Support Vector Machines for Non-Linearly Separable Data',['https://docs.opencv.org/4.2.0/d0/dcc/tutorial_non_linear_svms.html',1,'']]],
  ['lines_20by_20using_20morphological_20operations_22',['Extract horizontal and vertical lines by using morphological operations',['https://docs.opencv.org/4.2.0/dd/dd7/tutorial_morph_lines_detection.html',1,'']]],
  ['linux_23',['Installation in Linux',['https://docs.opencv.org/4.2.0/d7/d9f/tutorial_linux_install.html',1,'']]],
  ['linux_20systems_24',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['list_25',['Deprecated List',['../deprecated.html',1,'']]],
  ['load_20and_20display_20an_20image_26',['Load and Display an Image',['https://docs.opencv.org/4.2.0/db/deb/tutorial_display_image.html',1,'']]],
  ['load_20caffe_20framework_20models_27',['Load Caffe framework models',['https://docs.opencv.org/4.2.0/d5/de7/tutorial_dnn_googlenet.html',1,'']]],
  ['load_20modify_20and_20save_20an_20image_28',['Load, Modify, and Save an Image',['https://docs.opencv.org/4.2.0/db/d64/tutorial_load_save_image.html',1,'']]],
  ['local_20features_20matching_29',['AKAZE local features matching',['https://docs.opencv.org/4.2.0/db/d70/tutorial_akaze_matching.html',1,'']]],
  ['location_20in_20subpixels_30',['Detecting corners location in subpixels',['https://docs.opencv.org/4.2.0/dd/d92/tutorial_corner_subpixels.html',1,'']]],
  ['lookup_20tables_20and_20time_20measurement_20with_20opencv_31',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]]
];
