var searchData=
[
  ['random_20generator_20and_20text_20with_20opencv_0',['Random generator and text with OpenCV',['https://docs.opencv.org/4.2.0/df/d61/tutorial_random_generator_and_text.html',1,'']]],
  ['range_20hdr_1',['High Dynamic Range (HDR)',['https://docs.opencv.org/4.2.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['range_20imaging_2',['High Dynamic Range Imaging',['https://docs.opencv.org/4.2.0/d3/db7/tutorial_hdr_imaging.html',1,'']]],
  ['raster_20files_20with_20gdal_3',['Reading Geospatial Raster files with GDAL',['https://docs.opencv.org/4.2.0/d7/d73/tutorial_raster_io_gdal.html',1,'']]],
  ['reading_20and_20writing_20attributes_4',['Reading and Writing Attributes',['https://docs.opencv.org/4.2.0/d5/d10/tutorial_hdf_read_write_attributes.html',1,'']]],
  ['reading_20datasets_5',['Creating, Writing and Reading Datasets',['https://docs.opencv.org/4.2.0/d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'']]],
  ['reading_20geospatial_20raster_20files_20with_20gdal_6',['Reading Geospatial Raster files with GDAL',['https://docs.opencv.org/4.2.0/d7/d73/tutorial_raster_io_gdal.html',1,'']]],
  ['real_20time_20pose_20estimation_20of_20a_20textured_20object_7',['Real Time pose estimation of a textured object',['https://docs.opencv.org/4.2.0/dc/d2c/tutorial_real_time_pose.html',1,'']]],
  ['real_20world_20vision_8',['Retina and real-world vision',['https://docs.opencv.org/4.2.0/d3/d86/tutorial_bioinspired_retina_model.html',1,'']]],
  ['recognition_20with_20opencv_9',['Face Recognition with OpenCV',['https://docs.opencv.org/4.2.0/da/d60/tutorial_face_main.html',1,'']]],
  ['reconstruction_10',['reconstruction',['https://docs.opencv.org/4.2.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'Camera Calibration and 3D Reconstruction'],['https://docs.opencv.org/4.2.0/de/dfd/tutorial_sfm_import_reconstruction.html',1,'Import Reconstruction'],['https://docs.opencv.org/4.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html',1,'Scene Reconstruction']]],
  ['reconstruction_20calib3d_20module_11',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['referencing_20opencv_20from_20other_20doxygen_20projects_12',['Cross referencing OpenCV from other Doxygen projects',['https://docs.opencv.org/4.2.0/d3/dff/tutorial_cross_referencing.html',1,'']]],
  ['remapping_13',['Remapping',['https://docs.opencv.org/4.2.0/d1/da0/tutorial_remap.html',1,'']]],
  ['removing_20filter_14',['Periodic Noise Removing Filter',['https://docs.opencv.org/4.2.0/d2/d0b/tutorial_periodic_noise_removing_filter.html',1,'']]],
  ['resizing_15',['Resizing',['https://eigen.tuxfamily.org/dox/TopicResizing.html',1,'']]],
  ['resolution_20benchmarking_16',['Super-resolution benchmarking',['https://docs.opencv.org/4.2.0/dc/d69/tutorial_dnn_superres_benchmark.html',1,'']]],
  ['resolution_20using_20cnns_17',['Super Resolution using CNNs',['https://docs.opencv.org/4.2.0/d8/df8/tutorial_table_of_content_dnn_superres.html',1,'']]],
  ['retina_20and_20its_20use_20for_20image_20processing_18',['Discovering the human retina and its use for image processing',['https://docs.opencv.org/4.2.0/df/dee/tutorial_table_of_content_retina.html',1,'']]],
  ['retina_20and_20real_20world_20vision_19',['Retina and real-world vision',['https://docs.opencv.org/4.2.0/d3/d86/tutorial_bioinspired_retina_model.html',1,'']]],
  ['retina_20introduction_20',['Bioinspired Module Retina Introduction',['https://docs.opencv.org/4.2.0/d2/d94/bioinspired_retina.html',1,'']]],
  ['robust_20features_21',['Introduction to SURF (Speeded-Up Robust Features)',['https://docs.opencv.org/4.2.0/df/dd2/tutorial_py_surf_intro.html',1,'']]],
  ['robust_20independent_20elementary_20features_22',['BRIEF (Binary Robust Independent Elementary Features)',['https://docs.opencv.org/4.2.0/dc/d7d/tutorial_py_brief.html',1,'']]],
  ['rotated_20boxes_20and_20ellipses_20for_20contours_23',['Creating Bounding rotated boxes and ellipses for contours',['https://docs.opencv.org/4.2.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'']]],
  ['rotated_20brief_24',['ORB (Oriented FAST and Rotated BRIEF)',['https://docs.opencv.org/4.2.0/d1/d89/tutorial_py_orb.html',1,'']]],
  ['run_20deep_20networks_20in_20browser_25',['How to run deep networks in browser',['https://docs.opencv.org/4.2.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['run_20deep_20networks_20on_20android_20device_26',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]]
];
