var searchData=
[
  ['save_20an_20image_0',['Load, Modify, and Save an Image',['https://docs.opencv.org/4.2.0/db/d64/tutorial_load_save_image.html',1,'']]],
  ['scalar_20types_1',['scalar types',['https://eigen.tuxfamily.org/dox/TopicScalarTypes.html',1,'Scalar types'],['https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html',1,'Using custom scalar types']]],
  ['scale_20invariant_20feature_20transform_2',['Introduction to SIFT (Scale-Invariant Feature Transform)',['https://docs.opencv.org/4.2.0/da/df5/tutorial_py_sift_intro.html',1,'']]],
  ['scan_20images_20lookup_20tables_20and_20time_20measurement_20with_20opencv_3',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['scene_20reconstruction_4',['Scene Reconstruction',['https://docs.opencv.org/4.2.0/d4/d18/tutorial_sfm_scene_reconstruction.html',1,'']]],
  ['schedule_20your_20network_20for_20halide_20backend_5',['How to schedule your network for Halide backend',['https://docs.opencv.org/4.2.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['sdk_6',['OpenCV4Android SDK',['https://docs.opencv.org/4.2.0/da/d2a/tutorial_O4A_SDK.html',1,'']]],
  ['sdk_20compatible_20depth_20sensors_7',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['segmentation_20by_20a_20gradient_20structure_20tensor_8',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['segmentation_20on_20g_20api_9',['Porting anisotropic image segmentation on G-API',['https://docs.opencv.org/4.2.0/d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'']]],
  ['segmentation_20with_20distance_20transform_20and_20watershed_20algorithm_10',['Image Segmentation with Distance Transform and Watershed Algorithm',['https://docs.opencv.org/4.2.0/d2/dbd/tutorial_distance_transform.html',1,'']]],
  ['segmentation_20with_20watershed_20algorithm_11',['segmentation with watershed algorithm',['https://docs.opencv.org/4.2.0/d3/db4/tutorial_py_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['https://docs.opencv.org/4.2.0/d7/d1c/tutorial_js_watershed.html',1,'Image Segmentation with Watershed Algorithm']]],
  ['sensors_12',['sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors'],['https://docs.opencv.org/4.2.0/d7/d6f/tutorial_kinect_openni.html',1,'Using Kinect and other OpenNI compatible depth sensors']]],
  ['senz3d_20and_20other_20intel_20perceptual_20computing_20sdk_20compatible_20depth_20sensors_13',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['separable_20data_14',['Support Vector Machines for Non-Linearly Separable Data',['https://docs.opencv.org/4.2.0/d0/dcc/tutorial_non_linear_svms.html',1,'']]],
  ['sfm_20module_20installation_15',['SFM module installation',['https://docs.opencv.org/4.2.0/db/db8/tutorial_sfm_installation.html',1,'']]],
  ['shi_20tomasi_20corner_20detector_16',['Shi-Tomasi corner detector',['https://docs.opencv.org/4.2.0/d8/dd8/tutorial_good_features_to_track.html',1,'']]],
  ['shi_20tomasi_20corner_20detector_20good_20features_20to_20track_17',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['sift_20scale_20invariant_20feature_20transform_18',['Introduction to SIFT (Scale-Invariant Feature Transform)',['https://docs.opencv.org/4.2.0/da/df5/tutorial_py_sift_intro.html',1,'']]],
  ['similarity_20check_20pnsr_20and_20ssim_20on_20the_20gpu_19',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['similarity_20measurement_20',['Video Input with OpenCV and similarity measurement',['https://docs.opencv.org/4.2.0/d5/dc4/tutorial_video_input_psnr_ssim.html',1,'']]],
  ['simple_20example_21',['What happens inside Eigen, on a simple example',['https://eigen.tuxfamily.org/dox/TopicInsideEigenExample.html',1,'']]],
  ['single_20output_22',['Upscaling images: single-output',['https://docs.opencv.org/4.2.0/d5/d29/tutorial_dnn_superres_upscale_image_single.html',1,'']]],
  ['sinusoidal_20pattern_20tutorial_23',['Capture Sinusoidal pattern tutorial',['https://docs.opencv.org/4.2.0/d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'']]],
  ['smoothing_20images_24',['smoothing images',['https://docs.opencv.org/4.2.0/dd/d6a/tutorial_js_filtering.html',1,'Smoothing Images'],['https://docs.opencv.org/4.2.0/dc/dd3/tutorial_gausian_median_blur_bilateral_filter.html',1,'Smoothing Images'],['https://docs.opencv.org/4.2.0/d4/d13/tutorial_py_filtering.html',1,'Smoothing Images']]],
  ['sobel_20derivatives_25',['Sobel Derivatives',['https://docs.opencv.org/4.2.0/d2/d2c/tutorial_sobel_derivatives.html',1,'']]],
  ['some_20data_20structures_26',['Some Data Structures',['https://docs.opencv.org/4.2.0/d5/df1/tutorial_js_some_data_structures.html',1,'']]],
  ['speeded_20up_20robust_20features_27',['Introduction to SURF (Speeded-Up Robust Features)',['https://docs.opencv.org/4.2.0/df/dd2/tutorial_py_surf_intro.html',1,'']]],
  ['square_20chessboard_28',['Camera calibration with square chessboard',['https://docs.opencv.org/4.2.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['ssim_20on_20the_20gpu_29',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['started_30',['started',['https://docs.opencv.org/4.2.0/d5/daa/tutorial_js_contours_begin.html',1,'Contours : Getting Started'],['https://docs.opencv.org/4.2.0/d4/d73/tutorial_py_contours_begin.html',1,'Contours : Getting Started'],['https://eigen.tuxfamily.org/dox/GettingStarted.html',1,'Getting started']]],
  ['started_20with_20images_31',['started with images',['https://docs.opencv.org/4.2.0/df/d24/tutorial_js_image_display.html',1,'Getting Started with Images'],['https://docs.opencv.org/4.2.0/dc/d2e/tutorial_py_image_display.html',1,'Getting Started with Images']]],
  ['started_20with_20videos_32',['started with videos',['https://docs.opencv.org/4.2.0/dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos'],['https://docs.opencv.org/4.2.0/dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos']]],
  ['stereo_33',['Quasi dense Stereo',['https://docs.opencv.org/4.2.0/d7/d5a/tutorial_qds_quasi_dense_stereo.html',1,'']]],
  ['stereo_20images_34',['Depth Map from Stereo Images',['https://docs.opencv.org/4.2.0/dd/d53/tutorial_py_depthmap.html',1,'']]],
  ['stereo_20stereo_20module_35',['Quasi Dense Stereo (stereo module)',['https://docs.opencv.org/4.2.0/d9/d58/tutorial_table_of_content_quasi_dense_stereo.html',1,'']]],
  ['stitcher_20class_36',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['stitching_20api_20stitcher_20class_37',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['stitching_20stitching_20module_38',['Images stitching (stitching module)',['https://docs.opencv.org/4.2.0/d0/d33/tutorial_table_of_content_stitching.html',1,'']]],
  ['structure_20from_20motion_39',['Structure From Motion',['https://docs.opencv.org/4.2.0/de/d7c/tutorial_table_of_content_sfm.html',1,'']]],
  ['structure_20tensor_40',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['structured_20forest_20training_41',['Structured forest training',['https://docs.opencv.org/4.2.0/d2/d59/tutorial_ximgproc_training.html',1,'']]],
  ['structured_20forests_20for_20fast_20edge_20detection_42',['Structured forests for fast edge detection',['https://docs.opencv.org/4.2.0/d0/da5/tutorial_ximgproc_prediction.html',1,'']]],
  ['structured_20light_20tutorials_43',['Structured Light tutorials',['https://docs.opencv.org/4.2.0/d3/d81/tutorial_structured_light.html',1,'']]],
  ['structures_44',['Some Data Structures',['https://docs.opencv.org/4.2.0/d5/df1/tutorial_js_some_data_structures.html',1,'']]],
  ['studio_45',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['studio_20debugger_46',['Image Watch: viewing in-memory images in the Visual Studio debugger',['https://docs.opencv.org/4.2.0/d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'']]],
  ['style_20guide_47',['Style Guide',['../md_StyleGuide.html',1,'']]],
  ['subpixels_48',['Detecting corners location in subpixels',['https://docs.opencv.org/4.2.0/dd/d92/tutorial_corner_subpixels.html',1,'']]],
  ['subtraction_49',['subtraction',['https://docs.opencv.org/4.2.0/d8/d38/tutorial_bgsegm_bg_subtraction.html',1,'Background Subtraction'],['https://docs.opencv.org/4.2.0/de/df4/tutorial_js_bg_subtraction.html',1,'Background Subtraction'],['https://docs.opencv.org/4.2.0/db/d5c/tutorial_py_bg_subtraction.html',1,'Background Subtraction']]],
  ['subtraction_20methods_50',['How to Use Background Subtraction Methods',['https://docs.opencv.org/4.2.0/d1/dc5/tutorial_background_subtraction.html',1,'']]],
  ['super_20resolution_20benchmarking_51',['Super-resolution benchmarking',['https://docs.opencv.org/4.2.0/dc/d69/tutorial_dnn_superres_benchmark.html',1,'']]],
  ['super_20resolution_20using_20cnns_52',['Super Resolution using CNNs',['https://docs.opencv.org/4.2.0/d8/df8/tutorial_table_of_content_dnn_superres.html',1,'']]],
  ['support_53',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['support_20vector_20machines_54',['Introduction to Support Vector Machines',['https://docs.opencv.org/4.2.0/d1/d73/tutorial_introduction_to_svm.html',1,'']]],
  ['support_20vector_20machines_20for_20non_20linearly_20separable_20data_55',['Support Vector Machines for Non-Linearly Separable Data',['https://docs.opencv.org/4.2.0/d0/dcc/tutorial_non_linear_svms.html',1,'']]],
  ['support_20vector_20machines_20svm_56',['Support Vector Machines (SVM)',['https://docs.opencv.org/4.2.0/d3/d02/tutorial_py_svm_index.html',1,'']]],
  ['surf_20speeded_20up_20robust_20features_57',['Introduction to SURF (Speeded-Up Robust Features)',['https://docs.opencv.org/4.2.0/df/dd2/tutorial_py_surf_intro.html',1,'']]],
  ['svm_58',['svm',['https://docs.opencv.org/4.2.0/dd/d3b/tutorial_py_svm_opencv.html',1,'OCR of Hand-written Data using SVM'],['https://docs.opencv.org/4.2.0/d3/d02/tutorial_py_svm_index.html',1,'Support Vector Machines (SVM)'],['https://docs.opencv.org/4.2.0/d4/db1/tutorial_py_svm_basics.html',1,'Understanding SVM']]],
  ['swapping_20using_20face_20landmark_20detection_59',['Face swapping using face landmark detection',['https://docs.opencv.org/4.2.0/d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'']]],
  ['systems_60',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]]
];
