var searchData=
[
  ['unclassified_20pages_0',['Unclassified pages',['https://eigen.tuxfamily.org/dox/UnclassifiedPages.html',1,'']]],
  ['understanding_20eigen_1',['Understanding Eigen',['https://eigen.tuxfamily.org/dox/UserManual_UnderstandingEigen.html',1,'']]],
  ['understanding_20features_2',['Understanding Features',['https://docs.opencv.org/4.2.0/df/d54/tutorial_py_features_meaning.html',1,'']]],
  ['understanding_20k_2dmeans_20clustering_3',['Understanding K-Means Clustering',['https://docs.opencv.org/4.2.0/de/d4d/tutorial_py_kmeans_understanding.html',1,'']]],
  ['understanding_20k_2dnearest_20neighbour_4',['Understanding k-Nearest Neighbour',['https://docs.opencv.org/4.2.0/d5/d26/tutorial_py_knn_understanding.html',1,'']]],
  ['understanding_20svm_5',['Understanding SVM',['https://docs.opencv.org/4.2.0/d4/db1/tutorial_py_svm_basics.html',1,'']]],
  ['unwrap_20two_2ddimensional_20phase_20maps_6',['Unwrap two-dimensional phase maps',['https://docs.opencv.org/4.2.0/d9/dfb/tutorial_unwrap.html',1,'']]],
  ['upscaling_20images_3a_20multi_2doutput_7',['Upscaling images: multi-output',['https://docs.opencv.org/4.2.0/d6/dca/tutorial_dnn_superres_upscale_image_multi.html',1,'']]],
  ['upscaling_20images_3a_20single_2doutput_8',['Upscaling images: single-output',['https://docs.opencv.org/4.2.0/d5/d29/tutorial_dnn_superres_upscale_image_single.html',1,'']]],
  ['upscaling_20video_9',['Upscaling video',['https://docs.opencv.org/4.2.0/de/d7f/tutorial_dnn_superres_upscale_video.html',1,'']]],
  ['use_20opencl_20in_20android_20camera_20preview_20based_20cv_20application_10',['Use OpenCL in Android camera preview based CV application',['https://docs.opencv.org/4.2.0/d7/dbd/tutorial_android_ocl_intro.html',1,'']]],
  ['using_20_25eigen_20in_20cmake_20projects_11',['Using %Eigen in CMake Projects',['https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html',1,'']]],
  ['using_20a_20cv_3a_3acuda_3a_3agpumat_20with_20thrust_12',['Using a cv::cuda::GpuMat with thrust',['https://docs.opencv.org/4.2.0/d8/db9/tutorial_gpu_thrust_interop.html',1,'']]],
  ['using_20blas_2flapack_20from_20_25eigen_13',['Using BLAS/LAPACK from %Eigen',['https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html',1,'']]],
  ['using_20creative_20senz3d_20and_20other_20intel_20perceptual_20computing_20sdk_20compatible_20depth_20sensors_14',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['using_20custom_20scalar_20types_15',['Using custom scalar types',['https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html',1,'']]],
  ['using_20eigen_20in_20cuda_20kernels_16',['Using Eigen in CUDA kernels',['https://eigen.tuxfamily.org/dox/TopicCUDA.html',1,'']]],
  ['using_20intel®_20mkl_20from_20_25eigen_17',['Using Intel® MKL from %Eigen',['https://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html',1,'']]],
  ['using_20kinect_20and_20other_20openni_20compatible_20depth_20sensors_18',['Using Kinect and other OpenNI compatible depth sensors',['https://docs.opencv.org/4.2.0/d7/d6f/tutorial_kinect_openni.html',1,'']]],
  ['using_20multitracker_19',['Using MultiTracker',['https://docs.opencv.org/4.2.0/d5/d07/tutorial_multitracker.html',1,'']]],
  ['using_20opencv_20java_20with_20eclipse_20',['Using OpenCV Java with Eclipse',['https://docs.opencv.org/4.2.0/d1/d0a/tutorial_java_eclipse.html',1,'']]],
  ['using_20opencv_20with_20eclipse_20_28plugin_20cdt_29_21',['Using OpenCV with Eclipse (plugin CDT)',['https://docs.opencv.org/4.2.0/d7/d16/tutorial_linux_eclipse.html',1,'']]],
  ['using_20opencv_20with_20gcc_20and_20cmake_22',['Using OpenCV with gcc and CMake',['https://docs.opencv.org/4.2.0/db/df5/tutorial_linux_gcc_cmake.html',1,'']]],
  ['using_20opencv_2ejs_23',['Using OpenCV.js',['https://docs.opencv.org/4.2.0/d0/d84/tutorial_js_usage.html',1,'']]],
  ['using_20opencv_2ejs_20in_20node_2ejs_24',['Using OpenCV.js In Node.js',['https://docs.opencv.org/4.2.0/dc/de6/tutorial_js_nodejs.html',1,'']]],
  ['using_20the_20facemark_20api_25',['Using the Facemark API',['https://docs.opencv.org/4.2.0/d7/dec/tutorial_facemark_usage.html',1,'']]],
  ['using_20the_20facemarkaam_26',['Using the FacemarkAAM',['https://docs.opencv.org/4.2.0/d5/dd8/tutorial_facemark_aam.html',1,'']]]
];
