var searchData=
[
  ['c_0',['The template and typename keywords in C++',['https://eigen.tuxfamily.org/dox/TopicTemplateKeyword.html',1,'']]],
  ['caffe_20framework_20models_1',['Load Caffe framework models',['https://docs.opencv.org/4.2.0/d5/de7/tutorial_dnn_googlenet.html',1,'']]],
  ['calculation_2',['Histogram Calculation',['https://docs.opencv.org/4.2.0/d8/dbc/tutorial_histogram_calculation.html',1,'']]],
  ['calib3d_20module_3',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['calibration_4',['calibration',['https://docs.opencv.org/4.2.0/dc/dbb/tutorial_py_calibration.html',1,'Camera Calibration'],['https://docs.opencv.org/4.2.0/d2/d1c/tutorial_multi_camera_main.html',1,'Multi-camera Calibration'],['https://docs.opencv.org/4.2.0/dd/d12/tutorial_omnidir_calib_main.html',1,'Omnidirectional Cameara Calibration']]],
  ['calibration_20and_203d_20reconstruction_5',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'']]],
  ['calibration_20and_203d_20reconstruction_20calib3d_20module_6',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['calibration_20application_7',['Interactive camera calibration application',['https://docs.opencv.org/4.2.0/d7/d21/tutorial_interactive_calibration.html',1,'']]],
  ['calibration_20pattern_8',['Create calibration pattern',['https://docs.opencv.org/4.2.0/da/d0d/tutorial_camera_calibration_pattern.html',1,'']]],
  ['calibration_20with_20aruco_20and_20charuco_9',['Calibration with ArUco and ChArUco',['https://docs.opencv.org/4.2.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['calibration_20with_20opencv_10',['Camera calibration With OpenCV',['https://docs.opencv.org/4.2.0/d4/d94/tutorial_camera_calibration.html',1,'']]],
  ['calibration_20with_20square_20chessboard_11',['Camera calibration with square chessboard',['https://docs.opencv.org/4.2.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['cameara_20calibration_12',['Omnidirectional Cameara Calibration',['https://docs.opencv.org/4.2.0/dd/d12/tutorial_omnidir_calib_main.html',1,'']]],
  ['camera_20calibration_13',['camera calibration',['https://docs.opencv.org/4.2.0/dc/dbb/tutorial_py_calibration.html',1,'Camera Calibration'],['https://docs.opencv.org/4.2.0/d2/d1c/tutorial_multi_camera_main.html',1,'Multi-camera Calibration']]],
  ['camera_20calibration_20and_203d_20reconstruction_14',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_20calib3d_20module_15',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['camera_20calibration_20application_16',['Interactive camera calibration application',['https://docs.opencv.org/4.2.0/d7/d21/tutorial_interactive_calibration.html',1,'']]],
  ['camera_20calibration_20with_20opencv_17',['Camera calibration With OpenCV',['https://docs.opencv.org/4.2.0/d4/d94/tutorial_camera_calibration.html',1,'']]],
  ['camera_20calibration_20with_20square_20chessboard_18',['Camera calibration with square chessboard',['https://docs.opencv.org/4.2.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['camera_20configuration_19',['Camera Configuration',['../cameraconfig.html',1,'']]],
  ['camera_20motion_20estimation_20',['Camera Motion Estimation',['https://docs.opencv.org/4.2.0/d5/dab/tutorial_sfm_trajectory_estimation.html',1,'']]],
  ['camera_20preview_20based_20cv_20application_21',['Use OpenCL in Android camera preview based CV application',['https://docs.opencv.org/4.2.0/d7/dbd/tutorial_android_ocl_intro.html',1,'']]],
  ['camshift_22',['camshift',['https://docs.opencv.org/4.2.0/d7/d00/tutorial_meanshift.html',1,'Meanshift and Camshift'],['https://docs.opencv.org/4.2.0/df/def/tutorial_js_meanshift.html',1,'Meanshift and Camshift'],['https://docs.opencv.org/4.2.0/db/df8/tutorial_py_meanshift.html',1,'Meanshift and Camshift']]],
  ['canny_20edge_20detection_23',['canny edge detection',['https://docs.opencv.org/4.2.0/da/d22/tutorial_py_canny.html',1,'Canny Edge Detection'],['https://docs.opencv.org/4.2.0/d7/de1/tutorial_js_canny.html',1,'Canny Edge Detection']]],
  ['canny_20edge_20detector_24',['Canny Edge Detector',['https://docs.opencv.org/4.2.0/da/d5c/tutorial_canny_detector.html',1,'']]],
  ['capture_25',['capture',['https://docs.opencv.org/4.2.0/df/d6c/tutorial_js_face_detection_camera.html',1,'Face Detection in Video Capture'],['https://docs.opencv.org/4.2.0/d8/d54/tutorial_js_imgproc_camera.html',1,'Image Processing for Video Capture']]],
  ['capture_20gray_20code_20pattern_20tutorial_26',['Capture Gray code pattern tutorial',['https://docs.opencv.org/4.2.0/db/d56/tutorial_capture_graycode_pattern.html',1,'']]],
  ['capture_20sinusoidal_20pattern_20tutorial_27',['Capture Sinusoidal pattern tutorial',['https://docs.opencv.org/4.2.0/d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'']]],
  ['cascade_20classifier_28',['Cascade Classifier',['https://docs.opencv.org/4.2.0/db/d28/tutorial_cascade_classifier.html',1,'']]],
  ['cascade_20classifier_20training_29',['Cascade Classifier Training',['https://docs.opencv.org/4.2.0/dc/d88/tutorial_traincascade.html',1,'']]],
  ['cascades_30',['cascades',['https://docs.opencv.org/4.2.0/d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades'],['https://docs.opencv.org/4.2.0/d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['causing_20optical_20illusions_31',['Processing images causing optical illusions',['https://docs.opencv.org/4.2.0/d7/d8f/tutorial_bioinspired_retina_illusion.html',1,'']]],
  ['cdt_32',['Using OpenCV with Eclipse (plugin CDT)',['https://docs.opencv.org/4.2.0/d7/d16/tutorial_linux_eclipse.html',1,'']]],
  ['changelog_33',['Face module changelog',['https://docs.opencv.org/4.2.0/d9/d47/face_changelog.html',1,'']]],
  ['changing_20colorspaces_34',['changing colorspaces',['https://docs.opencv.org/4.2.0/df/d9d/tutorial_py_colorspaces.html',1,'Changing Colorspaces'],['https://docs.opencv.org/4.2.0/db/d64/tutorial_js_colorspaces.html',1,'Changing Colorspaces']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_35',['Changing the contrast and brightness of an image!',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['charuco_36',['Calibration with ArUco and ChArUco',['https://docs.opencv.org/4.2.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['charuco_20corners_37',['Detection of ChArUco Corners',['https://docs.opencv.org/4.2.0/df/d4a/tutorial_charuco_detection.html',1,'']]],
  ['check_20pnsr_20and_20ssim_20on_20the_20gpu_38',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['chessboard_39',['Camera calibration with square chessboard',['https://docs.opencv.org/4.2.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['circle_20transform_40',['circle transform',['https://docs.opencv.org/4.2.0/da/d53/tutorial_py_houghcircles.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d4/d70/tutorial_hough_circle.html',1,'Hough Circle Transform'],['https://docs.opencv.org/4.2.0/d3/de5/tutorial_js_houghcircles.html',1,'Hough Circle Transform']]],
  ['circles_20for_20contours_41',['Creating Bounding boxes and circles for contours',['https://docs.opencv.org/4.2.0/da/d0c/tutorial_bounding_rects_circles.html',1,'']]],
  ['class_42',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['class_20hierarchy_43',['The class hierarchy',['https://eigen.tuxfamily.org/dox/TopicClassHierarchy.html',1,'']]],
  ['classes_44',['Extending MatrixBase (and other classes)',['https://eigen.tuxfamily.org/dox/TopicCustomizing_Plugins.html',1,'']]],
  ['classification_20and_20pose_20estimation_45',['CNN for 3D Object Classification and Pose Estimation',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'']]],
  ['classifier_46',['Cascade Classifier',['https://docs.opencv.org/4.2.0/db/d28/tutorial_cascade_classifier.html',1,'']]],
  ['classifier_20training_47',['Cascade Classifier Training',['https://docs.opencv.org/4.2.0/dc/d88/tutorial_traincascade.html',1,'']]],
  ['classify_48',['Classify',['https://docs.opencv.org/4.2.0/df/d38/tutorial_feature_classification.html',1,'']]],
  ['clojure_49',['Introduction to OpenCV Development with Clojure',['https://docs.opencv.org/4.2.0/d7/d1e/tutorial_clojure_dev_intro.html',1,'']]],
  ['clustering_50',['clustering',['https://docs.opencv.org/4.2.0/d9/d70/tutorial_py_kmeans_index.html',1,'K-Means Clustering'],['https://docs.opencv.org/4.2.0/de/d4d/tutorial_py_kmeans_understanding.html',1,'Understanding K-Means Clustering']]],
  ['clustering_20in_20opencv_51',['K-Means Clustering in OpenCV',['https://docs.opencv.org/4.2.0/d1/d5c/tutorial_py_kmeans_opencv.html',1,'']]],
  ['cmake_52',['Using OpenCV with gcc and CMake',['https://docs.opencv.org/4.2.0/db/df5/tutorial_linux_gcc_cmake.html',1,'']]],
  ['cmake_20projects_53',['Using Eigen in CMake Projects',['https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html',1,'']]],
  ['cmake_20version_203_209_201_54',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['https://docs.opencv.org/4.2.0/db/d4c/tutorial_install_tesseract.html',1,'']]],
  ['cn_20tracker_55',['Customizing the CN Tracker',['https://docs.opencv.org/4.2.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'']]],
  ['cnn_20for_203d_20object_20classification_20and_20pose_20estimation_56',['CNN for 3D Object Classification and Pose Estimation',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'']]],
  ['cnns_57',['cnns',['https://docs.opencv.org/4.2.0/d2/da2/tutorial_dnn_objdetect.html',1,'Object Detection using CNNs'],['https://docs.opencv.org/4.2.0/d8/df8/tutorial_table_of_content_dnn_superres.html',1,'Super Resolution using CNNs']]],
  ['code_58',['code',['https://docs.opencv.org/4.2.0/d9/dab/tutorial_homography.html',1,'Basic concepts of the homography explained with code'],['https://docs.opencv.org/4.2.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'How to use the OpenCV parallel_for_ to parallelize your code']]],
  ['code_20pattern_20tutorial_59',['code pattern tutorial',['https://docs.opencv.org/4.2.0/db/d56/tutorial_capture_graycode_pattern.html',1,'Capture Gray code pattern tutorial'],['https://docs.opencv.org/4.2.0/dc/da9/tutorial_decode_graycode_pattern.html',1,'Decode Gray code pattern tutorial']]],
  ['color_20conversions_60',['Color conversions',['https://docs.opencv.org/4.2.0/de/d25/imgproc_color_conversions.html',1,'']]],
  ['color_20palette_61',['Trackbar as the Color Palette',['https://docs.opencv.org/4.2.0/d9/dc8/tutorial_py_trackbar.html',1,'']]],
  ['colorspaces_62',['colorspaces',['https://docs.opencv.org/4.2.0/df/d9d/tutorial_py_colorspaces.html',1,'Changing Colorspaces'],['https://docs.opencv.org/4.2.0/db/d64/tutorial_js_colorspaces.html',1,'Changing Colorspaces']]],
  ['common_20pitfalls_63',['Common pitfalls',['https://eigen.tuxfamily.org/dox/TopicPitfalls.html',1,'']]],
  ['comparison_64',['Histogram Comparison',['https://docs.opencv.org/4.2.0/d8/dc8/tutorial_histogram_comparison.html',1,'']]],
  ['compatible_20depth_20sensors_65',['compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors'],['https://docs.opencv.org/4.2.0/d7/d6f/tutorial_kinect_openni.html',1,'Using Kinect and other OpenNI compatible depth sensors']]],
  ['compilation_20for_20arm_20based_20linux_20systems_66',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['component_20analysis_20pca_67',['Introduction to Principal Component Analysis (PCA)',['https://docs.opencv.org/4.2.0/d1/dee/tutorial_introduction_to_pca.html',1,'']]],
  ['computational_20photography_68',['Computational Photography',['https://docs.opencv.org/4.2.0/d0/d07/tutorial_py_table_of_contents_photo.html',1,'']]],
  ['computational_20photography_20photo_20module_69',['Computational photography (photo module)',['https://docs.opencv.org/4.2.0/da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['computer_20vision_20applications_70',['Interactive Visual Debugging of Computer Vision applications',['https://docs.opencv.org/4.2.0/d7/dcf/tutorial_cvv_introduction.html',1,'']]],
  ['computer_20vision_20cuda_20module_71',['GPU-Accelerated Computer Vision (cuda module)',['https://docs.opencv.org/4.2.0/da/d2c/tutorial_table_of_content_gpu.html',1,'']]],
  ['computing_20sdk_20compatible_20depth_20sensors_72',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['concepts_20of_20the_20homography_20explained_20with_20code_73',['Basic concepts of the homography explained with code',['https://docs.opencv.org/4.2.0/d9/dab/tutorial_homography.html',1,'']]],
  ['configuration_74',['Camera Configuration',['../cameraconfig.html',1,'']]],
  ['container_75',['Mat - The Basic Image Container',['https://docs.opencv.org/4.2.0/d6/d6d/tutorial_mat_the_basic_image_container.html',1,'']]],
  ['contour_20features_76',['contour features',['https://docs.opencv.org/4.2.0/dc/dcf/tutorial_js_contour_features.html',1,'Contour Features'],['https://docs.opencv.org/4.2.0/dd/d49/tutorial_py_contour_features.html',1,'Contour Features']]],
  ['contour_20properties_77',['contour properties',['https://docs.opencv.org/4.2.0/da/dc1/tutorial_js_contour_properties.html',1,'Contour Properties'],['https://docs.opencv.org/4.2.0/d1/d32/tutorial_py_contour_properties.html',1,'Contour Properties']]],
  ['contours_78',['contours',['https://docs.opencv.org/4.2.0/da/d0c/tutorial_bounding_rects_circles.html',1,'Creating Bounding boxes and circles for contours'],['https://docs.opencv.org/4.2.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'Creating Bounding rotated boxes and ellipses for contours']]],
  ['contours_20_3a_20getting_20started_79',['contours : getting started',['https://docs.opencv.org/4.2.0/d5/daa/tutorial_js_contours_begin.html',1,'Contours : Getting Started'],['https://docs.opencv.org/4.2.0/d4/d73/tutorial_py_contours_begin.html',1,'Contours : Getting Started']]],
  ['contours_20_3a_20more_20functions_80',['contours : more functions',['https://docs.opencv.org/4.2.0/d5/d45/tutorial_py_contours_more_functions.html',1,'Contours : More Functions'],['https://docs.opencv.org/4.2.0/d8/d1c/tutorial_js_contours_more_functions.html',1,'Contours : More Functions']]],
  ['contours_20hierarchy_81',['contours hierarchy',['https://docs.opencv.org/4.2.0/d9/d8b/tutorial_py_contours_hierarchy.html',1,'Contours Hierarchy'],['https://docs.opencv.org/4.2.0/da/d0a/tutorial_js_contours_hierarchy.html',1,'Contours Hierarchy']]],
  ['contours_20in_20opencv_82',['Contours in OpenCV',['https://docs.opencv.org/4.2.0/d3/d05/tutorial_py_table_of_contents_contours.html',1,'']]],
  ['contours_20in_20opencv_20js_83',['Contours in OpenCV.js',['https://docs.opencv.org/4.2.0/d0/d43/tutorial_js_table_of_contents_contours.html',1,'']]],
  ['contours_20in_20your_20image_84',['Finding contours in your image',['https://docs.opencv.org/4.2.0/df/d0d/tutorial_find_contours.html',1,'']]],
  ['contrast_20and_20brightness_20of_20an_20image_85',['Changing the contrast and brightness of an image!',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['contrib_20modules_86',['Tutorials for contrib modules',['https://docs.opencv.org/4.2.0/d3/d81/tutorial_contrib_root.html',1,'']]],
  ['conversions_87',['Color conversions',['https://docs.opencv.org/4.2.0/de/d25/imgproc_color_conversions.html',1,'']]],
  ['convex_20hull_88',['Convex Hull',['https://docs.opencv.org/4.2.0/d7/d1d/tutorial_hull.html',1,'']]],
  ['core_20functionality_20core_20module_89',['The Core Functionality (core module)',['https://docs.opencv.org/4.2.0/de/d7a/tutorial_table_of_content_core.html',1,'']]],
  ['core_20operations_90',['core operations',['https://docs.opencv.org/4.2.0/d1/d78/tutorial_js_table_of_contents_core.html',1,'Core Operations'],['https://docs.opencv.org/4.2.0/d7/d16/tutorial_py_table_of_contents_core.html',1,'Core Operations']]],
  ['corner_20detection_91',['corner detection',['https://docs.opencv.org/4.2.0/df/d0c/tutorial_py_fast.html',1,'FAST Algorithm for Corner Detection'],['https://docs.opencv.org/4.2.0/dc/d0d/tutorial_py_features_harris.html',1,'Harris Corner Detection']]],
  ['corner_20detector_92',['corner detector',['https://docs.opencv.org/4.2.0/d9/dbc/tutorial_generic_corner_detector.html',1,'Creating your own corner detector'],['https://docs.opencv.org/4.2.0/d4/d7d/tutorial_harris_detector.html',1,'Harris corner detector'],['https://docs.opencv.org/4.2.0/d8/dd8/tutorial_good_features_to_track.html',1,'Shi-Tomasi corner detector']]],
  ['corner_20detector_20good_20features_20to_20track_93',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['corners_94',['Detection of ChArUco Corners',['https://docs.opencv.org/4.2.0/df/d4a/tutorial_charuco_detection.html',1,'']]],
  ['corners_20location_20in_20subpixels_95',['Detecting corners location in subpixels',['https://docs.opencv.org/4.2.0/dd/d92/tutorial_corner_subpixels.html',1,'']]],
  ['create_20calibration_20pattern_96',['Create calibration pattern',['https://docs.opencv.org/4.2.0/da/d0d/tutorial_camera_calibration_pattern.html',1,'']]],
  ['creating_20a_203d_20histogram_97',['Creating a 3D histogram',['https://docs.opencv.org/4.2.0/d1/d1d/tutorial_histo3D.html',1,'']]],
  ['creating_20a_20video_20with_20opencv_98',['Creating a video with OpenCV',['https://docs.opencv.org/4.2.0/d7/d9e/tutorial_video_write.html',1,'']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours_99',['Creating Bounding boxes and circles for contours',['https://docs.opencv.org/4.2.0/da/d0c/tutorial_bounding_rects_circles.html',1,'']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours_100',['Creating Bounding rotated boxes and ellipses for contours',['https://docs.opencv.org/4.2.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'']]],
  ['creating_20groups_101',['Creating Groups',['https://docs.opencv.org/4.2.0/d1/d8b/tutorial_hdf_create_groups.html',1,'']]],
  ['creating_20widgets_102',['Creating Widgets',['https://docs.opencv.org/4.2.0/d2/d64/tutorial_creating_widgets.html',1,'']]],
  ['creating_20writing_20and_20reading_20datasets_103',['Creating, Writing and Reading Datasets',['https://docs.opencv.org/4.2.0/d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'']]],
  ['creating_20your_20own_20corner_20detector_104',['Creating your own corner detector',['https://docs.opencv.org/4.2.0/d9/dbc/tutorial_generic_corner_detector.html',1,'']]],
  ['creative_20senz3d_20and_20other_20intel_20perceptual_20computing_20sdk_20compatible_20depth_20sensors_105',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems_106',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects_107',['Cross referencing OpenCV from other Doxygen projects',['https://docs.opencv.org/4.2.0/d3/dff/tutorial_cross_referencing.html',1,'']]],
  ['cuda_108',['Building OpenCV for Tegra with CUDA',['https://docs.opencv.org/4.2.0/d6/d15/tutorial_building_tegra_cuda.html',1,'']]],
  ['cuda_20kernels_109',['Using Eigen in CUDA kernels',['https://eigen.tuxfamily.org/dox/TopicCUDA.html',1,'']]],
  ['cuda_20module_110',['GPU-Accelerated Computer Vision (cuda module)',['https://docs.opencv.org/4.2.0/da/d2c/tutorial_table_of_content_gpu.html',1,'']]],
  ['cuda_20module_20introduction_111',['CUDA Module Introduction',['https://docs.opencv.org/4.2.0/d2/dbc/cuda_intro.html',1,'']]],
  ['custom_20deep_20learning_20layers_20support_112',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['custom_20scalar_20types_113',['Using custom scalar types',['https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html',1,'']]],
  ['customizing_20eigen_114',['Extending/Customizing Eigen',['https://eigen.tuxfamily.org/dox/UserManual_CustomizingEigen.html',1,'']]],
  ['customizing_20the_20cn_20tracker_115',['Customizing the CN Tracker',['https://docs.opencv.org/4.2.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'']]],
  ['cv_20application_116',['Use OpenCL in Android camera preview based CV application',['https://docs.opencv.org/4.2.0/d7/dbd/tutorial_android_ocl_intro.html',1,'']]],
  ['cv_3a_3acuda_3a_3agpumat_20with_20thrust_117',['Using a cv::cuda::GpuMat with thrust',['https://docs.opencv.org/4.2.0/d8/db9/tutorial_gpu_thrust_interop.html',1,'']]]
];
