var searchData=
[
  ['calibration_20with_20aruco_20and_20charuco_0',['Calibration with ArUco and ChArUco',['https://docs.opencv.org/4.2.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['camera_20calibration_1',['Camera Calibration',['https://docs.opencv.org/4.2.0/dc/dbb/tutorial_py_calibration.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_2',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'']]],
  ['camera_20calibration_20and_203d_20reconstruction_20_28calib3d_20module_29_3',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['camera_20calibration_20with_20opencv_4',['Camera calibration With OpenCV',['https://docs.opencv.org/4.2.0/d4/d94/tutorial_camera_calibration.html',1,'']]],
  ['camera_20calibration_20with_20square_20chessboard_5',['Camera calibration with square chessboard',['https://docs.opencv.org/4.2.0/dc/d43/tutorial_camera_calibration_square_chess.html',1,'']]],
  ['camera_20configuration_6',['Camera Configuration',['../cameraconfig.html',1,'']]],
  ['camera_20motion_20estimation_7',['Camera Motion Estimation',['https://docs.opencv.org/4.2.0/d5/dab/tutorial_sfm_trajectory_estimation.html',1,'']]],
  ['canny_20edge_20detection_8',['Canny Edge Detection',['https://docs.opencv.org/4.2.0/d7/de1/tutorial_js_canny.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/da/d22/tutorial_py_canny.html',1,'(Global Namespace)']]],
  ['canny_20edge_20detector_9',['Canny Edge Detector',['https://docs.opencv.org/4.2.0/da/d5c/tutorial_canny_detector.html',1,'']]],
  ['capture_20gray_20code_20pattern_20tutorial_10',['Capture Gray code pattern tutorial',['https://docs.opencv.org/4.2.0/db/d56/tutorial_capture_graycode_pattern.html',1,'']]],
  ['capture_20sinusoidal_20pattern_20tutorial_11',['Capture Sinusoidal pattern tutorial',['https://docs.opencv.org/4.2.0/d0/de8/tutorial_capture_sinusoidal_pattern.html',1,'']]],
  ['cascade_20classifier_12',['Cascade Classifier',['https://docs.opencv.org/4.2.0/db/d28/tutorial_cascade_classifier.html',1,'']]],
  ['cascade_20classifier_20training_13',['Cascade Classifier Training',['https://docs.opencv.org/4.2.0/dc/d88/tutorial_traincascade.html',1,'']]],
  ['changing_20colorspaces_14',['Changing Colorspaces',['https://docs.opencv.org/4.2.0/db/d64/tutorial_js_colorspaces.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/df/d9d/tutorial_py_colorspaces.html',1,'(Global Namespace)']]],
  ['changing_20the_20contrast_20and_20brightness_20of_20an_20image_21_15',['Changing the contrast and brightness of an image!',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['classify_16',['Classify',['https://docs.opencv.org/4.2.0/df/d38/tutorial_feature_classification.html',1,'']]],
  ['cnn_20for_203d_20object_20classification_20and_20pose_20estimation_17',['CNN for 3D Object Classification and Pose Estimation',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'']]],
  ['color_20conversions_18',['Color conversions',['https://docs.opencv.org/4.2.0/de/d25/imgproc_color_conversions.html',1,'']]],
  ['common_20pitfalls_19',['Common pitfalls',['https://eigen.tuxfamily.org/dox/TopicPitfalls.html',1,'']]],
  ['computational_20photography_20',['Computational Photography',['https://docs.opencv.org/4.2.0/d0/d07/tutorial_py_table_of_contents_photo.html',1,'']]],
  ['computational_20photography_20_28photo_20module_29_21',['Computational photography (photo module)',['https://docs.opencv.org/4.2.0/da/de7/tutorial_table_of_content_photo.html',1,'']]],
  ['contour_20features_22',['Contour Features',['https://docs.opencv.org/4.2.0/dc/dcf/tutorial_js_contour_features.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/dd/d49/tutorial_py_contour_features.html',1,'(Global Namespace)']]],
  ['contour_20properties_23',['Contour Properties',['https://docs.opencv.org/4.2.0/da/dc1/tutorial_js_contour_properties.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d1/d32/tutorial_py_contour_properties.html',1,'(Global Namespace)']]],
  ['contours_20_3a_20getting_20started_24',['Contours : Getting Started',['https://docs.opencv.org/4.2.0/d5/daa/tutorial_js_contours_begin.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d4/d73/tutorial_py_contours_begin.html',1,'(Global Namespace)']]],
  ['contours_20_3a_20more_20functions_25',['Contours : More Functions',['https://docs.opencv.org/4.2.0/d8/d1c/tutorial_js_contours_more_functions.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d5/d45/tutorial_py_contours_more_functions.html',1,'(Global Namespace)']]],
  ['contours_20hierarchy_26',['Contours Hierarchy',['https://docs.opencv.org/4.2.0/da/d0a/tutorial_js_contours_hierarchy.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d9/d8b/tutorial_py_contours_hierarchy.html',1,'(Global Namespace)']]],
  ['contours_20in_20opencv_27',['Contours in OpenCV',['https://docs.opencv.org/4.2.0/d3/d05/tutorial_py_table_of_contents_contours.html',1,'']]],
  ['contours_20in_20opencv_2ejs_28',['Contours in OpenCV.js',['https://docs.opencv.org/4.2.0/d0/d43/tutorial_js_table_of_contents_contours.html',1,'']]],
  ['convex_20hull_29',['Convex Hull',['https://docs.opencv.org/4.2.0/d7/d1d/tutorial_hull.html',1,'']]],
  ['core_20operations_30',['Core Operations',['https://docs.opencv.org/4.2.0/d1/d78/tutorial_js_table_of_contents_core.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d7/d16/tutorial_py_table_of_contents_core.html',1,'(Global Namespace)']]],
  ['create_20calibration_20pattern_31',['Create calibration pattern',['https://docs.opencv.org/4.2.0/da/d0d/tutorial_camera_calibration_pattern.html',1,'']]],
  ['creating_20a_203d_20histogram_32',['Creating a 3D histogram',['https://docs.opencv.org/4.2.0/d1/d1d/tutorial_histo3D.html',1,'']]],
  ['creating_20a_20video_20with_20opencv_33',['Creating a video with OpenCV',['https://docs.opencv.org/4.2.0/d7/d9e/tutorial_video_write.html',1,'']]],
  ['creating_20bounding_20boxes_20and_20circles_20for_20contours_34',['Creating Bounding boxes and circles for contours',['https://docs.opencv.org/4.2.0/da/d0c/tutorial_bounding_rects_circles.html',1,'']]],
  ['creating_20bounding_20rotated_20boxes_20and_20ellipses_20for_20contours_35',['Creating Bounding rotated boxes and ellipses for contours',['https://docs.opencv.org/4.2.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'']]],
  ['creating_20groups_36',['Creating Groups',['https://docs.opencv.org/4.2.0/d1/d8b/tutorial_hdf_create_groups.html',1,'']]],
  ['creating_20widgets_37',['Creating Widgets',['https://docs.opencv.org/4.2.0/d2/d64/tutorial_creating_widgets.html',1,'']]],
  ['creating_20your_20own_20corner_20detector_38',['Creating your own corner detector',['https://docs.opencv.org/4.2.0/d9/dbc/tutorial_generic_corner_detector.html',1,'']]],
  ['creating_2c_20writing_20and_20reading_20datasets_39',['Creating, Writing and Reading Datasets',['https://docs.opencv.org/4.2.0/d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'']]],
  ['cross_20compilation_20for_20arm_20based_20linux_20systems_40',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['cross_20referencing_20opencv_20from_20other_20doxygen_20projects_41',['Cross referencing OpenCV from other Doxygen projects',['https://docs.opencv.org/4.2.0/d3/dff/tutorial_cross_referencing.html',1,'']]],
  ['cuda_20module_20introduction_42',['CUDA Module Introduction',['https://docs.opencv.org/4.2.0/d2/dbc/cuda_intro.html',1,'']]],
  ['custom_20deep_20learning_20layers_20support_43',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['customizing_20the_20cn_20tracker_44',['Customizing the CN Tracker',['https://docs.opencv.org/4.2.0/dc/db8/tutorial_customizing_cn_tracker.html',1,'']]]
];
