var searchData=
[
  ['harris_20corner_20detection_0',['Harris Corner Detection',['https://docs.opencv.org/4.2.0/dc/d0d/tutorial_py_features_harris.html',1,'']]],
  ['harris_20corner_20detector_1',['Harris corner detector',['https://docs.opencv.org/4.2.0/d4/d7d/tutorial_harris_detector.html',1,'']]],
  ['high_20dynamic_20range_20_28hdr_29_2',['High Dynamic Range (HDR)',['https://docs.opencv.org/4.2.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['high_20dynamic_20range_20imaging_3',['High Dynamic Range Imaging',['https://docs.opencv.org/4.2.0/d3/db7/tutorial_hdr_imaging.html',1,'']]],
  ['high_20level_20gui_20and_20media_20_28highgui_20module_29_4',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['high_20level_20stitching_20api_20_28stitcher_20class_29_5',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['high_2dlevel_20design_20overview_6',['High-level design overview',['https://docs.opencv.org/4.2.0/de/d4d/gapi_hld.html',1,'']]],
  ['histogram_20_2d_203_20_3a_20histogram_20backprojection_7',['Histogram - 3 : Histogram Backprojection',['https://docs.opencv.org/4.2.0/dd/d4d/tutorial_js_histogram_backprojection.html',1,'']]],
  ['histogram_20_2d_204_20_3a_20histogram_20backprojection_8',['Histogram - 4 : Histogram Backprojection',['https://docs.opencv.org/4.2.0/dc/df6/tutorial_py_histogram_backprojection.html',1,'']]],
  ['histogram_20calculation_9',['Histogram Calculation',['https://docs.opencv.org/4.2.0/d8/dbc/tutorial_histogram_calculation.html',1,'']]],
  ['histogram_20comparison_10',['Histogram Comparison',['https://docs.opencv.org/4.2.0/d8/dc8/tutorial_histogram_comparison.html',1,'']]],
  ['histogram_20equalization_11',['Histogram Equalization',['https://docs.opencv.org/4.2.0/d4/d1b/tutorial_histogram_equalization.html',1,'']]],
  ['histograms_20_2d_201_20_3a_20find_2c_20plot_2c_20analyze_20_21_21_21_12',['Histograms - 1 : Find, Plot, Analyze !!!',['https://docs.opencv.org/4.2.0/d7/d32/tutorial_js_histogram_begins.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d1/db7/tutorial_py_histogram_begins.html',1,'(Global Namespace)']]],
  ['histograms_20_2d_202_3a_20histogram_20equalization_13',['Histograms - 2: Histogram Equalization',['https://docs.opencv.org/4.2.0/d2/d74/tutorial_js_histogram_equalization.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d5/daf/tutorial_py_histogram_equalization.html',1,'(Global Namespace)']]],
  ['histograms_20_2d_203_20_3a_202d_20histograms_14',['Histograms - 3 : 2D Histograms',['https://docs.opencv.org/4.2.0/dd/d0d/tutorial_py_2d_histogram.html',1,'']]],
  ['histograms_20in_20opencv_15',['Histograms in OpenCV',['https://docs.opencv.org/4.2.0/de/db2/tutorial_py_table_of_contents_histograms.html',1,'']]],
  ['histograms_20in_20opencv_2ejs_16',['Histograms in OpenCV.js',['https://docs.opencv.org/4.2.0/d5/dc0/tutorial_js_table_of_contents_histograms.html',1,'']]],
  ['hit_2dor_2dmiss_17',['Hit-or-Miss',['https://docs.opencv.org/4.2.0/db/d06/tutorial_hitOrMiss.html',1,'']]],
  ['hough_20circle_20transform_18',['Hough Circle Transform',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_hough_circle.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d3/de5/tutorial_js_houghcircles.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/da/d53/tutorial_py_houghcircles.html',1,'(Global Namespace)']]],
  ['hough_20line_20transform_19',['Hough Line Transform',['https://docs.opencv.org/4.2.0/d9/db0/tutorial_hough_lines.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d3/de6/tutorial_js_houghlines.html',1,'(Global Namespace)'],['https://docs.opencv.org/4.2.0/d6/d10/tutorial_py_houghlines.html',1,'(Global Namespace)']]],
  ['how_20opencv_2dpython_20bindings_20works_3f_20',['How OpenCV-Python Bindings Works?',['https://docs.opencv.org/4.2.0/da/d49/tutorial_py_bindings_basics.html',1,'']]],
  ['how_20to_20build_20applications_20with_20opencv_20inside_20the_20_22microsoft_20visual_20studio_22_21',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['how_20to_20enable_20halide_20backend_20for_20improve_20efficiency_22',['How to enable Halide backend for improve efficiency',['https://docs.opencv.org/4.2.0/de/d37/tutorial_dnn_halide.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20in_20browser_23',['How to run deep networks in browser',['https://docs.opencv.org/4.2.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['how_20to_20run_20deep_20networks_20on_20android_20device_24',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['how_20to_20scan_20images_2c_20lookup_20tables_20and_20time_20measurement_20with_20opencv_25',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['how_20to_20schedule_20your_20network_20for_20halide_20backend_26',['How to schedule your network for Halide backend',['https://docs.opencv.org/4.2.0/de/d5d/tutorial_dnn_halide_scheduling.html',1,'']]],
  ['how_20to_20use_20background_20subtraction_20methods_27',['How to Use Background Subtraction Methods',['https://docs.opencv.org/4.2.0/d1/dc5/tutorial_background_subtraction.html',1,'']]],
  ['how_20to_20use_20the_20opencv_20parallel_5ffor_5f_20to_20parallelize_20your_20code_28',['How to use the OpenCV parallel_for_ to parallelize your code',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_how_to_use_OpenCV_parallel_for_.html',1,'']]]
];
