var searchData=
[
  ['vector_20machines_0',['Introduction to Support Vector Machines',['https://docs.opencv.org/4.2.0/d1/d73/tutorial_introduction_to_svm.html',1,'']]],
  ['vector_20machines_20for_20non_20linearly_20separable_20data_1',['Support Vector Machines for Non-Linearly Separable Data',['https://docs.opencv.org/4.2.0/d0/dcc/tutorial_non_linear_svms.html',1,'']]],
  ['vector_20machines_20svm_2',['Support Vector Machines (SVM)',['https://docs.opencv.org/4.2.0/d3/d02/tutorial_py_svm_index.html',1,'']]],
  ['vectorization_3',['Vectorization',['https://eigen.tuxfamily.org/dox/TopicVectorization.html',1,'']]],
  ['version_202_2014_201_20and_20cmake_20version_203_209_201_4',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['https://docs.opencv.org/4.2.0/db/d4c/tutorial_install_tesseract.html',1,'']]],
  ['vertical_20lines_20by_20using_20morphological_20operations_5',['Extract horizontal and vertical lines by using morphological operations',['https://docs.opencv.org/4.2.0/dd/dd7/tutorial_morph_lines_detection.html',1,'']]],
  ['via_20nullary_20expressions_6',['Matrix manipulation via nullary-expressions',['https://eigen.tuxfamily.org/dox/TopicCustomizing_NullaryExpr.html',1,'']]],
  ['video_7',['video',['https://docs.opencv.org/4.2.0/d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'Face landmark detection in a video'],['https://docs.opencv.org/4.2.0/de/d7f/tutorial_dnn_superres_upscale_video.html',1,'Upscaling video']]],
  ['video_20analysis_8',['video analysis',['https://docs.opencv.org/4.2.0/de/db6/tutorial_js_table_of_contents_video.html',1,'Video Analysis'],['https://docs.opencv.org/4.2.0/d3/db0/tutorial_py_table_of_contents_video.html',1,'Video Analysis']]],
  ['video_20analysis_20video_20module_9',['Video analysis (video module)',['https://docs.opencv.org/4.2.0/da/dd0/tutorial_table_of_content_video.html',1,'']]],
  ['video_20capture_10',['video capture',['https://docs.opencv.org/4.2.0/df/d6c/tutorial_js_face_detection_camera.html',1,'Face Detection in Video Capture'],['https://docs.opencv.org/4.2.0/d8/d54/tutorial_js_imgproc_camera.html',1,'Image Processing for Video Capture']]],
  ['video_20i_20o_20with_20opencv_20overview_11',['Video I/O with OpenCV Overview',['https://docs.opencv.org/4.2.0/d0/da7/videoio_overview.html',1,'']]],
  ['video_20input_20and_20output_20videoio_20module_12',['Video Input and Output (videoio module)',['https://docs.opencv.org/4.2.0/df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['video_20input_20with_20opencv_20and_20similarity_20measurement_13',['Video Input with OpenCV and similarity measurement',['https://docs.opencv.org/4.2.0/d5/dc4/tutorial_video_input_psnr_ssim.html',1,'']]],
  ['video_20processing_14',['OpenCV iOS - Video Processing',['https://docs.opencv.org/4.2.0/db/dc8/tutorial_video_processing.html',1,'']]],
  ['video_20with_20opencv_15',['Creating a video with OpenCV',['https://docs.opencv.org/4.2.0/d7/d9e/tutorial_video_write.html',1,'']]],
  ['videoio_20module_16',['Video Input and Output (videoio module)',['https://docs.opencv.org/4.2.0/df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['videos_17',['videos',['https://docs.opencv.org/4.2.0/dd/d00/tutorial_js_video_display.html',1,'Getting Started with Videos'],['https://docs.opencv.org/4.2.0/dd/d43/tutorial_py_video_display.html',1,'Getting Started with Videos']]],
  ['viewing_20in_20memory_20images_20in_20the_20visual_20studio_20debugger_18',['Image Watch: viewing in-memory images in the Visual Studio debugger',['https://docs.opencv.org/4.2.0/d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'']]],
  ['vision_19',['Retina and real-world vision',['https://docs.opencv.org/4.2.0/d3/d86/tutorial_bioinspired_retina_model.html',1,'']]],
  ['vision_20applications_20',['Interactive Visual Debugging of Computer Vision applications',['https://docs.opencv.org/4.2.0/d7/dcf/tutorial_cvv_introduction.html',1,'']]],
  ['vision_20cuda_20module_21',['GPU-Accelerated Computer Vision (cuda module)',['https://docs.opencv.org/4.2.0/da/d2c/tutorial_table_of_content_gpu.html',1,'']]],
  ['visual_20debugging_20of_20computer_20vision_20applications_22',['Interactive Visual Debugging of Computer Vision applications',['https://docs.opencv.org/4.2.0/d7/dcf/tutorial_cvv_introduction.html',1,'']]],
  ['visual_20studio_23',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['visual_20studio_20debugger_24',['Image Watch: viewing in-memory images in the Visual Studio debugger',['https://docs.opencv.org/4.2.0/d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'']]],
  ['viz_25',['viz',['https://docs.opencv.org/4.2.0/d5/d7d/tutorial_launching_viz.html',1,'Launching Viz'],['https://docs.opencv.org/4.2.0/d7/df9/tutorial_table_of_content_viz.html',1,'OpenCV Viz']]]
];
