var searchData=
[
  ['a_203d_20histogram_0',['Creating a 3D histogram',['https://docs.opencv.org/4.2.0/d1/d1d/tutorial_histo3D.html',1,'']]],
  ['a_20cv_3a_3acuda_3a_3agpumat_20with_20thrust_1',['Using a cv::cuda::GpuMat with thrust',['https://docs.opencv.org/4.2.0/d8/db9/tutorial_gpu_thrust_interop.html',1,'']]],
  ['a_20face_20beautification_20algorithm_20with_20g_20api_2',['Implementing a face beautification algorithm with G-API',['https://docs.opencv.org/4.2.0/d4/d48/tutorial_gapi_face_beautification.html',1,'']]],
  ['a_20gradient_20structure_20tensor_3',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['a_20known_20object_4',['Features2D + Homography to find a known object',['https://docs.opencv.org/4.2.0/d7/dff/tutorial_feature_homography.html',1,'']]],
  ['a_20new_20algorithm_20to_20the_20facemark_20api_5',['Adding a new algorithm to the Facemark API',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'']]],
  ['a_20new_20expression_20type_6',['Adding a new expression type',['https://eigen.tuxfamily.org/dox/TopicNewExpressionType.html',1,'']]],
  ['a_20paint_20brush_7',['Mouse as a Paint-Brush',['https://docs.opencv.org/4.2.0/db/d5b/tutorial_py_mouse_handling.html',1,'']]],
  ['a_20simple_20example_8',['What happens inside Eigen, on a simple example',['https://eigen.tuxfamily.org/dox/TopicInsideEigenExample.html',1,'']]],
  ['a_20template_20parameter_20file_9',['Exporting a template parameter file',['https://docs.opencv.org/4.2.0/df/dc0/tutorial_qds_export_parameters.html',1,'']]],
  ['a_20textured_20object_10',['Real Time pose estimation of a textured object',['https://docs.opencv.org/4.2.0/dc/d2c/tutorial_real_time_pose.html',1,'']]],
  ['a_20trackbar_20to_20our_20applications_11',['Adding a Trackbar to our applications!',['https://docs.opencv.org/4.2.0/da/d6a/tutorial_trackbar.html',1,'']]],
  ['a_20trackbar_20to_20your_20application_12',['Add a Trackbar to Your Application',['https://docs.opencv.org/4.2.0/d5/df3/tutorial_js_trackbar.html',1,'']]],
  ['a_20video_13',['Face landmark detection in a video',['https://docs.opencv.org/4.2.0/d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'']]],
  ['a_20video_20with_20opencv_14',['Creating a video with OpenCV',['https://docs.opencv.org/4.2.0/d7/d9e/tutorial_video_write.html',1,'']]],
  ['a_20widget_15',['Pose of a widget',['https://docs.opencv.org/4.2.0/d8/df0/tutorial_widget_pose.html',1,'']]],
  ['accelerated_20computer_20vision_20cuda_20module_16',['GPU-Accelerated Computer Vision (cuda module)',['https://docs.opencv.org/4.2.0/da/d2c/tutorial_table_of_content_gpu.html',1,'']]],
  ['add_20a_20trackbar_20to_20your_20application_17',['Add a Trackbar to Your Application',['https://docs.opencv.org/4.2.0/d5/df3/tutorial_js_trackbar.html',1,'']]],
  ['adding_20a_20new_20algorithm_20to_20the_20facemark_20api_18',['Adding a new algorithm to the Facemark API',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'']]],
  ['adding_20a_20new_20expression_20type_19',['Adding a new expression type',['https://eigen.tuxfamily.org/dox/TopicNewExpressionType.html',1,'']]],
  ['adding_20a_20trackbar_20to_20our_20applications_20',['Adding a Trackbar to our applications!',['https://docs.opencv.org/4.2.0/da/d6a/tutorial_trackbar.html',1,'']]],
  ['adding_20blending_20two_20images_20using_20opencv_21',['Adding (blending) two images using OpenCV',['https://docs.opencv.org/4.2.0/d5/dc4/tutorial_adding_images.html',1,'']]],
  ['adding_20borders_20to_20your_20images_22',['Adding borders to your images',['https://docs.opencv.org/4.2.0/dc/da3/tutorial_copyMakeBorder.html',1,'']]],
  ['affine_20transformations_23',['Affine Transformations',['https://docs.opencv.org/4.2.0/d4/d61/tutorial_warp_affine.html',1,'']]],
  ['akaze_20and_20orb_20planar_20tracking_24',['AKAZE and ORB planar tracking',['https://docs.opencv.org/4.2.0/dc/d16/tutorial_akaze_tracking.html',1,'']]],
  ['akaze_20local_20features_20matching_25',['AKAZE local features matching',['https://docs.opencv.org/4.2.0/db/d70/tutorial_akaze_matching.html',1,'']]],
  ['algorithm_26',['algorithm',['https://docs.opencv.org/4.2.0/dd/dfc/tutorial_js_grabcut.html',1,'Foreground Extraction using GrabCut Algorithm'],['https://docs.opencv.org/4.2.0/d2/dbd/tutorial_distance_transform.html',1,'Image Segmentation with Distance Transform and Watershed Algorithm'],['https://docs.opencv.org/4.2.0/d7/d1c/tutorial_js_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['https://docs.opencv.org/4.2.0/d3/db4/tutorial_py_watershed.html',1,'Image Segmentation with Watershed Algorithm'],['https://docs.opencv.org/4.2.0/d8/d83/tutorial_py_grabcut.html',1,'Interactive Foreground Extraction using GrabCut Algorithm'],['https://docs.opencv.org/4.2.0/dc/dcb/tutorial_xphoto_training_white_balance.html',1,'Training the learning-based white balance algorithm']]],
  ['algorithm_20for_20corner_20detection_27',['FAST Algorithm for Corner Detection',['https://docs.opencv.org/4.2.0/df/d0c/tutorial_py_fast.html',1,'']]],
  ['algorithm_20to_20the_20facemark_20api_28',['Adding a new algorithm to the Facemark API',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'']]],
  ['algorithm_20with_20g_20api_29',['Implementing a face beautification algorithm with G-API',['https://docs.opencv.org/4.2.0/d4/d48/tutorial_gapi_face_beautification.html',1,'']]],
  ['aliasing_30',['Lazy Evaluation and Aliasing',['https://eigen.tuxfamily.org/dox/TopicLazyEvaluation.html',1,'']]],
  ['an_20image_31',['an image',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'Changing the contrast and brightness of an image!'],['https://docs.opencv.org/4.2.0/d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'Face landmark detection in an image'],['https://docs.opencv.org/4.2.0/db/deb/tutorial_display_image.html',1,'Load and Display an Image'],['https://docs.opencv.org/4.2.0/db/d64/tutorial_load_save_image.html',1,'Load, Modify, and Save an Image']]],
  ['analysis_32',['analysis',['https://docs.opencv.org/4.2.0/d8/d09/tutorial_model_analysis.html',1,'Training Model Analysis'],['https://docs.opencv.org/4.2.0/de/db6/tutorial_js_table_of_contents_video.html',1,'Video Analysis'],['https://docs.opencv.org/4.2.0/d3/db0/tutorial_py_table_of_contents_video.html',1,'Video Analysis']]],
  ['analysis_20pca_33',['Introduction to Principal Component Analysis (PCA)',['https://docs.opencv.org/4.2.0/d1/dee/tutorial_introduction_to_pca.html',1,'']]],
  ['analysis_20video_20module_34',['Video analysis (video module)',['https://docs.opencv.org/4.2.0/da/dd0/tutorial_table_of_content_video.html',1,'']]],
  ['analytics_20pipeline_20with_20g_20api_35',['Face analytics pipeline with G-API',['https://docs.opencv.org/4.2.0/d8/d24/tutorial_gapi_interactive_face_detection.html',1,'']]],
  ['analyze_36',['analyze',['https://docs.opencv.org/4.2.0/d1/db7/tutorial_py_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!'],['https://docs.opencv.org/4.2.0/d7/d32/tutorial_js_histogram_begins.html',1,'Histograms - 1 : Find, Plot, Analyze !!!']]],
  ['and_203d_20reconstruction_37',['Camera Calibration and 3D Reconstruction',['https://docs.opencv.org/4.2.0/d9/db7/tutorial_py_table_of_contents_calib3d.html',1,'']]],
  ['and_203d_20reconstruction_20calib3d_20module_38',['Camera calibration and 3D reconstruction (calib3d module)',['https://docs.opencv.org/4.2.0/d6/d55/tutorial_table_of_content_calib3d.html',1,'']]],
  ['and_20aliasing_39',['Lazy Evaluation and Aliasing',['https://eigen.tuxfamily.org/dox/TopicLazyEvaluation.html',1,'']]],
  ['and_20brightness_20of_20an_20image_40',['Changing the contrast and brightness of an image!',['https://docs.opencv.org/4.2.0/d3/dc1/tutorial_basic_linear_transform.html',1,'']]],
  ['and_20camshift_41',['and camshift',['https://docs.opencv.org/4.2.0/d7/d00/tutorial_meanshift.html',1,'Meanshift and Camshift'],['https://docs.opencv.org/4.2.0/db/df8/tutorial_py_meanshift.html',1,'Meanshift and Camshift'],['https://docs.opencv.org/4.2.0/df/def/tutorial_js_meanshift.html',1,'Meanshift and Camshift']]],
  ['and_20charuco_42',['Calibration with ArUco and ChArUco',['https://docs.opencv.org/4.2.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['and_20circles_20for_20contours_43',['Creating Bounding boxes and circles for contours',['https://docs.opencv.org/4.2.0/da/d0c/tutorial_bounding_rects_circles.html',1,'']]],
  ['and_20cmake_44',['Using OpenCV with gcc and CMake',['https://docs.opencv.org/4.2.0/db/df5/tutorial_linux_gcc_cmake.html',1,'']]],
  ['and_20cmake_20version_203_209_201_45',['Tesseract (master) installation by using git-bash (version&gt;=2.14.1) and cmake (version &gt;=3.9.1)',['https://docs.opencv.org/4.2.0/db/d4c/tutorial_install_tesseract.html',1,'']]],
  ['and_20description_46',['Feature Detection and Description',['https://docs.opencv.org/4.2.0/db/d27/tutorial_py_table_of_contents_feature2d.html',1,'']]],
  ['and_20dilating_47',['Eroding and Dilating',['https://docs.opencv.org/4.2.0/db/df6/tutorial_erosion_dilatation.html',1,'']]],
  ['and_20display_20an_20image_48',['Load and Display an Image',['https://docs.opencv.org/4.2.0/db/deb/tutorial_display_image.html',1,'']]],
  ['and_20ellipses_20for_20contours_49',['Creating Bounding rotated boxes and ellipses for contours',['https://docs.opencv.org/4.2.0/de/d62/tutorial_bounding_rotated_ellipses.html',1,'']]],
  ['and_20improvement_20techniques_50',['Performance Measurement and Improvement Techniques',['https://docs.opencv.org/4.2.0/dc/d71/tutorial_py_optimization.html',1,'']]],
  ['and_20its_20use_20for_20image_20processing_51',['Discovering the human retina and its use for image processing',['https://docs.opencv.org/4.2.0/df/dee/tutorial_table_of_content_retina.html',1,'']]],
  ['and_20media_20highgui_20module_52',['High Level GUI and Media (highgui module)',['https://docs.opencv.org/4.2.0/d0/de2/tutorial_table_of_content_highgui.html',1,'']]],
  ['and_20multi_20threading_53',['Eigen and multi-threading',['https://eigen.tuxfamily.org/dox/TopicMultiThreading.html',1,'']]],
  ['and_20orb_20planar_20tracking_54',['AKAZE and ORB planar tracking',['https://docs.opencv.org/4.2.0/dc/d16/tutorial_akaze_tracking.html',1,'']]],
  ['and_20other_20classes_55',['Extending MatrixBase (and other classes)',['https://eigen.tuxfamily.org/dox/TopicCustomizing_Plugins.html',1,'']]],
  ['and_20other_20intel_20perceptual_20computing_20sdk_20compatible_20depth_20sensors_56',['Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'']]],
  ['and_20other_20openni_20compatible_20depth_20sensors_57',['Using Kinect and other OpenNI compatible depth sensors',['https://docs.opencv.org/4.2.0/d7/d6f/tutorial_kinect_openni.html',1,'']]],
  ['and_20output_20imgcodecs_20module_58',['Image Input and Output (imgcodecs module)',['https://docs.opencv.org/4.2.0/da/d8f/tutorial_table_of_content_imgcodecs.html',1,'']]],
  ['and_20output_20using_20xml_20and_20yaml_20files_59',['File Input and Output using XML and YAML files',['https://docs.opencv.org/4.2.0/dd/d74/tutorial_file_input_output_with_xml_yml.html',1,'']]],
  ['and_20output_20videoio_20module_60',['Video Input and Output (videoio module)',['https://docs.opencv.org/4.2.0/df/d2c/tutorial_table_of_content_videoio.html',1,'']]],
  ['and_20pose_20estimation_61',['CNN for 3D Object Classification and Pose Estimation',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_table_of_content_cnn_3dobj.html',1,'']]],
  ['and_20reading_20datasets_62',['Creating, Writing and Reading Datasets',['https://docs.opencv.org/4.2.0/d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'']]],
  ['and_20real_20world_20vision_63',['Retina and real-world vision',['https://docs.opencv.org/4.2.0/d3/d86/tutorial_bioinspired_retina_model.html',1,'']]],
  ['and_20rotated_20brief_64',['ORB (Oriented FAST and Rotated BRIEF)',['https://docs.opencv.org/4.2.0/d1/d89/tutorial_py_orb.html',1,'']]],
  ['and_20save_20an_20image_65',['Load, Modify, and Save an Image',['https://docs.opencv.org/4.2.0/db/d64/tutorial_load_save_image.html',1,'']]],
  ['and_20similarity_20measurement_66',['Video Input with OpenCV and similarity measurement',['https://docs.opencv.org/4.2.0/d5/dc4/tutorial_video_input_psnr_ssim.html',1,'']]],
  ['and_20ssim_20on_20the_20gpu_67',['Similarity check (PNSR and SSIM) on the GPU',['https://docs.opencv.org/4.2.0/dd/d3d/tutorial_gpu_basics_similarity.html',1,'']]],
  ['and_20text_20with_20opencv_68',['Random generator and text with OpenCV',['https://docs.opencv.org/4.2.0/df/d61/tutorial_random_generator_and_text.html',1,'']]],
  ['and_20time_20measurement_20with_20opencv_69',['How to scan images, lookup tables and time measurement with OpenCV',['https://docs.opencv.org/4.2.0/db/da5/tutorial_how_to_scan_images.html',1,'']]],
  ['and_20tutorials_70',['Introduction to OpenCV.js and Tutorials',['https://docs.opencv.org/4.2.0/df/d0a/tutorial_js_intro.html',1,'']]],
  ['and_20typename_20keywords_20in_20c_71',['The template and typename keywords in C++',['https://eigen.tuxfamily.org/dox/TopicTemplateKeyword.html',1,'']]],
  ['and_20vertical_20lines_20by_20using_20morphological_20operations_72',['Extract horizontal and vertical lines by using morphological operations',['https://docs.opencv.org/4.2.0/dd/dd7/tutorial_morph_lines_detection.html',1,'']]],
  ['and_20watershed_20algorithm_73',['Image Segmentation with Distance Transform and Watershed Algorithm',['https://docs.opencv.org/4.2.0/d2/dbd/tutorial_distance_transform.html',1,'']]],
  ['and_20writing_20attributes_74',['Reading and Writing Attributes',['https://docs.opencv.org/4.2.0/d5/d10/tutorial_hdf_read_write_attributes.html',1,'']]],
  ['android_20camera_20preview_20based_20cv_20application_75',['Use OpenCL in Android camera preview based CV application',['https://docs.opencv.org/4.2.0/d7/dbd/tutorial_android_ocl_intro.html',1,'']]],
  ['android_20development_76',['Introduction into Android Development',['https://docs.opencv.org/4.2.0/d9/d3f/tutorial_android_dev_intro.html',1,'']]],
  ['android_20development_20with_20opencv_77',['Android Development with OpenCV',['https://docs.opencv.org/4.2.0/d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'']]],
  ['android_20device_78',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['anisotropic_20image_20segmentation_20by_20a_20gradient_20structure_20tensor_79',['Anisotropic image segmentation by a gradient structure tensor',['https://docs.opencv.org/4.2.0/d4/d70/tutorial_anisotropic_image_segmentation_by_a_gst.html',1,'']]],
  ['anisotropic_20image_20segmentation_20on_20g_20api_80',['Porting anisotropic image segmentation on G-API',['https://docs.opencv.org/4.2.0/d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'']]],
  ['api_81',['api',['https://docs.opencv.org/4.2.0/d4/d3e/tutorial_facemark_add_algorithm.html',1,'Adding a new algorithm to the Facemark API'],['https://docs.opencv.org/4.2.0/d8/d24/tutorial_gapi_interactive_face_detection.html',1,'Face analytics pipeline with G-API'],['https://docs.opencv.org/4.2.0/d0/d1e/gapi.html',1,'Graph API'],['https://docs.opencv.org/4.2.0/d4/d48/tutorial_gapi_face_beautification.html',1,'Implementing a face beautification algorithm with G-API'],['https://docs.opencv.org/4.2.0/d0/d25/gapi_kernel_api.html',1,'Kernel API'],['https://docs.opencv.org/4.2.0/d3/d7a/tutorial_gapi_anisotropic_segmentation.html',1,'Porting anisotropic image segmentation on G-API'],['https://docs.opencv.org/4.2.0/d5/d47/tutorial_table_of_content_facemark.html',1,'Tutorial on Facial Landmark Detector API'],['https://docs.opencv.org/4.2.0/d7/dec/tutorial_facemark_usage.html',1,'Using the Facemark API'],['https://docs.opencv.org/4.2.0/d6/dc9/gapi_purposes.html',1,'Why Graph API?']]],
  ['api_20gapi_20module_82',['Graph API (gapi module)',['https://docs.opencv.org/4.2.0/df/d7e/tutorial_table_of_content_gapi.html',1,'']]],
  ['api_20overview_83',['G-API Overview',['https://docs.opencv.org/4.2.0/db/d87/md_gapi_doc_slides_README.html',1,'']]],
  ['api_20stitcher_20class_84',['High level stitching API (Stitcher class)',['https://docs.opencv.org/4.2.0/d8/d19/tutorial_stitcher.html',1,'']]],
  ['application_85',['application',['https://docs.opencv.org/4.2.0/d5/df3/tutorial_js_trackbar.html',1,'Add a Trackbar to Your Application'],['https://docs.opencv.org/4.2.0/d7/d21/tutorial_interactive_calibration.html',1,'Interactive camera calibration application'],['https://docs.opencv.org/4.2.0/d7/dbd/tutorial_android_ocl_intro.html',1,'Use OpenCL in Android camera preview based CV application']]],
  ['applications_86',['applications',['https://docs.opencv.org/4.2.0/da/d6a/tutorial_trackbar.html',1,'Adding a Trackbar to our applications!'],['https://docs.opencv.org/4.2.0/d7/dcf/tutorial_cvv_introduction.html',1,'Interactive Visual Debugging of Computer Vision applications']]],
  ['applications_20with_20opencv_20inside_20the_20microsoft_20visual_20studio_87',['How to build applications with OpenCV inside the &quot;Microsoft Visual Studio&quot;',['https://docs.opencv.org/4.2.0/dd/d6e/tutorial_windows_visual_studio_opencv.html',1,'']]],
  ['arithmetic_20operations_20on_20images_88',['arithmetic operations on images',['https://docs.opencv.org/4.2.0/dd/d4d/tutorial_js_image_arithmetics.html',1,'Arithmetic Operations on Images'],['https://docs.opencv.org/4.2.0/d0/d86/tutorial_py_image_arithmetics.html',1,'Arithmetic Operations on Images']]],
  ['arm_20based_20linux_20systems_89',['Cross compilation for ARM based Linux systems',['https://docs.opencv.org/4.2.0/d0/d76/tutorial_arm_crosscompile_with_cmake.html',1,'']]],
  ['aruco_20and_20charuco_90',['Calibration with ArUco and ChArUco',['https://docs.opencv.org/4.2.0/da/d13/tutorial_aruco_calibration.html',1,'']]],
  ['aruco_20boards_91',['Detection of ArUco Boards',['https://docs.opencv.org/4.2.0/db/da9/tutorial_aruco_board_detection.html',1,'']]],
  ['aruco_20marker_20detection_20aruco_20module_92',['ArUco marker detection (aruco module)',['https://docs.opencv.org/4.2.0/d9/d6d/tutorial_table_of_content_aruco.html',1,'']]],
  ['aruco_20markers_93',['Detection of ArUco Markers',['https://docs.opencv.org/4.2.0/d5/dae/tutorial_aruco_detection.html',1,'']]],
  ['aruco_20module_20faq_94',['Aruco module FAQ',['https://docs.opencv.org/4.2.0/d1/dcb/tutorial_aruco_faq.html',1,'']]],
  ['as_20a_20paint_20brush_95',['Mouse as a Paint-Brush',['https://docs.opencv.org/4.2.0/db/d5b/tutorial_py_mouse_handling.html',1,'']]],
  ['as_20parameters_96',['Writing Functions Taking Eigen Types as Parameters',['https://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html',1,'']]],
  ['as_20the_20color_20palette_97',['Trackbar as the Color Palette',['https://docs.opencv.org/4.2.0/d9/dc8/tutorial_py_trackbar.html',1,'']]],
  ['asked_20questions_98',['Frequently Asked Questions',['https://docs.opencv.org/4.2.0/d3/d2d/faq.html',1,'']]],
  ['assertions_99',['Assertions',['https://eigen.tuxfamily.org/dox/TopicAssertions.html',1,'']]],
  ['attributes_100',['Reading and Writing Attributes',['https://docs.opencv.org/4.2.0/d5/d10/tutorial_hdf_read_write_attributes.html',1,'']]]
];
