var searchData=
[
  ['data_0',['Support Vector Machines for Non-Linearly Separable Data',['https://docs.opencv.org/4.2.0/d0/dcc/tutorial_non_linear_svms.html',1,'']]],
  ['data_20format_20hdf_20i_20o_1',['The Hierarchical Data Format (hdf) I/O',['https://docs.opencv.org/4.2.0/d3/d00/tutorial_table_of_content_hdf.html',1,'']]],
  ['data_20generation_20using_20icosphere_2',['Training data generation using Icosphere',['https://docs.opencv.org/4.2.0/d6/df4/tutorial_data_generation.html',1,'']]],
  ['data_20structures_3',['Some Data Structures',['https://docs.opencv.org/4.2.0/d5/df1/tutorial_js_some_data_structures.html',1,'']]],
  ['data_20using_20knn_4',['OCR of Hand-written Data using kNN',['https://docs.opencv.org/4.2.0/d8/d4b/tutorial_py_knn_opencv.html',1,'']]],
  ['data_20using_20svm_5',['OCR of Hand-written Data using SVM',['https://docs.opencv.org/4.2.0/dd/d3b/tutorial_py_svm_opencv.html',1,'']]],
  ['datasets_6',['Creating, Writing and Reading Datasets',['https://docs.opencv.org/4.2.0/d4/d93/tutorial_hdf_create_read_write_datasets.html',1,'']]],
  ['deblur_20filter_7',['deblur filter',['https://docs.opencv.org/4.2.0/d1/dfd/tutorial_motion_deblur_filter.html',1,'Motion Deblur Filter'],['https://docs.opencv.org/4.2.0/de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'Out-of-focus Deblur Filter']]],
  ['debugger_8',['Image Watch: viewing in-memory images in the Visual Studio debugger',['https://docs.opencv.org/4.2.0/d4/d14/tutorial_windows_visual_studio_image_watch.html',1,'']]],
  ['debugging_20of_20computer_20vision_20applications_9',['Interactive Visual Debugging of Computer Vision applications',['https://docs.opencv.org/4.2.0/d7/dcf/tutorial_cvv_introduction.html',1,'']]],
  ['decode_20gray_20code_20pattern_20tutorial_10',['Decode Gray code pattern tutorial',['https://docs.opencv.org/4.2.0/dc/da9/tutorial_decode_graycode_pattern.html',1,'']]],
  ['deep_20learning_20layers_20support_11',['Custom deep learning layers support',['https://docs.opencv.org/4.2.0/dc/db1/tutorial_dnn_custom_layers.html',1,'']]],
  ['deep_20networks_20in_20browser_12',['How to run deep networks in browser',['https://docs.opencv.org/4.2.0/d5/d86/tutorial_dnn_javascript.html',1,'']]],
  ['deep_20networks_20on_20android_20device_13',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['deep_20neural_20networks_20dnn_20module_14',['Deep Neural Networks (dnn module)',['https://docs.opencv.org/4.2.0/d2/d58/tutorial_table_of_content_dnn.html',1,'']]],
  ['denoising_15',['Image Denoising',['https://docs.opencv.org/4.2.0/d5/d69/tutorial_py_non_local_means.html',1,'']]],
  ['dense_20stereo_16',['Quasi dense Stereo',['https://docs.opencv.org/4.2.0/d7/d5a/tutorial_qds_quasi_dense_stereo.html',1,'']]],
  ['dense_20stereo_20stereo_20module_17',['Quasi Dense Stereo (stereo module)',['https://docs.opencv.org/4.2.0/d9/d58/tutorial_table_of_content_quasi_dense_stereo.html',1,'']]],
  ['deprecated_20list_18',['Deprecated List',['../deprecated.html',1,'']]],
  ['depth_20map_20from_20stereo_20images_19',['Depth Map from Stereo Images',['https://docs.opencv.org/4.2.0/dd/d53/tutorial_py_depthmap.html',1,'']]],
  ['depth_20sensors_20',['depth sensors',['https://docs.opencv.org/4.2.0/db/d08/tutorial_intelperc.html',1,'Using Creative Senz3D and other Intel Perceptual Computing SDK compatible depth sensors'],['https://docs.opencv.org/4.2.0/d7/d6f/tutorial_kinect_openni.html',1,'Using Kinect and other OpenNI compatible depth sensors']]],
  ['derivatives_21',['Sobel Derivatives',['https://docs.opencv.org/4.2.0/d2/d2c/tutorial_sobel_derivatives.html',1,'']]],
  ['description_22',['description',['https://docs.opencv.org/4.2.0/d5/dde/tutorial_feature_description.html',1,'Feature Description'],['https://docs.opencv.org/4.2.0/db/d27/tutorial_py_table_of_contents_feature2d.html',1,'Feature Detection and Description']]],
  ['design_20overview_23',['High-level design overview',['https://docs.opencv.org/4.2.0/de/d4d/gapi_hld.html',1,'']]],
  ['details_24',['Implementation details',['https://docs.opencv.org/4.2.0/d4/ddd/gapi_impl.html',1,'']]],
  ['detecting_20corners_20location_20in_20subpixels_25',['Detecting corners location in subpixels',['https://docs.opencv.org/4.2.0/dd/d92/tutorial_corner_subpixels.html',1,'']]],
  ['detection_26',['detection',['https://docs.opencv.org/4.2.0/d7/de1/tutorial_js_canny.html',1,'Canny Edge Detection'],['https://docs.opencv.org/4.2.0/da/d22/tutorial_py_canny.html',1,'Canny Edge Detection'],['https://docs.opencv.org/4.2.0/d1/d52/tutorial_face_swapping_face_landmark_detection.html',1,'Face swapping using face landmark detection'],['https://docs.opencv.org/4.2.0/df/d0c/tutorial_py_fast.html',1,'FAST Algorithm for Corner Detection'],['https://docs.opencv.org/4.2.0/d7/d66/tutorial_feature_detection.html',1,'Feature Detection'],['https://docs.opencv.org/4.2.0/dc/d0d/tutorial_py_features_harris.html',1,'Harris Corner Detection'],['https://docs.opencv.org/4.2.0/d9/de5/tutorial_py_table_of_contents_objdetect.html',1,'Object Detection'],['https://docs.opencv.org/4.2.0/dc/d73/tutorial_js_table_of_contents_objdetect.html',1,'Object Detection'],['https://docs.opencv.org/4.2.0/d0/da5/tutorial_ximgproc_prediction.html',1,'Structured forests for fast edge detection']]],
  ['detection_20and_20description_27',['Feature Detection and Description',['https://docs.opencv.org/4.2.0/db/d27/tutorial_py_table_of_contents_feature2d.html',1,'']]],
  ['detection_20aruco_20module_28',['ArUco marker detection (aruco module)',['https://docs.opencv.org/4.2.0/d9/d6d/tutorial_table_of_content_aruco.html',1,'']]],
  ['detection_20in_20a_20video_29',['Face landmark detection in a video',['https://docs.opencv.org/4.2.0/d8/d3c/tutorial_face_landmark_detection_in_video.html',1,'']]],
  ['detection_20in_20an_20image_30',['Face landmark detection in an image',['https://docs.opencv.org/4.2.0/d2/d42/tutorial_face_landmark_detection_in_an_image.html',1,'']]],
  ['detection_20in_20video_20capture_31',['Face Detection in Video Capture',['https://docs.opencv.org/4.2.0/df/d6c/tutorial_js_face_detection_camera.html',1,'']]],
  ['detection_20objdetect_20module_32',['Object Detection (objdetect module)',['https://docs.opencv.org/4.2.0/d2/d64/tutorial_table_of_content_objdetect.html',1,'']]],
  ['detection_20of_20aruco_20boards_33',['Detection of ArUco Boards',['https://docs.opencv.org/4.2.0/db/da9/tutorial_aruco_board_detection.html',1,'']]],
  ['detection_20of_20aruco_20markers_34',['Detection of ArUco Markers',['https://docs.opencv.org/4.2.0/d5/dae/tutorial_aruco_detection.html',1,'']]],
  ['detection_20of_20charuco_20corners_35',['Detection of ChArUco Corners',['https://docs.opencv.org/4.2.0/df/d4a/tutorial_charuco_detection.html',1,'']]],
  ['detection_20of_20diamond_20markers_36',['Detection of Diamond Markers',['https://docs.opencv.org/4.2.0/d5/d07/tutorial_charuco_diamond_detection.html',1,'']]],
  ['detection_20of_20planar_20objects_37',['Detection of planar objects',['https://docs.opencv.org/4.2.0/dd/dd4/tutorial_detection_of_planar_objects.html',1,'']]],
  ['detection_20using_20cnns_38',['Object Detection using CNNs',['https://docs.opencv.org/4.2.0/d2/da2/tutorial_dnn_objdetect.html',1,'']]],
  ['detection_20using_20haar_20cascades_39',['detection using haar cascades',['https://docs.opencv.org/4.2.0/d7/d8b/tutorial_py_face_detection.html',1,'Face Detection using Haar Cascades'],['https://docs.opencv.org/4.2.0/d2/d99/tutorial_js_face_detection.html',1,'Face Detection using Haar Cascades']]],
  ['detector_40',['detector',['https://docs.opencv.org/4.2.0/da/d5c/tutorial_canny_detector.html',1,'Canny Edge Detector'],['https://docs.opencv.org/4.2.0/d9/dbc/tutorial_generic_corner_detector.html',1,'Creating your own corner detector'],['https://docs.opencv.org/4.2.0/d4/d7d/tutorial_harris_detector.html',1,'Harris corner detector'],['https://docs.opencv.org/4.2.0/d8/dd8/tutorial_good_features_to_track.html',1,'Shi-Tomasi corner detector']]],
  ['detector_20api_41',['Tutorial on Facial Landmark Detector API',['https://docs.opencv.org/4.2.0/d5/d47/tutorial_table_of_content_facemark.html',1,'']]],
  ['detector_20good_20features_20to_20track_42',['Shi-Tomasi Corner Detector &amp; Good Features to Track',['https://docs.opencv.org/4.2.0/d4/d8c/tutorial_py_shi_tomasi.html',1,'']]],
  ['development_43',['development',['https://docs.opencv.org/4.2.0/d9/d3f/tutorial_android_dev_intro.html',1,'Introduction into Android Development'],['https://docs.opencv.org/4.2.0/d9/d52/tutorial_java_dev_intro.html',1,'Introduction to Java Development']]],
  ['development_20with_20clojure_44',['Introduction to OpenCV Development with Clojure',['https://docs.opencv.org/4.2.0/d7/d1e/tutorial_clojure_dev_intro.html',1,'']]],
  ['development_20with_20opencv_45',['Android Development with OpenCV',['https://docs.opencv.org/4.2.0/d5/df8/tutorial_dev_with_OCV_on_Android.html',1,'']]],
  ['device_46',['How to run deep networks on Android device',['https://docs.opencv.org/4.2.0/d0/d6c/tutorial_dnn_android.html',1,'']]],
  ['diamond_20markers_47',['Detection of Diamond Markers',['https://docs.opencv.org/4.2.0/d5/d07/tutorial_charuco_diamond_detection.html',1,'']]],
  ['dilating_48',['Eroding and Dilating',['https://docs.opencv.org/4.2.0/db/df6/tutorial_erosion_dilatation.html',1,'']]],
  ['dimensional_20phase_20maps_49',['Unwrap two-dimensional phase maps',['https://docs.opencv.org/4.2.0/d9/dfb/tutorial_unwrap.html',1,'']]],
  ['directives_50',['Preprocessor directives',['https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html',1,'']]],
  ['discovering_20the_20human_20retina_20and_20its_20use_20for_20image_20processing_51',['Discovering the human retina and its use for image processing',['https://docs.opencv.org/4.2.0/df/dee/tutorial_table_of_content_retina.html',1,'']]],
  ['discrete_20fourier_20transform_52',['Discrete Fourier Transform',['https://docs.opencv.org/4.2.0/d8/d01/tutorial_discrete_fourier_transform.html',1,'']]],
  ['disparity_20map_20post_20filtering_53',['Disparity map post-filtering',['https://docs.opencv.org/4.2.0/d3/d14/tutorial_ximgproc_disparity_filtering.html',1,'']]],
  ['display_20an_20image_54',['Load and Display an Image',['https://docs.opencv.org/4.2.0/db/deb/tutorial_display_image.html',1,'']]],
  ['distance_20transform_20and_20watershed_20algorithm_55',['Image Segmentation with Distance Transform and Watershed Algorithm',['https://docs.opencv.org/4.2.0/d2/dbd/tutorial_distance_transform.html',1,'']]],
  ['dnn_20module_56',['Deep Neural Networks (dnn module)',['https://docs.opencv.org/4.2.0/d2/d58/tutorial_table_of_content_dnn.html',1,'']]],
  ['dnns_57',['YOLO DNNs',['https://docs.opencv.org/4.2.0/da/d9d/tutorial_dnn_yolo.html',1,'']]],
  ['documentation_20for_20opencv_58',['Writing documentation for OpenCV',['https://docs.opencv.org/4.2.0/d4/db1/tutorial_documentation.html',1,'']]],
  ['doxygen_20projects_59',['Cross referencing OpenCV from other Doxygen projects',['https://docs.opencv.org/4.2.0/d3/dff/tutorial_cross_referencing.html',1,'']]],
  ['drawing_60',['Basic Drawing',['https://docs.opencv.org/4.2.0/d3/d96/tutorial_basic_geometric_drawing.html',1,'']]],
  ['drawing_20functions_20in_20opencv_61',['Drawing Functions in OpenCV',['https://docs.opencv.org/4.2.0/dc/da5/tutorial_py_drawing_functions.html',1,'']]],
  ['dynamic_20range_20hdr_62',['High Dynamic Range (HDR)',['https://docs.opencv.org/4.2.0/d2/df0/tutorial_py_hdr.html',1,'']]],
  ['dynamic_20range_20imaging_63',['High Dynamic Range Imaging',['https://docs.opencv.org/4.2.0/d3/db7/tutorial_hdr_imaging.html',1,'']]]
];
