#pragma once

class Simulator
{
    // Goal: display local obstacles around robot (ObstacleMap) and generated route
    // draw map, plot obstacles from ObstacleMap
    // plot robot location (center?), destination location (trajectory if off screen)
    // plot route generated by pather     
     
}